// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shale/delegation.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type Delegation struct {
	ent.Schema
}

func (Delegation) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.Bytes("app").
			Immutable(),
		field.String("client_id").
			Immutable(),
		field.Bytes("secret_hash").
			Immutable(),
		field.Bool("live").
			Immutable(),
		field.Bool("recordings").
			Immutable(),
		field.Json("sets", [][]byte{}).
			Immutable().
			Optional(),
		field.Json("sources", [][]byte{}).
			Immutable().
			Optional(),
		field.Time("recordings_from").
			Nillable().
			Immutable().
			Optional(),
		field.Time("recordings_to").
			Nillable().
			Immutable().
			Optional(),
		field.Time("date_ends").
			Immutable().
			Optional(),
		field.Time("date_revoked").
			Nillable().
			Optional(),
		field.Time("date_used").
			Nillable().
			Optional(),
		field.Time("date_updated"),
		field.Time("date_erased").
			Nillable().
			Optional(),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Uuid("tenant_id").
			Immutable(),
		field.Uuid("holder_id").
			Immutable(),
	}
}

func (Delegation) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
		edge.To("holder", Holder.Type).
			Unique().
			Field("holder_id").
			Required().
			Immutable(),
	}
}

func (Delegation) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Fields("date_ends").
			Edges("holder"),
	}
}

func (Delegation) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "delegation"},
	}
}
