// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shale/member.proto

package schema

import (
	ent "github.com/protobuf-orm/ent"
	entsql "github.com/protobuf-orm/ent/dialect/entsql"
	schema "github.com/protobuf-orm/ent/schema"
	edge "github.com/protobuf-orm/ent/schema/edge"
	field "github.com/protobuf-orm/ent/schema/field"
	index "github.com/protobuf-orm/ent/schema/index"
)

type SiteMember struct {
	ent.Schema
}

func (SiteMember) Fields() []ent.Field {
	return []ent.Field{
		field.Uuid("id").
			Unique().
			Immutable(),
		field.Time("date_updated"),
		field.Time("date_created").
			Immutable().
			Optional(),
		field.Uuid("tenant_id").
			Immutable(),
		field.Uuid("site_id").
			Immutable(),
		field.Uuid("holder_id").
			Optional().
			Immutable(),
		field.Uuid("reader_id").
			Optional().
			Immutable(),
	}
}

func (SiteMember) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tenant", Tenant.Type).
			Unique().
			Field("tenant_id").
			Required().
			Immutable(),
		edge.To("site", Site.Type).
			Unique().
			Field("site_id").
			Required().
			Immutable(),
		edge.To("holder", Holder.Type).
			Unique().
			Field("holder_id").
			Immutable(),
		edge.To("reader", Reader.Type).
			Unique().
			Field("reader_id").
			Immutable(),
	}
}

func (SiteMember) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("date_created", "id"),
		index.Edges("site", "holder"),
		index.Edges("site", "reader"),
	}
}

func (SiteMember) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "sitemember"},
	}
}
