// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/lesomnus/shale/internal/ent/addresspolicy"
	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// AddressPolicyDelete is the builder for deleting a AddressPolicy entity.
type AddressPolicyDelete struct {
	config
	hooks    []Hook
	mutation *AddressPolicyMutation
}

// Where appends a list predicates to the AddressPolicyDelete builder.
func (_d *AddressPolicyDelete) Where(ps ...predicate.AddressPolicy) *AddressPolicyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AddressPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AddressPolicyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AddressPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(addresspolicy.Table, sqlgraph.NewFieldSpec(addresspolicy.FieldId, field.TypeUuid))
	if ps := _d.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AddressPolicyDeleteOne is the builder for deleting a single AddressPolicy entity.
type AddressPolicyDeleteOne struct {
	_d *AddressPolicyDelete
}

// Where appends a list predicates to the AddressPolicyDelete builder.
func (_d *AddressPolicyDeleteOne) Where(ps ...predicate.AddressPolicy) *AddressPolicyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AddressPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{addresspolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AddressPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
