// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/audit"
	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// AuditUpdate is the builder for updating Audit entities.
type AuditUpdate struct {
	config
	hooks     []Hook
	mutation  *AuditMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdate) Where(ps ...predicate.Audit) *AuditUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantId sets the "tenant_id" field.
func (_u *AuditUpdate) SetTenantId(v uuid.UUID) *AuditUpdate {
	_u.mutation.SetTenantId(v)
	return _u
}

// SetNillableTenantId sets the "tenant_id" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableTenantId(v *uuid.UUID) *AuditUpdate {
	if v != nil {
		_u.SetTenantId(*v)
	}
	return _u
}

// SetActorId sets the "actor_id" field.
func (_u *AuditUpdate) SetActorId(v uuid.UUID) *AuditUpdate {
	_u.mutation.SetActorId(v)
	return _u
}

// SetNillableActorId sets the "actor_id" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableActorId(v *uuid.UUID) *AuditUpdate {
	if v != nil {
		_u.SetActorId(*v)
	}
	return _u
}

// SetTraceId sets the "trace_id" field.
func (_u *AuditUpdate) SetTraceId(v []byte) *AuditUpdate {
	_u.mutation.SetTraceId(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditUpdate) SetAction(v string) *AuditUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableAction(v *string) *AuditUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetObjectId sets the "object_id" field.
func (_u *AuditUpdate) SetObjectId(v uuid.UUID) *AuditUpdate {
	_u.mutation.SetObjectId(v)
	return _u
}

// SetNillableObjectId sets the "object_id" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableObjectId(v *uuid.UUID) *AuditUpdate {
	if v != nil {
		_u.SetObjectId(*v)
	}
	return _u
}

// SetPatch sets the "patch" field.
func (_u *AuditUpdate) SetPatch(v []byte) *AuditUpdate {
	_u.mutation.SetPatch(v)
	return _u
}

// SetActorTenantId sets the "actor_tenant_id" field.
func (_u *AuditUpdate) SetActorTenantId(v uuid.UUID) *AuditUpdate {
	_u.mutation.SetActorTenantId(v)
	return _u
}

// SetNillableActorTenantId sets the "actor_tenant_id" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableActorTenantId(v *uuid.UUID) *AuditUpdate {
	if v != nil {
		_u.SetActorTenantId(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AuditUpdate) SetValue(v []byte) *AuditUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetCounterpartTenantId sets the "counterpart_tenant_id" field.
func (_u *AuditUpdate) SetCounterpartTenantId(v uuid.UUID) *AuditUpdate {
	_u.mutation.SetCounterpartTenantId(v)
	return _u
}

// SetNillableCounterpartTenantId sets the "counterpart_tenant_id" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableCounterpartTenantId(v *uuid.UUID) *AuditUpdate {
	if v != nil {
		_u.SetCounterpartTenantId(*v)
	}
	return _u
}

// ClearCounterpartTenantId clears the value of the "counterpart_tenant_id" field.
func (_u *AuditUpdate) ClearCounterpartTenantId() *AuditUpdate {
	_u.mutation.ClearCounterpartTenantId()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *AuditUpdate) SetDomain(v uint32) *AuditUpdate {
	_u.mutation.ResetDomain()
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *AuditUpdate) SetNillableDomain(v *uint32) *AuditUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// AddDomain adds value to the "domain" field.
func (_u *AuditUpdate) AddDomain(v int32) *AuditUpdate {
	_u.mutation.AddDomain(v)
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *AuditUpdate) ClearDomain() *AuditUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdate) Mutation() *AuditMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuditUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuditUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuditUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantId(); ok {
		_spec.SetField(audit.FieldTenantId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.ActorId(); ok {
		_spec.SetField(audit.FieldActorId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.TraceId(); ok {
		_spec.SetField(audit.FieldTraceId, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(audit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectId(); ok {
		_spec.SetField(audit.FieldObjectId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.Patch(); ok {
		_spec.SetField(audit.FieldPatch, field.TypeBytes, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(audit.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.ActorTenantId(); ok {
		_spec.SetField(audit.FieldActorTenantId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(audit.FieldValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CounterpartTenantId(); ok {
		_spec.SetField(audit.FieldCounterpartTenantId, field.TypeUuid, value)
	}
	if _u.mutation.CounterpartTenantIdCleared() {
		_spec.ClearField(audit.FieldCounterpartTenantId, field.TypeUuid)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(audit.FieldDomain, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDomain(); ok {
		_spec.AddField(audit.FieldDomain, field.TypeUint32, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(audit.FieldDomain, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditUpdateOne is the builder for updating a single Audit entity.
type AuditUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AuditMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTenantId sets the "tenant_id" field.
func (_u *AuditUpdateOne) SetTenantId(v uuid.UUID) *AuditUpdateOne {
	_u.mutation.SetTenantId(v)
	return _u
}

// SetNillableTenantId sets the "tenant_id" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableTenantId(v *uuid.UUID) *AuditUpdateOne {
	if v != nil {
		_u.SetTenantId(*v)
	}
	return _u
}

// SetActorId sets the "actor_id" field.
func (_u *AuditUpdateOne) SetActorId(v uuid.UUID) *AuditUpdateOne {
	_u.mutation.SetActorId(v)
	return _u
}

// SetNillableActorId sets the "actor_id" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableActorId(v *uuid.UUID) *AuditUpdateOne {
	if v != nil {
		_u.SetActorId(*v)
	}
	return _u
}

// SetTraceId sets the "trace_id" field.
func (_u *AuditUpdateOne) SetTraceId(v []byte) *AuditUpdateOne {
	_u.mutation.SetTraceId(v)
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditUpdateOne) SetAction(v string) *AuditUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableAction(v *string) *AuditUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetObjectId sets the "object_id" field.
func (_u *AuditUpdateOne) SetObjectId(v uuid.UUID) *AuditUpdateOne {
	_u.mutation.SetObjectId(v)
	return _u
}

// SetNillableObjectId sets the "object_id" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableObjectId(v *uuid.UUID) *AuditUpdateOne {
	if v != nil {
		_u.SetObjectId(*v)
	}
	return _u
}

// SetPatch sets the "patch" field.
func (_u *AuditUpdateOne) SetPatch(v []byte) *AuditUpdateOne {
	_u.mutation.SetPatch(v)
	return _u
}

// SetActorTenantId sets the "actor_tenant_id" field.
func (_u *AuditUpdateOne) SetActorTenantId(v uuid.UUID) *AuditUpdateOne {
	_u.mutation.SetActorTenantId(v)
	return _u
}

// SetNillableActorTenantId sets the "actor_tenant_id" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableActorTenantId(v *uuid.UUID) *AuditUpdateOne {
	if v != nil {
		_u.SetActorTenantId(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *AuditUpdateOne) SetValue(v []byte) *AuditUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetCounterpartTenantId sets the "counterpart_tenant_id" field.
func (_u *AuditUpdateOne) SetCounterpartTenantId(v uuid.UUID) *AuditUpdateOne {
	_u.mutation.SetCounterpartTenantId(v)
	return _u
}

// SetNillableCounterpartTenantId sets the "counterpart_tenant_id" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableCounterpartTenantId(v *uuid.UUID) *AuditUpdateOne {
	if v != nil {
		_u.SetCounterpartTenantId(*v)
	}
	return _u
}

// ClearCounterpartTenantId clears the value of the "counterpart_tenant_id" field.
func (_u *AuditUpdateOne) ClearCounterpartTenantId() *AuditUpdateOne {
	_u.mutation.ClearCounterpartTenantId()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *AuditUpdateOne) SetDomain(v uint32) *AuditUpdateOne {
	_u.mutation.ResetDomain()
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *AuditUpdateOne) SetNillableDomain(v *uint32) *AuditUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// AddDomain adds value to the "domain" field.
func (_u *AuditUpdateOne) AddDomain(v int32) *AuditUpdateOne {
	_u.mutation.AddDomain(v)
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *AuditUpdateOne) ClearDomain() *AuditUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// Mutation returns the AuditMutation object of the builder.
func (_u *AuditUpdateOne) Mutation() *AuditMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditUpdate builder.
func (_u *AuditUpdateOne) Where(ps ...predicate.Audit) *AuditUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditUpdateOne) Select(field string, fields ...string) *AuditUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Audit entity.
func (_u *AuditUpdateOne) Save(ctx context.Context) (*Audit, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditUpdateOne) SaveX(ctx context.Context) *Audit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuditUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuditUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuditUpdateOne) sqlSave(ctx context.Context) (_node *Audit, err error) {
	_spec := sqlgraph.NewUpdateSpec(audit.Table, audit.Columns, sqlgraph.NewFieldSpec(audit.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Audit.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, audit.FieldId)
		for _, f := range fields {
			if !audit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != audit.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantId(); ok {
		_spec.SetField(audit.FieldTenantId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.ActorId(); ok {
		_spec.SetField(audit.FieldActorId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.TraceId(); ok {
		_spec.SetField(audit.FieldTraceId, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(audit.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObjectId(); ok {
		_spec.SetField(audit.FieldObjectId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.Patch(); ok {
		_spec.SetField(audit.FieldPatch, field.TypeBytes, value)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(audit.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.ActorTenantId(); ok {
		_spec.SetField(audit.FieldActorTenantId, field.TypeUuid, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(audit.FieldValue, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CounterpartTenantId(); ok {
		_spec.SetField(audit.FieldCounterpartTenantId, field.TypeUuid, value)
	}
	if _u.mutation.CounterpartTenantIdCleared() {
		_spec.ClearField(audit.FieldCounterpartTenantId, field.TypeUuid)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(audit.FieldDomain, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDomain(); ok {
		_spec.AddField(audit.FieldDomain, field.TypeUint32, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(audit.FieldDomain, field.TypeUint32)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Audit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{audit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
