// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/lamina"
	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/lesomnus/shale/internal/ent/set"
	"github.com/lesomnus/shale/internal/ent/sink"
	"github.com/lesomnus/shale/internal/ent/site"
	"github.com/lesomnus/shale/internal/ent/source"
	"github.com/lesomnus/shale/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// LaminaQuery is the builder for querying Lamina entities.
type LaminaQuery struct {
	config
	ctx        *QueryContext
	order      []lamina.OrderOption
	inters     []Interceptor
	predicates []predicate.Lamina
	withTenant *TenantQuery
	withSite   *SiteQuery
	withSet    *SetQuery
	withSource *SourceQuery
	withSink   *SinkQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LaminaQuery builder.
func (_q *LaminaQuery) Where(ps ...predicate.Lamina) *LaminaQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LaminaQuery) Limit(limit int) *LaminaQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LaminaQuery) Offset(offset int) *LaminaQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LaminaQuery) Unique(unique bool) *LaminaQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LaminaQuery) Order(o ...lamina.OrderOption) *LaminaQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *LaminaQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lamina.Table, lamina.FieldId, selector),
			sqlgraph.To(tenant.Table, tenant.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, lamina.TenantTable, lamina.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySite chains the current query on the "site" edge.
func (_q *LaminaQuery) QuerySite() *SiteQuery {
	query := (&SiteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lamina.Table, lamina.FieldId, selector),
			sqlgraph.To(site.Table, site.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, lamina.SiteTable, lamina.SiteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySet chains the current query on the "set" edge.
func (_q *LaminaQuery) QuerySet() *SetQuery {
	query := (&SetClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lamina.Table, lamina.FieldId, selector),
			sqlgraph.To(set.Table, set.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, lamina.SetTable, lamina.SetColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySource chains the current query on the "source" edge.
func (_q *LaminaQuery) QuerySource() *SourceQuery {
	query := (&SourceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lamina.Table, lamina.FieldId, selector),
			sqlgraph.To(source.Table, source.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, lamina.SourceTable, lamina.SourceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySink chains the current query on the "sink" edge.
func (_q *LaminaQuery) QuerySink() *SinkQuery {
	query := (&SinkClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lamina.Table, lamina.FieldId, selector),
			sqlgraph.To(sink.Table, sink.FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, lamina.SinkTable, lamina.SinkColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lamina entity from the query.
// Returns a *NotFoundError when no Lamina was found.
func (_q *LaminaQuery) First(ctx context.Context) (*Lamina, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lamina.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LaminaQuery) FirstX(ctx context.Context) *Lamina {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstId returns the first Lamina Id from the query.
// Returns a *NotFoundError when no Lamina Id was found.
func (_q *LaminaQuery) FirstId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryFirstId)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lamina.Label}
		return
	}
	return ids[0], nil
}

// FirstIdX is like FirstId, but panics if an error occurs.
func (_q *LaminaQuery) FirstIdX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstId(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lamina entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lamina entity is found.
// Returns a *NotFoundError when no Lamina entities are found.
func (_q *LaminaQuery) Only(ctx context.Context) (*Lamina, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lamina.Label}
	default:
		return nil, &NotSingularError{lamina.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LaminaQuery) OnlyX(ctx context.Context) *Lamina {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyId is like Only, but returns the only Lamina Id in the query.
// Returns a *NotSingularError when more than one Lamina Id is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LaminaQuery) OnlyId(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).Ids(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyId)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lamina.Label}
	default:
		err = &NotSingularError{lamina.Label}
	}
	return
}

// OnlyIdX is like OnlyId, but panics if an error occurs.
func (_q *LaminaQuery) OnlyIdX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyId(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lamina entities.
func (_q *LaminaQuery) All(ctx context.Context) ([]*Lamina, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lamina, *LaminaQuery]()
	return withInterceptors[[]*Lamina](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LaminaQuery) AllX(ctx context.Context) []*Lamina {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Ids executes the query and returns a list of Lamina Ids.
func (_q *LaminaQuery) Ids(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIds)
	if err = _q.Select(lamina.FieldId).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IdsX is like Ids, but panics if an error occurs.
func (_q *LaminaQuery) IdsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.Ids(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LaminaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LaminaQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LaminaQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LaminaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstId(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LaminaQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LaminaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LaminaQuery) Clone() *LaminaQuery {
	if _q == nil {
		return nil
	}
	return &LaminaQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]lamina.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Lamina{}, _q.predicates...),
		withTenant: _q.withTenant.Clone(),
		withSite:   _q.withSite.Clone(),
		withSet:    _q.withSet.Clone(),
		withSource: _q.withSource.Clone(),
		withSink:   _q.withSink.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LaminaQuery) WithTenant(opts ...func(*TenantQuery)) *LaminaQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithSite tells the query-builder to eager-load the nodes that are connected to
// the "site" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LaminaQuery) WithSite(opts ...func(*SiteQuery)) *LaminaQuery {
	query := (&SiteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSite = query
	return _q
}

// WithSet tells the query-builder to eager-load the nodes that are connected to
// the "set" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LaminaQuery) WithSet(opts ...func(*SetQuery)) *LaminaQuery {
	query := (&SetClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSet = query
	return _q
}

// WithSource tells the query-builder to eager-load the nodes that are connected to
// the "source" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LaminaQuery) WithSource(opts ...func(*SourceQuery)) *LaminaQuery {
	query := (&SourceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSource = query
	return _q
}

// WithSink tells the query-builder to eager-load the nodes that are connected to
// the "sink" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LaminaQuery) WithSink(opts ...func(*SinkQuery)) *LaminaQuery {
	query := (&SinkClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSink = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LaminaKey string `json:"lamina_key,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lamina.Query().
//		GroupBy(lamina.FieldLaminaKey).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LaminaQuery) GroupBy(field string, fields ...string) *LaminaGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LaminaGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = lamina.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LaminaKey string `json:"lamina_key,omitempty"`
//	}
//
//	client.Lamina.Query().
//		Select(lamina.FieldLaminaKey).
//		Scan(ctx, &v)
func (_q *LaminaQuery) Select(fields ...string) *LaminaSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LaminaSelect{LaminaQuery: _q}
	sbuild.label = lamina.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LaminaSelect configured with the given aggregations.
func (_q *LaminaQuery) Aggregate(fns ...AggregateFunc) *LaminaSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LaminaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !lamina.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LaminaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lamina, error) {
	var (
		nodes       = []*Lamina{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTenant != nil,
			_q.withSite != nil,
			_q.withSet != nil,
			_q.withSource != nil,
			_q.withSink != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lamina).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lamina{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *Lamina, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSite; query != nil {
		if err := _q.loadSite(ctx, query, nodes, nil,
			func(n *Lamina, e *Site) { n.Edges.Site = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSet; query != nil {
		if err := _q.loadSet(ctx, query, nodes, nil,
			func(n *Lamina, e *Set) { n.Edges.Set = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSource; query != nil {
		if err := _q.loadSource(ctx, query, nodes, nil,
			func(n *Lamina, e *Source) { n.Edges.Source = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSink; query != nil {
		if err := _q.loadSink(ctx, query, nodes, nil,
			func(n *Lamina, e *Sink) { n.Edges.Sink = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LaminaQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*Lamina, init func(*Lamina), assign func(*Lamina, *Tenant)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lamina)
	for i := range nodes {
		fk := nodes[i].TenantId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LaminaQuery) loadSite(ctx context.Context, query *SiteQuery, nodes []*Lamina, init func(*Lamina), assign func(*Lamina, *Site)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lamina)
	for i := range nodes {
		fk := nodes[i].SiteId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(site.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LaminaQuery) loadSet(ctx context.Context, query *SetQuery, nodes []*Lamina, init func(*Lamina), assign func(*Lamina, *Set)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lamina)
	for i := range nodes {
		fk := nodes[i].SetId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(set.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "set_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LaminaQuery) loadSource(ctx context.Context, query *SourceQuery, nodes []*Lamina, init func(*Lamina), assign func(*Lamina, *Source)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lamina)
	for i := range nodes {
		fk := nodes[i].SourceId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(source.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "source_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LaminaQuery) loadSink(ctx context.Context, query *SinkQuery, nodes []*Lamina, init func(*Lamina), assign func(*Lamina, *Sink)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Lamina)
	for i := range nodes {
		fk := nodes[i].SinkId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sink.IdIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.Id]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sink_id" returned %v`, n.Id)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *LaminaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LaminaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lamina.Table, lamina.Columns, sqlgraph.NewFieldSpec(lamina.FieldId, field.TypeUuid))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lamina.FieldId)
		for i := range fields {
			if fields[i] != lamina.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withTenant != nil {
			_spec.Node.AddColumnOnce(lamina.FieldTenantId)
		}
		if _q.withSite != nil {
			_spec.Node.AddColumnOnce(lamina.FieldSiteId)
		}
		if _q.withSet != nil {
			_spec.Node.AddColumnOnce(lamina.FieldSetId)
		}
		if _q.withSource != nil {
			_spec.Node.AddColumnOnce(lamina.FieldSourceId)
		}
		if _q.withSink != nil {
			_spec.Node.AddColumnOnce(lamina.FieldSinkId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LaminaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(lamina.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = lamina.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *LaminaQuery) Modify(modifiers ...func(s *sql.Selector)) *LaminaSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// LaminaGroupBy is the group-by builder for Lamina entities.
type LaminaGroupBy struct {
	selector
	build *LaminaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LaminaGroupBy) Aggregate(fns ...AggregateFunc) *LaminaGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LaminaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LaminaQuery, *LaminaGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LaminaGroupBy) sqlScan(ctx context.Context, root *LaminaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LaminaSelect is the builder for selecting fields of Lamina entities.
type LaminaSelect struct {
	*LaminaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LaminaSelect) Aggregate(fns ...AggregateFunc) *LaminaSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LaminaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LaminaQuery, *LaminaSelect](ctx, _s.LaminaQuery, _s, _s.inters, v)
}

func (_s *LaminaSelect) sqlScan(ctx context.Context, root *LaminaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *LaminaSelect) Modify(modifiers ...func(s *sql.Selector)) *LaminaSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
