// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/lamina"
	"github.com/lesomnus/shale/internal/ent/set"
	"github.com/lesomnus/shale/internal/ent/sink"
	"github.com/lesomnus/shale/internal/ent/site"
	"github.com/lesomnus/shale/internal/ent/source"
	"github.com/lesomnus/shale/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Lamina is the model entity for the Lamina schema.
type Lamina struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// LaminaKey holds the value of the "lamina_key" field.
	LaminaKey string `json:"lamina_key,omitempty"`
	// State holds the value of the "state" field.
	State int32 `json:"state,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// DateStarted holds the value of the "date_started" field.
	DateStarted time.Time `json:"date_started,omitempty"`
	// DateEnded holds the value of the "date_ended" field.
	DateEnded *time.Time `json:"date_ended,omitempty"`
	// EndedEstimated holds the value of the "ended_estimated" field.
	EndedEstimated bool `json:"ended_estimated,omitempty"`
	// Size holds the value of the "size" field.
	Size int64 `json:"size,omitempty"`
	// Incomplete holds the value of the "incomplete" field.
	Incomplete bool `json:"incomplete,omitempty"`
	// DateExpired holds the value of the "date_expired" field.
	DateExpired time.Time `json:"date_expired,omitempty"`
	// DateDeleted holds the value of the "date_deleted" field.
	DateDeleted *time.Time `json:"date_deleted,omitempty"`
	// DatesSynced holds the value of the "dates_synced" field.
	DatesSynced bool `json:"dates_synced,omitempty"`
	// PlacementVersion holds the value of the "placement_version" field.
	PlacementVersion int64 `json:"placement_version,omitempty"`
	// DateCommitted holds the value of the "date_committed" field.
	DateCommitted *time.Time `json:"date_committed,omitempty"`
	// DateFinished holds the value of the "date_finished" field.
	DateFinished *time.Time `json:"date_finished,omitempty"`
	// Checksum holds the value of the "checksum" field.
	Checksum []byte `json:"checksum,omitempty"`
	// Epoch holds the value of the "epoch" field.
	Epoch int64 `json:"epoch,omitempty"`
	// SkipReason holds the value of the "skip_reason" field.
	SkipReason int32 `json:"skip_reason,omitempty"`
	// TenantId holds the value of the "tenant_id" field.
	TenantId uuid.UUID `json:"tenant_id,omitempty"`
	// SiteId holds the value of the "site_id" field.
	SiteId uuid.UUID `json:"site_id,omitempty"`
	// SetId holds the value of the "set_id" field.
	SetId uuid.UUID `json:"set_id,omitempty"`
	// SourceId holds the value of the "source_id" field.
	SourceId uuid.UUID `json:"source_id,omitempty"`
	// SinkId holds the value of the "sink_id" field.
	SinkId uuid.UUID `json:"sink_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LaminaQuery when eager-loading is set.
	Edges        LaminaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LaminaEdges holds the relations/edges for other nodes in the graph.
type LaminaEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// Set holds the value of the set edge.
	Set *Set `json:"set,omitempty"`
	// Source holds the value of the source edge.
	Source *Source `json:"source,omitempty"`
	// Sink holds the value of the sink edge.
	Sink *Sink `json:"sink,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LaminaEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LaminaEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// SetOrErr returns the Set value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LaminaEdges) SetOrErr() (*Set, error) {
	if e.Set != nil {
		return e.Set, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: set.Label}
	}
	return nil, &NotLoadedError{edge: "set"}
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LaminaEdges) SourceOrErr() (*Source, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: source.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// SinkOrErr returns the Sink value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LaminaEdges) SinkOrErr() (*Sink, error) {
	if e.Sink != nil {
		return e.Sink, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: sink.Label}
	}
	return nil, &NotLoadedError{edge: "sink"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Lamina) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case lamina.FieldChecksum:
			values[i] = new([]byte)
		case lamina.FieldEndedEstimated, lamina.FieldIncomplete, lamina.FieldDatesSynced:
			values[i] = new(sql.NullBool)
		case lamina.FieldState, lamina.FieldSize, lamina.FieldPlacementVersion, lamina.FieldEpoch, lamina.FieldSkipReason:
			values[i] = new(sql.NullInt64)
		case lamina.FieldLaminaKey:
			values[i] = new(sql.NullString)
		case lamina.FieldDateUpdated, lamina.FieldDateCreated, lamina.FieldDateStarted, lamina.FieldDateEnded, lamina.FieldDateExpired, lamina.FieldDateDeleted, lamina.FieldDateCommitted, lamina.FieldDateFinished:
			values[i] = new(sql.NullTime)
		case lamina.FieldSiteId, lamina.FieldSinkId:
			values[i] = new(sql.Null[uuid.UUID])
		case lamina.FieldId, lamina.FieldTenantId, lamina.FieldSetId, lamina.FieldSourceId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Lamina fields.
func (_m *Lamina) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lamina.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case lamina.FieldLaminaKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lamina_key", values[i])
			} else if value.Valid {
				_m.LaminaKey = value.String
			}
		case lamina.FieldState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = int32(value.Int64)
			}
		case lamina.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case lamina.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case lamina.FieldDateStarted:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_started", values[i])
			} else if value.Valid {
				_m.DateStarted = value.Time
			}
		case lamina.FieldDateEnded:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_ended", values[i])
			} else if value.Valid {
				_m.DateEnded = new(time.Time)
				*_m.DateEnded = value.Time
			}
		case lamina.FieldEndedEstimated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ended_estimated", values[i])
			} else if value.Valid {
				_m.EndedEstimated = value.Bool
			}
		case lamina.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = value.Int64
			}
		case lamina.FieldIncomplete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field incomplete", values[i])
			} else if value.Valid {
				_m.Incomplete = value.Bool
			}
		case lamina.FieldDateExpired:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_expired", values[i])
			} else if value.Valid {
				_m.DateExpired = value.Time
			}
		case lamina.FieldDateDeleted:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_deleted", values[i])
			} else if value.Valid {
				_m.DateDeleted = new(time.Time)
				*_m.DateDeleted = value.Time
			}
		case lamina.FieldDatesSynced:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field dates_synced", values[i])
			} else if value.Valid {
				_m.DatesSynced = value.Bool
			}
		case lamina.FieldPlacementVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field placement_version", values[i])
			} else if value.Valid {
				_m.PlacementVersion = value.Int64
			}
		case lamina.FieldDateCommitted:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_committed", values[i])
			} else if value.Valid {
				_m.DateCommitted = new(time.Time)
				*_m.DateCommitted = value.Time
			}
		case lamina.FieldDateFinished:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_finished", values[i])
			} else if value.Valid {
				_m.DateFinished = new(time.Time)
				*_m.DateFinished = value.Time
			}
		case lamina.FieldChecksum:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field checksum", values[i])
			} else if value != nil {
				_m.Checksum = *value
			}
		case lamina.FieldEpoch:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field epoch", values[i])
			} else if value.Valid {
				_m.Epoch = value.Int64
			}
		case lamina.FieldSkipReason:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skip_reason", values[i])
			} else if value.Valid {
				_m.SkipReason = int32(value.Int64)
			}
		case lamina.FieldTenantId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantId = *value
			}
		case lamina.FieldSiteId:
			if value, ok := values[i].(*sql.Null[uuid.UUID]); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteId = value.V
			}
		case lamina.FieldSetId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field set_id", values[i])
			} else if value != nil {
				_m.SetId = *value
			}
		case lamina.FieldSourceId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value != nil {
				_m.SourceId = *value
			}
		case lamina.FieldSinkId:
			if value, ok := values[i].(*sql.Null[uuid.UUID]); !ok {
				return fmt.Errorf("unexpected type %T for field sink_id", values[i])
			} else if value.Valid {
				_m.SinkId = value.V
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Lamina.
// This includes values selected through modifiers, order, etc.
func (_m *Lamina) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Lamina entity.
func (_m *Lamina) QueryTenant() *TenantQuery {
	return NewLaminaClient(_m.config).QueryTenant(_m)
}

// QuerySite queries the "site" edge of the Lamina entity.
func (_m *Lamina) QuerySite() *SiteQuery {
	return NewLaminaClient(_m.config).QuerySite(_m)
}

// QuerySet queries the "set" edge of the Lamina entity.
func (_m *Lamina) QuerySet() *SetQuery {
	return NewLaminaClient(_m.config).QuerySet(_m)
}

// QuerySource queries the "source" edge of the Lamina entity.
func (_m *Lamina) QuerySource() *SourceQuery {
	return NewLaminaClient(_m.config).QuerySource(_m)
}

// QuerySink queries the "sink" edge of the Lamina entity.
func (_m *Lamina) QuerySink() *SinkQuery {
	return NewLaminaClient(_m.config).QuerySink(_m)
}

// Update returns a builder for updating this Lamina.
// Note that you need to call Lamina.Unwrap() before calling this method if this Lamina
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Lamina) Update() *LaminaUpdateOne {
	return NewLaminaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Lamina entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Lamina) Unwrap() *Lamina {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Lamina is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Lamina) String() string {
	var builder strings.Builder
	builder.WriteString("Lamina(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("lamina_key=")
	builder.WriteString(_m.LaminaKey)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("date_started=")
	builder.WriteString(_m.DateStarted.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateEnded; v != nil {
		builder.WriteString("date_ended=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("ended_estimated=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndedEstimated))
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", _m.Size))
	builder.WriteString(", ")
	builder.WriteString("incomplete=")
	builder.WriteString(fmt.Sprintf("%v", _m.Incomplete))
	builder.WriteString(", ")
	builder.WriteString("date_expired=")
	builder.WriteString(_m.DateExpired.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateDeleted; v != nil {
		builder.WriteString("date_deleted=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("dates_synced=")
	builder.WriteString(fmt.Sprintf("%v", _m.DatesSynced))
	builder.WriteString(", ")
	builder.WriteString("placement_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlacementVersion))
	builder.WriteString(", ")
	if v := _m.DateCommitted; v != nil {
		builder.WriteString("date_committed=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DateFinished; v != nil {
		builder.WriteString("date_finished=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("checksum=")
	builder.WriteString(fmt.Sprintf("%v", _m.Checksum))
	builder.WriteString(", ")
	builder.WriteString("epoch=")
	builder.WriteString(fmt.Sprintf("%v", _m.Epoch))
	builder.WriteString(", ")
	builder.WriteString("skip_reason=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipReason))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantId))
	builder.WriteString(", ")
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SiteId))
	builder.WriteString(", ")
	builder.WriteString("set_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SetId))
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceId))
	builder.WriteString(", ")
	builder.WriteString("sink_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SinkId))
	builder.WriteByte(')')
	return builder.String()
}

// LaminaList is a parsable slice of Lamina.
type LaminaList []*Lamina
