// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/object"
	"github.com/lesomnus/shale/internal/ent/set"
	"github.com/lesomnus/shale/internal/ent/sink"
	"github.com/lesomnus/shale/internal/ent/site"
	"github.com/lesomnus/shale/internal/ent/source"
	"github.com/lesomnus/shale/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// ObjectCreate is the builder for creating a Object entity.
type ObjectCreate struct {
	config
	mutation *ObjectMutation
	hooks    []Hook
}

// SetObjectKey sets the "object_key" field.
func (_c *ObjectCreate) SetObjectKey(v string) *ObjectCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ObjectCreate) SetState(v int32) *ObjectCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *ObjectCreate) SetDateUpdated(v time.Time) *ObjectCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *ObjectCreate) SetDateCreated(v time.Time) *ObjectCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateCreated(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetDateStarted sets the "date_started" field.
func (_c *ObjectCreate) SetDateStarted(v time.Time) *ObjectCreate {
	_c.mutation.SetDateStarted(v)
	return _c
}

// SetNillableDateStarted sets the "date_started" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateStarted(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateStarted(*v)
	}
	return _c
}

// SetDateEnded sets the "date_ended" field.
func (_c *ObjectCreate) SetDateEnded(v time.Time) *ObjectCreate {
	_c.mutation.SetDateEnded(v)
	return _c
}

// SetNillableDateEnded sets the "date_ended" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateEnded(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateEnded(*v)
	}
	return _c
}

// SetEndedEstimated sets the "ended_estimated" field.
func (_c *ObjectCreate) SetEndedEstimated(v bool) *ObjectCreate {
	_c.mutation.SetEndedEstimated(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *ObjectCreate) SetSize(v int64) *ObjectCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetIncomplete sets the "incomplete" field.
func (_c *ObjectCreate) SetIncomplete(v bool) *ObjectCreate {
	_c.mutation.SetIncomplete(v)
	return _c
}

// SetDateExpired sets the "date_expired" field.
func (_c *ObjectCreate) SetDateExpired(v time.Time) *ObjectCreate {
	_c.mutation.SetDateExpired(v)
	return _c
}

// SetNillableDateExpired sets the "date_expired" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateExpired(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateExpired(*v)
	}
	return _c
}

// SetDateDeleted sets the "date_deleted" field.
func (_c *ObjectCreate) SetDateDeleted(v time.Time) *ObjectCreate {
	_c.mutation.SetDateDeleted(v)
	return _c
}

// SetNillableDateDeleted sets the "date_deleted" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateDeleted(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateDeleted(*v)
	}
	return _c
}

// SetDatesSynced sets the "dates_synced" field.
func (_c *ObjectCreate) SetDatesSynced(v bool) *ObjectCreate {
	_c.mutation.SetDatesSynced(v)
	return _c
}

// SetPlacementVersion sets the "placement_version" field.
func (_c *ObjectCreate) SetPlacementVersion(v int64) *ObjectCreate {
	_c.mutation.SetPlacementVersion(v)
	return _c
}

// SetDateCommitted sets the "date_committed" field.
func (_c *ObjectCreate) SetDateCommitted(v time.Time) *ObjectCreate {
	_c.mutation.SetDateCommitted(v)
	return _c
}

// SetNillableDateCommitted sets the "date_committed" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateCommitted(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateCommitted(*v)
	}
	return _c
}

// SetDateFinished sets the "date_finished" field.
func (_c *ObjectCreate) SetDateFinished(v time.Time) *ObjectCreate {
	_c.mutation.SetDateFinished(v)
	return _c
}

// SetNillableDateFinished sets the "date_finished" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDateFinished(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDateFinished(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *ObjectCreate) SetChecksum(v []byte) *ObjectCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetEpoch sets the "epoch" field.
func (_c *ObjectCreate) SetEpoch(v int64) *ObjectCreate {
	_c.mutation.SetEpoch(v)
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *ObjectCreate) SetTenantId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetSiteId sets the "site_id" field.
func (_c *ObjectCreate) SetSiteId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetSiteId(v)
	return _c
}

// SetNillableSiteId sets the "site_id" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableSiteId(v *uuid.UUID) *ObjectCreate {
	if v != nil {
		_c.SetSiteId(*v)
	}
	return _c
}

// SetSetId sets the "set_id" field.
func (_c *ObjectCreate) SetSetId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetSetId(v)
	return _c
}

// SetSourceId sets the "source_id" field.
func (_c *ObjectCreate) SetSourceId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetSourceId(v)
	return _c
}

// SetSinkId sets the "sink_id" field.
func (_c *ObjectCreate) SetSinkId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetSinkId(v)
	return _c
}

// SetNillableSinkId sets the "sink_id" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableSinkId(v *uuid.UUID) *ObjectCreate {
	if v != nil {
		_c.SetSinkId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *ObjectCreate) SetId(v uuid.UUID) *ObjectCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ObjectCreate) SetTenant(v *Tenant) *ObjectCreate {
	return _c.SetTenantId(v.Id)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *ObjectCreate) SetSite(v *Site) *ObjectCreate {
	return _c.SetSiteId(v.Id)
}

// SetSet sets the "set" edge to the Set entity.
func (_c *ObjectCreate) SetSet(v *Set) *ObjectCreate {
	return _c.SetSetId(v.Id)
}

// SetSource sets the "source" edge to the Source entity.
func (_c *ObjectCreate) SetSource(v *Source) *ObjectCreate {
	return _c.SetSourceId(v.Id)
}

// SetSink sets the "sink" edge to the Sink entity.
func (_c *ObjectCreate) SetSink(v *Sink) *ObjectCreate {
	return _c.SetSinkId(v.Id)
}

// Mutation returns the ObjectMutation object of the builder.
func (_c *ObjectCreate) Mutation() *ObjectMutation {
	return _c.mutation
}

// Save creates the Object in the database.
func (_c *ObjectCreate) Save(ctx context.Context) (*Object, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectCreate) SaveX(ctx context.Context) *Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectCreate) check() error {
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "Object.object_key"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Object.state"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Object.date_updated"`)}
	}
	if _, ok := _c.mutation.EndedEstimated(); !ok {
		return &ValidationError{Name: "ended_estimated", err: errors.New(`ent: missing required field "Object.ended_estimated"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Object.size"`)}
	}
	if _, ok := _c.mutation.Incomplete(); !ok {
		return &ValidationError{Name: "incomplete", err: errors.New(`ent: missing required field "Object.incomplete"`)}
	}
	if _, ok := _c.mutation.DatesSynced(); !ok {
		return &ValidationError{Name: "dates_synced", err: errors.New(`ent: missing required field "Object.dates_synced"`)}
	}
	if _, ok := _c.mutation.PlacementVersion(); !ok {
		return &ValidationError{Name: "placement_version", err: errors.New(`ent: missing required field "Object.placement_version"`)}
	}
	if _, ok := _c.mutation.Epoch(); !ok {
		return &ValidationError{Name: "epoch", err: errors.New(`ent: missing required field "Object.epoch"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Object.tenant_id"`)}
	}
	if _, ok := _c.mutation.GetSetId(); !ok {
		return &ValidationError{Name: "set_id", err: errors.New(`ent: missing required field "Object.set_id"`)}
	}
	if _, ok := _c.mutation.SourceId(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "Object.source_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Object.tenant"`)}
	}
	if len(_c.mutation.SetIds()) == 0 {
		return &ValidationError{Name: "set", err: errors.New(`ent: missing required edge "Object.set"`)}
	}
	if len(_c.mutation.SourceIds()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "Object.source"`)}
	}
	return nil
}

func (_c *ObjectCreate) sqlSave(ctx context.Context) (*Object, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectCreate) createSpec() (*Object, *sqlgraph.CreateSpec) {
	var (
		_node = &Object{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(object.Table, sqlgraph.NewFieldSpec(object.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(object.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(object.FieldState, field.TypeInt32, value)
		_node.State = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(object.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(object.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if value, ok := _c.mutation.DateStarted(); ok {
		_spec.SetField(object.FieldDateStarted, field.TypeTime, value)
		_node.DateStarted = value
	}
	if value, ok := _c.mutation.DateEnded(); ok {
		_spec.SetField(object.FieldDateEnded, field.TypeTime, value)
		_node.DateEnded = &value
	}
	if value, ok := _c.mutation.EndedEstimated(); ok {
		_spec.SetField(object.FieldEndedEstimated, field.TypeBool, value)
		_node.EndedEstimated = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(object.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Incomplete(); ok {
		_spec.SetField(object.FieldIncomplete, field.TypeBool, value)
		_node.Incomplete = value
	}
	if value, ok := _c.mutation.DateExpired(); ok {
		_spec.SetField(object.FieldDateExpired, field.TypeTime, value)
		_node.DateExpired = value
	}
	if value, ok := _c.mutation.DateDeleted(); ok {
		_spec.SetField(object.FieldDateDeleted, field.TypeTime, value)
		_node.DateDeleted = &value
	}
	if value, ok := _c.mutation.DatesSynced(); ok {
		_spec.SetField(object.FieldDatesSynced, field.TypeBool, value)
		_node.DatesSynced = value
	}
	if value, ok := _c.mutation.PlacementVersion(); ok {
		_spec.SetField(object.FieldPlacementVersion, field.TypeInt64, value)
		_node.PlacementVersion = value
	}
	if value, ok := _c.mutation.DateCommitted(); ok {
		_spec.SetField(object.FieldDateCommitted, field.TypeTime, value)
		_node.DateCommitted = &value
	}
	if value, ok := _c.mutation.DateFinished(); ok {
		_spec.SetField(object.FieldDateFinished, field.TypeTime, value)
		_node.DateFinished = &value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(object.FieldChecksum, field.TypeBytes, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.Epoch(); ok {
		_spec.SetField(object.FieldEpoch, field.TypeInt64, value)
		_node.Epoch = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   object.TenantTable,
			Columns: []string{object.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   object.SiteTable,
			Columns: []string{object.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(site.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SetIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   object.SetTable,
			Columns: []string{object.SetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(set.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SetId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   object.SourceTable,
			Columns: []string{object.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(source.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SourceId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SinkIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   object.SinkTable,
			Columns: []string{object.SinkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(sink.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SinkId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ObjectCreateBulk is the builder for creating many Object entities in bulk.
type ObjectCreateBulk struct {
	config
	err      error
	builders []*ObjectCreate
}

// Save creates the Object entities in the database.
func (_c *ObjectCreateBulk) Save(ctx context.Context) ([]*Object, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Object, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectCreateBulk) SaveX(ctx context.Context) []*Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
