// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/shale/api"
	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/lesomnus/shale/internal/ent/set"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// SetUpdate is the builder for updating Set entities.
type SetUpdate struct {
	config
	hooks     []Hook
	mutation  *SetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SetUpdate builder.
func (_u *SetUpdate) Where(ps ...predicate.Set) *SetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAlias sets the "alias" field.
func (_u *SetUpdate) SetAlias(v string) *SetUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *SetUpdate) SetNillableAlias(v *string) *SetUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SetUpdate) SetName(v string) *SetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SetUpdate) SetNillableName(v *string) *SetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *SetUpdate) SetDesc(v string) *SetUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *SetUpdate) SetNillableDesc(v *string) *SetUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *SetUpdate) SetLabels(v map[string]string) *SetUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *SetUpdate) ClearLabels() *SetUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetPlacement sets the "placement" field.
func (_u *SetUpdate) SetPlacement(v *api.SetPlacement) *SetUpdate {
	_u.mutation.SetPlacement(v)
	return _u
}

// ClearPlacement clears the value of the "placement" field.
func (_u *SetUpdate) ClearPlacement() *SetUpdate {
	_u.mutation.ClearPlacement()
	return _u
}

// SetRetention sets the "retention" field.
func (_u *SetUpdate) SetRetention(v *api.SetRetention) *SetUpdate {
	_u.mutation.SetRetention(v)
	return _u
}

// ClearRetention clears the value of the "retention" field.
func (_u *SetUpdate) ClearRetention() *SetUpdate {
	_u.mutation.ClearRetention()
	return _u
}

// SetLink sets the "link" field.
func (_u *SetUpdate) SetLink(v *api.LinkProfile) *SetUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *SetUpdate) ClearLink() *SetUpdate {
	_u.mutation.ClearLink()
	return _u
}

// SetMaxBitrateTotal sets the "max_bitrate_total" field.
func (_u *SetUpdate) SetMaxBitrateTotal(v int64) *SetUpdate {
	_u.mutation.ResetMaxBitrateTotal()
	_u.mutation.SetMaxBitrateTotal(v)
	return _u
}

// SetNillableMaxBitrateTotal sets the "max_bitrate_total" field if the given value is not nil.
func (_u *SetUpdate) SetNillableMaxBitrateTotal(v *int64) *SetUpdate {
	if v != nil {
		_u.SetMaxBitrateTotal(*v)
	}
	return _u
}

// AddMaxBitrateTotal adds value to the "max_bitrate_total" field.
func (_u *SetUpdate) AddMaxBitrateTotal(v int64) *SetUpdate {
	_u.mutation.AddMaxBitrateTotal(v)
	return _u
}

// SetAutoRaise sets the "auto_raise" field.
func (_u *SetUpdate) SetAutoRaise(v bool) *SetUpdate {
	_u.mutation.SetAutoRaise(v)
	return _u
}

// SetNillableAutoRaise sets the "auto_raise" field if the given value is not nil.
func (_u *SetUpdate) SetNillableAutoRaise(v *bool) *SetUpdate {
	if v != nil {
		_u.SetAutoRaise(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *SetUpdate) SetDateUpdated(v time.Time) *SetUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *SetUpdate) SetNillableDateUpdated(v *time.Time) *SetUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *SetUpdate) SetDateErased(v time.Time) *SetUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *SetUpdate) SetNillableDateErased(v *time.Time) *SetUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *SetUpdate) ClearDateErased() *SetUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *SetUpdate) SetChecksum(v bool) *SetUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *SetUpdate) SetNillableChecksum(v *bool) *SetUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetProfileVersion sets the "profile_version" field.
func (_u *SetUpdate) SetProfileVersion(v int64) *SetUpdate {
	_u.mutation.ResetProfileVersion()
	_u.mutation.SetProfileVersion(v)
	return _u
}

// SetNillableProfileVersion sets the "profile_version" field if the given value is not nil.
func (_u *SetUpdate) SetNillableProfileVersion(v *int64) *SetUpdate {
	if v != nil {
		_u.SetProfileVersion(*v)
	}
	return _u
}

// AddProfileVersion adds value to the "profile_version" field.
func (_u *SetUpdate) AddProfileVersion(v int64) *SetUpdate {
	_u.mutation.AddProfileVersion(v)
	return _u
}

// Mutation returns the SetMutation object of the builder.
func (_u *SetUpdate) Mutation() *SetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SetUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Set.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SetUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SetUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(set.Table, set.Columns, sqlgraph.NewFieldSpec(set.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(set.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(set.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(set.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(set.FieldLabels, field.TypeJson, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(set.FieldLabels, field.TypeJson)
	}
	if value, ok := _u.mutation.Placement(); ok {
		vv, err := set.ValueScanner.Placement.Value(value)
		if err != nil {
			return 0, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return 0, err
		}
		_spec.SetField(set.FieldPlacement, field.TypeJson, vv)
	}
	if _u.mutation.PlacementCleared() {
		_spec.ClearField(set.FieldPlacement, field.TypeJson)
	}
	if value, ok := _u.mutation.Retention(); ok {
		vv, err := set.ValueScanner.Retention.Value(value)
		if err != nil {
			return 0, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return 0, err
		}
		_spec.SetField(set.FieldRetention, field.TypeJson, vv)
	}
	if _u.mutation.RetentionCleared() {
		_spec.ClearField(set.FieldRetention, field.TypeJson)
	}
	if value, ok := _u.mutation.Link(); ok {
		vv, err := set.ValueScanner.Link.Value(value)
		if err != nil {
			return 0, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return 0, err
		}
		_spec.SetField(set.FieldLink, field.TypeJson, vv)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(set.FieldLink, field.TypeJson)
	}
	if value, ok := _u.mutation.MaxBitrateTotal(); ok {
		_spec.SetField(set.FieldMaxBitrateTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxBitrateTotal(); ok {
		_spec.AddField(set.FieldMaxBitrateTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AutoRaise(); ok {
		_spec.SetField(set.FieldAutoRaise, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(set.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(set.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(set.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(set.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(set.FieldChecksum, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProfileVersion(); ok {
		_spec.SetField(set.FieldProfileVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProfileVersion(); ok {
		_spec.AddField(set.FieldProfileVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{set.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SetUpdateOne is the builder for updating a single Set entity.
type SetUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SetMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAlias sets the "alias" field.
func (_u *SetUpdateOne) SetAlias(v string) *SetUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableAlias(v *string) *SetUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SetUpdateOne) SetName(v string) *SetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableName(v *string) *SetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDesc sets the "desc" field.
func (_u *SetUpdateOne) SetDesc(v string) *SetUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableDesc(v *string) *SetUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *SetUpdateOne) SetLabels(v map[string]string) *SetUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *SetUpdateOne) ClearLabels() *SetUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetPlacement sets the "placement" field.
func (_u *SetUpdateOne) SetPlacement(v *api.SetPlacement) *SetUpdateOne {
	_u.mutation.SetPlacement(v)
	return _u
}

// ClearPlacement clears the value of the "placement" field.
func (_u *SetUpdateOne) ClearPlacement() *SetUpdateOne {
	_u.mutation.ClearPlacement()
	return _u
}

// SetRetention sets the "retention" field.
func (_u *SetUpdateOne) SetRetention(v *api.SetRetention) *SetUpdateOne {
	_u.mutation.SetRetention(v)
	return _u
}

// ClearRetention clears the value of the "retention" field.
func (_u *SetUpdateOne) ClearRetention() *SetUpdateOne {
	_u.mutation.ClearRetention()
	return _u
}

// SetLink sets the "link" field.
func (_u *SetUpdateOne) SetLink(v *api.LinkProfile) *SetUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// ClearLink clears the value of the "link" field.
func (_u *SetUpdateOne) ClearLink() *SetUpdateOne {
	_u.mutation.ClearLink()
	return _u
}

// SetMaxBitrateTotal sets the "max_bitrate_total" field.
func (_u *SetUpdateOne) SetMaxBitrateTotal(v int64) *SetUpdateOne {
	_u.mutation.ResetMaxBitrateTotal()
	_u.mutation.SetMaxBitrateTotal(v)
	return _u
}

// SetNillableMaxBitrateTotal sets the "max_bitrate_total" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableMaxBitrateTotal(v *int64) *SetUpdateOne {
	if v != nil {
		_u.SetMaxBitrateTotal(*v)
	}
	return _u
}

// AddMaxBitrateTotal adds value to the "max_bitrate_total" field.
func (_u *SetUpdateOne) AddMaxBitrateTotal(v int64) *SetUpdateOne {
	_u.mutation.AddMaxBitrateTotal(v)
	return _u
}

// SetAutoRaise sets the "auto_raise" field.
func (_u *SetUpdateOne) SetAutoRaise(v bool) *SetUpdateOne {
	_u.mutation.SetAutoRaise(v)
	return _u
}

// SetNillableAutoRaise sets the "auto_raise" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableAutoRaise(v *bool) *SetUpdateOne {
	if v != nil {
		_u.SetAutoRaise(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *SetUpdateOne) SetDateUpdated(v time.Time) *SetUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableDateUpdated(v *time.Time) *SetUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *SetUpdateOne) SetDateErased(v time.Time) *SetUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableDateErased(v *time.Time) *SetUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *SetUpdateOne) ClearDateErased() *SetUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *SetUpdateOne) SetChecksum(v bool) *SetUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableChecksum(v *bool) *SetUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// SetProfileVersion sets the "profile_version" field.
func (_u *SetUpdateOne) SetProfileVersion(v int64) *SetUpdateOne {
	_u.mutation.ResetProfileVersion()
	_u.mutation.SetProfileVersion(v)
	return _u
}

// SetNillableProfileVersion sets the "profile_version" field if the given value is not nil.
func (_u *SetUpdateOne) SetNillableProfileVersion(v *int64) *SetUpdateOne {
	if v != nil {
		_u.SetProfileVersion(*v)
	}
	return _u
}

// AddProfileVersion adds value to the "profile_version" field.
func (_u *SetUpdateOne) AddProfileVersion(v int64) *SetUpdateOne {
	_u.mutation.AddProfileVersion(v)
	return _u
}

// Mutation returns the SetMutation object of the builder.
func (_u *SetUpdateOne) Mutation() *SetMutation {
	return _u.mutation
}

// Where appends a list predicates to the SetUpdate builder.
func (_u *SetUpdateOne) Where(ps ...predicate.Set) *SetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SetUpdateOne) Select(field string, fields ...string) *SetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Set entity.
func (_u *SetUpdateOne) Save(ctx context.Context) (*Set, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SetUpdateOne) SaveX(ctx context.Context) *Set {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SetUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Set.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SetUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SetUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SetUpdateOne) sqlSave(ctx context.Context) (_node *Set, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(set.Table, set.Columns, sqlgraph.NewFieldSpec(set.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Set.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, set.FieldId)
		for _, f := range fields {
			if !set.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != set.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(set.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(set.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(set.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(set.FieldLabels, field.TypeJson, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(set.FieldLabels, field.TypeJson)
	}
	if value, ok := _u.mutation.Placement(); ok {
		vv, err := set.ValueScanner.Placement.Value(value)
		if err != nil {
			return nil, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return nil, err
		}
		_spec.SetField(set.FieldPlacement, field.TypeJson, vv)
	}
	if _u.mutation.PlacementCleared() {
		_spec.ClearField(set.FieldPlacement, field.TypeJson)
	}
	if value, ok := _u.mutation.Retention(); ok {
		vv, err := set.ValueScanner.Retention.Value(value)
		if err != nil {
			return nil, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return nil, err
		}
		_spec.SetField(set.FieldRetention, field.TypeJson, vv)
	}
	if _u.mutation.RetentionCleared() {
		_spec.ClearField(set.FieldRetention, field.TypeJson)
	}
	if value, ok := _u.mutation.Link(); ok {
		vv, err := set.ValueScanner.Link.Value(value)
		if err != nil {
			return nil, err
		}
		if vv, err = field.JsonValue(vv); err != nil {
			return nil, err
		}
		_spec.SetField(set.FieldLink, field.TypeJson, vv)
	}
	if _u.mutation.LinkCleared() {
		_spec.ClearField(set.FieldLink, field.TypeJson)
	}
	if value, ok := _u.mutation.MaxBitrateTotal(); ok {
		_spec.SetField(set.FieldMaxBitrateTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxBitrateTotal(); ok {
		_spec.AddField(set.FieldMaxBitrateTotal, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AutoRaise(); ok {
		_spec.SetField(set.FieldAutoRaise, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(set.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(set.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(set.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(set.FieldDateCreated, field.TypeTime)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(set.FieldChecksum, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProfileVersion(); ok {
		_spec.SetField(set.FieldProfileVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProfileVersion(); ok {
		_spec.AddField(set.FieldProfileVersion, field.TypeInt64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Set{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{set.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
