// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/holder"
	"github.com/lesomnus/shale/internal/ent/reader"
	"github.com/lesomnus/shale/internal/ent/site"
	"github.com/lesomnus/shale/internal/ent/sitemember"
	"github.com/lesomnus/shale/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// SiteMemberCreate is the builder for creating a SiteMember entity.
type SiteMemberCreate struct {
	config
	mutation *SiteMemberMutation
	hooks    []Hook
}

// SetDateUpdated sets the "date_updated" field.
func (_c *SiteMemberCreate) SetDateUpdated(v time.Time) *SiteMemberCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *SiteMemberCreate) SetDateCreated(v time.Time) *SiteMemberCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *SiteMemberCreate) SetNillableDateCreated(v *time.Time) *SiteMemberCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *SiteMemberCreate) SetTenantId(v uuid.UUID) *SiteMemberCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetSiteId sets the "site_id" field.
func (_c *SiteMemberCreate) SetSiteId(v uuid.UUID) *SiteMemberCreate {
	_c.mutation.SetSiteId(v)
	return _c
}

// SetHolderId sets the "holder_id" field.
func (_c *SiteMemberCreate) SetHolderId(v uuid.UUID) *SiteMemberCreate {
	_c.mutation.SetHolderId(v)
	return _c
}

// SetNillableHolderId sets the "holder_id" field if the given value is not nil.
func (_c *SiteMemberCreate) SetNillableHolderId(v *uuid.UUID) *SiteMemberCreate {
	if v != nil {
		_c.SetHolderId(*v)
	}
	return _c
}

// SetReaderId sets the "reader_id" field.
func (_c *SiteMemberCreate) SetReaderId(v uuid.UUID) *SiteMemberCreate {
	_c.mutation.SetReaderId(v)
	return _c
}

// SetNillableReaderId sets the "reader_id" field if the given value is not nil.
func (_c *SiteMemberCreate) SetNillableReaderId(v *uuid.UUID) *SiteMemberCreate {
	if v != nil {
		_c.SetReaderId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *SiteMemberCreate) SetId(v uuid.UUID) *SiteMemberCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *SiteMemberCreate) SetTenant(v *Tenant) *SiteMemberCreate {
	return _c.SetTenantId(v.Id)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *SiteMemberCreate) SetSite(v *Site) *SiteMemberCreate {
	return _c.SetSiteId(v.Id)
}

// SetHolder sets the "holder" edge to the Holder entity.
func (_c *SiteMemberCreate) SetHolder(v *Holder) *SiteMemberCreate {
	return _c.SetHolderId(v.Id)
}

// SetReader sets the "reader" edge to the Reader entity.
func (_c *SiteMemberCreate) SetReader(v *Reader) *SiteMemberCreate {
	return _c.SetReaderId(v.Id)
}

// Mutation returns the SiteMemberMutation object of the builder.
func (_c *SiteMemberCreate) Mutation() *SiteMemberMutation {
	return _c.mutation
}

// Save creates the SiteMember in the database.
func (_c *SiteMemberCreate) Save(ctx context.Context) (*SiteMember, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteMemberCreate) SaveX(ctx context.Context) *SiteMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteMemberCreate) check() error {
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "SiteMember.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SiteMember.tenant_id"`)}
	}
	if _, ok := _c.mutation.SiteId(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "SiteMember.site_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "SiteMember.tenant"`)}
	}
	if len(_c.mutation.SiteIds()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "SiteMember.site"`)}
	}
	return nil
}

func (_c *SiteMemberCreate) sqlSave(ctx context.Context) (*SiteMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteMemberCreate) createSpec() (*SiteMember, *sqlgraph.CreateSpec) {
	var (
		_node = &SiteMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sitemember.Table, sqlgraph.NewFieldSpec(sitemember.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(sitemember.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(sitemember.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemember.TenantTable,
			Columns: []string{sitemember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemember.SiteTable,
			Columns: []string{sitemember.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(site.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HolderIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemember.HolderTable,
			Columns: []string{sitemember.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(holder.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HolderId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReaderIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemember.ReaderTable,
			Columns: []string{sitemember.ReaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(reader.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReaderId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SiteMemberCreateBulk is the builder for creating many SiteMember entities in bulk.
type SiteMemberCreateBulk struct {
	config
	err      error
	builders []*SiteMemberCreate
}

// Save creates the SiteMember entities in the database.
func (_c *SiteMemberCreateBulk) Save(ctx context.Context) ([]*SiteMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SiteMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteMemberCreateBulk) SaveX(ctx context.Context) []*SiteMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
