// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shale/site.proto

package ent

import (
	api "github.com/lesomnus/shale/api"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	uuid "uuid"
)

func (e *Site) Proto() *api.Site {
	x := &api.Site{}
	x.SetId(e.Id[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantId; v != *new(uuid.UUID) {
		r := &api.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	x.SetName(e.Name)
	x.SetDesc(e.Desc)
	x.SetLabels(e.Labels)
	x.SetRelaySelector(e.RelaySelector)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
