// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/site"
	"github.com/lesomnus/shale/internal/ent/tenant"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Site is the model entity for the Site schema.
type Site struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Desc holds the value of the "desc" field.
	Desc string `json:"desc,omitempty"`
	// Labels holds the value of the "labels" field.
	Labels map[string]string `json:"labels,omitempty"`
	// RelaySelector holds the value of the "relay_selector" field.
	RelaySelector map[string]string `json:"relay_selector,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// TenantId holds the value of the "tenant_id" field.
	TenantId uuid.UUID `json:"tenant_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SiteQuery when eager-loading is set.
	Edges        SiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SiteEdges holds the relations/edges for other nodes in the graph.
type SiteEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SiteEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Site) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case site.FieldLabels, site.FieldRelaySelector:
			values[i] = new([]byte)
		case site.FieldAlias, site.FieldName, site.FieldDesc:
			values[i] = new(sql.NullString)
		case site.FieldDateUpdated, site.FieldDateErased, site.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case site.FieldId, site.FieldTenantId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Site fields.
func (_m *Site) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case site.FieldId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.Id = *value
			}
		case site.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case site.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case site.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				_m.Desc = value.String
			}
		case site.FieldLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Labels); err != nil {
					return fmt.Errorf("unmarshal field labels: %w", err)
				}
			}
		case site.FieldRelaySelector:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field relay_selector", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RelaySelector); err != nil {
					return fmt.Errorf("unmarshal field relay_selector: %w", err)
				}
			}
		case site.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case site.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case site.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case site.FieldTenantId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantId = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Site.
// This includes values selected through modifiers, order, etc.
func (_m *Site) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Site entity.
func (_m *Site) QueryTenant() *TenantQuery {
	return NewSiteClient(_m.config).QueryTenant(_m)
}

// Update returns a builder for updating this Site.
// Note that you need to call Site.Unwrap() before calling this method if this Site
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Site) Update() *SiteUpdateOne {
	return NewSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Site entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Site) Unwrap() *Site {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Site is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Site) String() string {
	var builder strings.Builder
	builder.WriteString("Site(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("desc=")
	builder.WriteString(_m.Desc)
	builder.WriteString(", ")
	builder.WriteString("labels=")
	builder.WriteString(fmt.Sprintf("%v", _m.Labels))
	builder.WriteString(", ")
	builder.WriteString("relay_selector=")
	builder.WriteString(fmt.Sprintf("%v", _m.RelaySelector))
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantId))
	builder.WriteByte(')')
	return builder.String()
}

// SiteList is a parsable slice of Site.
type SiteList []*Site
