// Code generated by ent, DO NOT EDIT.

package delegation

import (
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldId, id))
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldId, id))
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldId, id))
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldId, ids...))
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldId, ids...))
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldId, id))
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldId, id))
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldId, id))
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldId, id))
}

// App applies equality check predicate on the "app" field. It's identical to AppEQ.
func App(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldApp, v))
}

// ClientId applies equality check predicate on the "client_id" field. It's identical to ClientIdEQ.
func ClientId(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldClientId, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldSecretHash, v))
}

// Live applies equality check predicate on the "live" field. It's identical to LiveEQ.
func Live(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldLive, v))
}

// Recordings applies equality check predicate on the "recordings" field. It's identical to RecordingsEQ.
func Recordings(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordings, v))
}

// RecordingsFrom applies equality check predicate on the "recordings_from" field. It's identical to RecordingsFromEQ.
func RecordingsFrom(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordingsFrom, v))
}

// RecordingsTo applies equality check predicate on the "recordings_to" field. It's identical to RecordingsToEQ.
func RecordingsTo(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordingsTo, v))
}

// DateEnds applies equality check predicate on the "date_ends" field. It's identical to DateEndsEQ.
func DateEnds(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateEnds, v))
}

// DateRevoked applies equality check predicate on the "date_revoked" field. It's identical to DateRevokedEQ.
func DateRevoked(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateRevoked, v))
}

// DateUsed applies equality check predicate on the "date_used" field. It's identical to DateUsedEQ.
func DateUsed(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateUsed, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateUpdated, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateErased, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateCreated, v))
}

// TenantId applies equality check predicate on the "tenant_id" field. It's identical to TenantIdEQ.
func TenantId(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldTenantId, v))
}

// HolderId applies equality check predicate on the "holder_id" field. It's identical to HolderIdEQ.
func HolderId(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldHolderId, v))
}

// AppEQ applies the EQ predicate on the "app" field.
func AppEQ(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldApp, v))
}

// AppNEQ applies the NEQ predicate on the "app" field.
func AppNEQ(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldApp, v))
}

// AppIn applies the In predicate on the "app" field.
func AppIn(vs ...[]byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldApp, vs...))
}

// AppNotIn applies the NotIn predicate on the "app" field.
func AppNotIn(vs ...[]byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldApp, vs...))
}

// AppGT applies the GT predicate on the "app" field.
func AppGT(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldApp, v))
}

// AppGTE applies the GTE predicate on the "app" field.
func AppGTE(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldApp, v))
}

// AppLT applies the LT predicate on the "app" field.
func AppLT(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldApp, v))
}

// AppLTE applies the LTE predicate on the "app" field.
func AppLTE(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldApp, v))
}

// ClientIdEQ applies the EQ predicate on the "client_id" field.
func ClientIdEQ(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldClientId, v))
}

// ClientIdNEQ applies the NEQ predicate on the "client_id" field.
func ClientIdNEQ(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldClientId, v))
}

// ClientIdIn applies the In predicate on the "client_id" field.
func ClientIdIn(vs ...string) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldClientId, vs...))
}

// ClientIdNotIn applies the NotIn predicate on the "client_id" field.
func ClientIdNotIn(vs ...string) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldClientId, vs...))
}

// ClientIdGT applies the GT predicate on the "client_id" field.
func ClientIdGT(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldClientId, v))
}

// ClientIdGTE applies the GTE predicate on the "client_id" field.
func ClientIdGTE(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldClientId, v))
}

// ClientIdLT applies the LT predicate on the "client_id" field.
func ClientIdLT(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldClientId, v))
}

// ClientIdLTE applies the LTE predicate on the "client_id" field.
func ClientIdLTE(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldClientId, v))
}

// ClientIdContains applies the Contains predicate on the "client_id" field.
func ClientIdContains(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldContains(FieldClientId, v))
}

// ClientIdHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIdHasPrefix(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldHasPrefix(FieldClientId, v))
}

// ClientIdHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIdHasSuffix(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldHasSuffix(FieldClientId, v))
}

// ClientIdEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIdEqualFold(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldEqualFold(FieldClientId, v))
}

// ClientIdContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIdContainsFold(v string) predicate.Delegation {
	return predicate.Delegation(sql.FieldContainsFold(FieldClientId, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...[]byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...[]byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v []byte) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldSecretHash, v))
}

// LiveEQ applies the EQ predicate on the "live" field.
func LiveEQ(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldLive, v))
}

// LiveNEQ applies the NEQ predicate on the "live" field.
func LiveNEQ(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldLive, v))
}

// RecordingsEQ applies the EQ predicate on the "recordings" field.
func RecordingsEQ(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordings, v))
}

// RecordingsNEQ applies the NEQ predicate on the "recordings" field.
func RecordingsNEQ(v bool) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldRecordings, v))
}

// SetsIsNil applies the IsNil predicate on the "sets" field.
func SetsIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldSets))
}

// SetsNotNil applies the NotNil predicate on the "sets" field.
func SetsNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldSets))
}

// SourcesIsNil applies the IsNil predicate on the "sources" field.
func SourcesIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldSources))
}

// SourcesNotNil applies the NotNil predicate on the "sources" field.
func SourcesNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldSources))
}

// RecordingsFromEQ applies the EQ predicate on the "recordings_from" field.
func RecordingsFromEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordingsFrom, v))
}

// RecordingsFromNEQ applies the NEQ predicate on the "recordings_from" field.
func RecordingsFromNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldRecordingsFrom, v))
}

// RecordingsFromIn applies the In predicate on the "recordings_from" field.
func RecordingsFromIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldRecordingsFrom, vs...))
}

// RecordingsFromNotIn applies the NotIn predicate on the "recordings_from" field.
func RecordingsFromNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldRecordingsFrom, vs...))
}

// RecordingsFromGT applies the GT predicate on the "recordings_from" field.
func RecordingsFromGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldRecordingsFrom, v))
}

// RecordingsFromGTE applies the GTE predicate on the "recordings_from" field.
func RecordingsFromGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldRecordingsFrom, v))
}

// RecordingsFromLT applies the LT predicate on the "recordings_from" field.
func RecordingsFromLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldRecordingsFrom, v))
}

// RecordingsFromLTE applies the LTE predicate on the "recordings_from" field.
func RecordingsFromLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldRecordingsFrom, v))
}

// RecordingsFromIsNil applies the IsNil predicate on the "recordings_from" field.
func RecordingsFromIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldRecordingsFrom))
}

// RecordingsFromNotNil applies the NotNil predicate on the "recordings_from" field.
func RecordingsFromNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldRecordingsFrom))
}

// RecordingsToEQ applies the EQ predicate on the "recordings_to" field.
func RecordingsToEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldRecordingsTo, v))
}

// RecordingsToNEQ applies the NEQ predicate on the "recordings_to" field.
func RecordingsToNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldRecordingsTo, v))
}

// RecordingsToIn applies the In predicate on the "recordings_to" field.
func RecordingsToIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldRecordingsTo, vs...))
}

// RecordingsToNotIn applies the NotIn predicate on the "recordings_to" field.
func RecordingsToNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldRecordingsTo, vs...))
}

// RecordingsToGT applies the GT predicate on the "recordings_to" field.
func RecordingsToGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldRecordingsTo, v))
}

// RecordingsToGTE applies the GTE predicate on the "recordings_to" field.
func RecordingsToGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldRecordingsTo, v))
}

// RecordingsToLT applies the LT predicate on the "recordings_to" field.
func RecordingsToLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldRecordingsTo, v))
}

// RecordingsToLTE applies the LTE predicate on the "recordings_to" field.
func RecordingsToLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldRecordingsTo, v))
}

// RecordingsToIsNil applies the IsNil predicate on the "recordings_to" field.
func RecordingsToIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldRecordingsTo))
}

// RecordingsToNotNil applies the NotNil predicate on the "recordings_to" field.
func RecordingsToNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldRecordingsTo))
}

// DateEndsEQ applies the EQ predicate on the "date_ends" field.
func DateEndsEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateEnds, v))
}

// DateEndsNEQ applies the NEQ predicate on the "date_ends" field.
func DateEndsNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateEnds, v))
}

// DateEndsIn applies the In predicate on the "date_ends" field.
func DateEndsIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateEnds, vs...))
}

// DateEndsNotIn applies the NotIn predicate on the "date_ends" field.
func DateEndsNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateEnds, vs...))
}

// DateEndsGT applies the GT predicate on the "date_ends" field.
func DateEndsGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateEnds, v))
}

// DateEndsGTE applies the GTE predicate on the "date_ends" field.
func DateEndsGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateEnds, v))
}

// DateEndsLT applies the LT predicate on the "date_ends" field.
func DateEndsLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateEnds, v))
}

// DateEndsLTE applies the LTE predicate on the "date_ends" field.
func DateEndsLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateEnds, v))
}

// DateEndsIsNil applies the IsNil predicate on the "date_ends" field.
func DateEndsIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldDateEnds))
}

// DateEndsNotNil applies the NotNil predicate on the "date_ends" field.
func DateEndsNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldDateEnds))
}

// DateRevokedEQ applies the EQ predicate on the "date_revoked" field.
func DateRevokedEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateRevoked, v))
}

// DateRevokedNEQ applies the NEQ predicate on the "date_revoked" field.
func DateRevokedNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateRevoked, v))
}

// DateRevokedIn applies the In predicate on the "date_revoked" field.
func DateRevokedIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateRevoked, vs...))
}

// DateRevokedNotIn applies the NotIn predicate on the "date_revoked" field.
func DateRevokedNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateRevoked, vs...))
}

// DateRevokedGT applies the GT predicate on the "date_revoked" field.
func DateRevokedGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateRevoked, v))
}

// DateRevokedGTE applies the GTE predicate on the "date_revoked" field.
func DateRevokedGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateRevoked, v))
}

// DateRevokedLT applies the LT predicate on the "date_revoked" field.
func DateRevokedLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateRevoked, v))
}

// DateRevokedLTE applies the LTE predicate on the "date_revoked" field.
func DateRevokedLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateRevoked, v))
}

// DateRevokedIsNil applies the IsNil predicate on the "date_revoked" field.
func DateRevokedIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldDateRevoked))
}

// DateRevokedNotNil applies the NotNil predicate on the "date_revoked" field.
func DateRevokedNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldDateRevoked))
}

// DateUsedEQ applies the EQ predicate on the "date_used" field.
func DateUsedEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateUsed, v))
}

// DateUsedNEQ applies the NEQ predicate on the "date_used" field.
func DateUsedNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateUsed, v))
}

// DateUsedIn applies the In predicate on the "date_used" field.
func DateUsedIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateUsed, vs...))
}

// DateUsedNotIn applies the NotIn predicate on the "date_used" field.
func DateUsedNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateUsed, vs...))
}

// DateUsedGT applies the GT predicate on the "date_used" field.
func DateUsedGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateUsed, v))
}

// DateUsedGTE applies the GTE predicate on the "date_used" field.
func DateUsedGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateUsed, v))
}

// DateUsedLT applies the LT predicate on the "date_used" field.
func DateUsedLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateUsed, v))
}

// DateUsedLTE applies the LTE predicate on the "date_used" field.
func DateUsedLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateUsed, v))
}

// DateUsedIsNil applies the IsNil predicate on the "date_used" field.
func DateUsedIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldDateUsed))
}

// DateUsedNotNil applies the NotNil predicate on the "date_used" field.
func DateUsedNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldDateUsed))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateUpdated, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldDateErased))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Delegation {
	return predicate.Delegation(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.Delegation {
	return predicate.Delegation(sql.FieldNotNull(FieldDateCreated))
}

// TenantIdEQ applies the EQ predicate on the "tenant_id" field.
func TenantIdEQ(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldTenantId, v))
}

// TenantIdNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIdNEQ(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldTenantId, v))
}

// TenantIdIn applies the In predicate on the "tenant_id" field.
func TenantIdIn(vs ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldTenantId, vs...))
}

// TenantIdNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIdNotIn(vs ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldTenantId, vs...))
}

// HolderIdEQ applies the EQ predicate on the "holder_id" field.
func HolderIdEQ(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldEQ(FieldHolderId, v))
}

// HolderIdNEQ applies the NEQ predicate on the "holder_id" field.
func HolderIdNEQ(v uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNEQ(FieldHolderId, v))
}

// HolderIdIn applies the In predicate on the "holder_id" field.
func HolderIdIn(vs ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldIn(FieldHolderId, vs...))
}

// HolderIdNotIn applies the NotIn predicate on the "holder_id" field.
func HolderIdNotIn(vs ...uuid.UUID) predicate.Delegation {
	return predicate.Delegation(sql.FieldNotIn(FieldHolderId, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Delegation {
	return predicate.Delegation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Delegation {
	return predicate.Delegation(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHolder applies the HasEdge predicate on the "holder" edge.
func HasHolder() predicate.Delegation {
	return predicate.Delegation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHolderWith applies the HasEdge predicate on the "holder" edge with a given conditions (other predicates).
func HasHolderWith(preds ...predicate.Holder) predicate.Delegation {
	return predicate.Delegation(func(s *sql.Selector) {
		step := newHolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Delegation) predicate.Delegation {
	return predicate.Delegation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Delegation) predicate.Delegation {
	return predicate.Delegation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Delegation) predicate.Delegation {
	return predicate.Delegation(sql.NotPredicates(p))
}
