// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"github.com/protobuf-orm/ent/dialect/sql"
)

// AddressPolicy is the predicate function for addresspolicy builders.
type AddressPolicy func(*sql.Selector)

// AddressPolicyOrErr calls the predicate only if the error is not nit.
func AddressPolicyOrErr(p AddressPolicy, err error) AddressPolicy {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Attempt is the predicate function for attempt builders.
type Attempt func(*sql.Selector)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// DeviceOrErr calls the predicate only if the error is not nit.
func DeviceOrErr(p Device, err error) Device {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Holder is the predicate function for holder builders.
type Holder func(*sql.Selector)

// Lamina is the predicate function for lamina builders.
type Lamina func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeOrErr calls the predicate only if the error is not nit.
func NodeOrErr(p Node, err error) Node {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Outbox is the predicate function for outbox builders.
type Outbox func(*sql.Selector)

// PlacementPolicy is the predicate function for placementpolicy builders.
type PlacementPolicy func(*sql.Selector)

// PlacementPolicyOrErr calls the predicate only if the error is not nit.
func PlacementPolicyOrErr(p PlacementPolicy, err error) PlacementPolicy {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Producer is the predicate function for producer builders.
type Producer func(*sql.Selector)

// ProducerOrErr calls the predicate only if the error is not nit.
func ProducerOrErr(p Producer, err error) Producer {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Reader is the predicate function for reader builders.
type Reader func(*sql.Selector)

// ReaderOrErr calls the predicate only if the error is not nit.
func ReaderOrErr(p Reader, err error) Reader {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Relay is the predicate function for relay builders.
type Relay func(*sql.Selector)

// RelayOrErr calls the predicate only if the error is not nit.
func RelayOrErr(p Relay, err error) Relay {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Set is the predicate function for set builders.
type Set func(*sql.Selector)

// SetOrErr calls the predicate only if the error is not nit.
func SetOrErr(p Set, err error) Set {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// SigningKey is the predicate function for signingkey builders.
type SigningKey func(*sql.Selector)

// Sink is the predicate function for sink builders.
type Sink func(*sql.Selector)

// SinkOrErr calls the predicate only if the error is not nit.
func SinkOrErr(p Sink, err error) Sink {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// SiteMember is the predicate function for sitemember builders.
type SiteMember func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// SourceOrErr calls the predicate only if the error is not nit.
func SourceOrErr(p Source, err error) Source {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// UploadPolicy is the predicate function for uploadpolicy builders.
type UploadPolicy func(*sql.Selector)

// UploadPolicyOrErr calls the predicate only if the error is not nit.
func UploadPolicyOrErr(p UploadPolicy, err error) UploadPolicy {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
