// Code generated by ent, DO NOT EDIT.

package audit

import (
	"context"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/shale/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the Audit nodes in the graph.
type Mutation struct {
	op                    ent.Op
	typ                   string
	tenant_id             *uuid.UUID
	actor_id              *uuid.UUID
	trace_id              *[]byte
	action                *string
	object_id             *uuid.UUID
	patch                 *[]byte
	date_created          *time.Time
	actor_tenant_id       *uuid.UUID
	value                 *[]byte
	counterpart_tenant_id *uuid.UUID
	domain                *uint32
	adddomain             *int32
	clearedFields         map[string]struct{}
	predicates            []predicate.Audit
}

// NewMutation creates a new Mutation for the Audit entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "Audit",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.Audit {
	return m.predicates
}

// SetTenantId sets the "tenant_id" field.
func (m *Mutation) SetTenantId(u uuid.UUID) {
	m.tenant_id = &u
}

// TenantId returns the value of the "tenant_id" field in the mutation.
func (m *Mutation) TenantId() (r uuid.UUID, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantId resets all changes to the "tenant_id" field.
func (m *Mutation) ResetTenantId() {
	m.tenant_id = nil
}

// SetActorId sets the "actor_id" field.
func (m *Mutation) SetActorId(u uuid.UUID) {
	m.actor_id = &u
}

// ActorId returns the value of the "actor_id" field in the mutation.
func (m *Mutation) ActorId() (r uuid.UUID, exists bool) {
	v := m.actor_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetActorId resets all changes to the "actor_id" field.
func (m *Mutation) ResetActorId() {
	m.actor_id = nil
}

// SetTraceId sets the "trace_id" field.
func (m *Mutation) SetTraceId(b []byte) {
	m.trace_id = &b
}

// TraceId returns the value of the "trace_id" field in the mutation.
func (m *Mutation) TraceId() (r []byte, exists bool) {
	v := m.trace_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTraceId resets all changes to the "trace_id" field.
func (m *Mutation) ResetTraceId() {
	m.trace_id = nil
}

// SetAction sets the "action" field.
func (m *Mutation) SetAction(s string) {
	m.action = &s
}

// Action returns the value of the "action" field in the mutation.
func (m *Mutation) Action() (r string, exists bool) {
	v := m.action
	if v == nil {
		return
	}
	return *v, true
}

// ResetAction resets all changes to the "action" field.
func (m *Mutation) ResetAction() {
	m.action = nil
}

// SetObjectId sets the "object_id" field.
func (m *Mutation) SetObjectId(u uuid.UUID) {
	m.object_id = &u
}

// ObjectId returns the value of the "object_id" field in the mutation.
func (m *Mutation) ObjectId() (r uuid.UUID, exists bool) {
	v := m.object_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetObjectId resets all changes to the "object_id" field.
func (m *Mutation) ResetObjectId() {
	m.object_id = nil
}

// SetPatch sets the "patch" field.
func (m *Mutation) SetPatch(b []byte) {
	m.patch = &b
}

// Patch returns the value of the "patch" field in the mutation.
func (m *Mutation) Patch() (r []byte, exists bool) {
	v := m.patch
	if v == nil {
		return
	}
	return *v, true
}

// ResetPatch resets all changes to the "patch" field.
func (m *Mutation) ResetPatch() {
	m.patch = nil
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetActorTenantId sets the "actor_tenant_id" field.
func (m *Mutation) SetActorTenantId(u uuid.UUID) {
	m.actor_tenant_id = &u
}

// ActorTenantId returns the value of the "actor_tenant_id" field in the mutation.
func (m *Mutation) ActorTenantId() (r uuid.UUID, exists bool) {
	v := m.actor_tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetActorTenantId resets all changes to the "actor_tenant_id" field.
func (m *Mutation) ResetActorTenantId() {
	m.actor_tenant_id = nil
}

// SetValue sets the "value" field.
func (m *Mutation) SetValue(b []byte) {
	m.value = &b
}

// Value returns the value of the "value" field in the mutation.
func (m *Mutation) Value() (r []byte, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *Mutation) ResetValue() {
	m.value = nil
}

// SetCounterpartTenantId sets the "counterpart_tenant_id" field.
func (m *Mutation) SetCounterpartTenantId(u uuid.UUID) {
	m.counterpart_tenant_id = &u
}

// CounterpartTenantId returns the value of the "counterpart_tenant_id" field in the mutation.
func (m *Mutation) CounterpartTenantId() (r uuid.UUID, exists bool) {
	v := m.counterpart_tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearCounterpartTenantId clears the value of the "counterpart_tenant_id" field.
func (m *Mutation) ClearCounterpartTenantId() {
	m.counterpart_tenant_id = nil
	m.clearedFields[FieldCounterpartTenantId] = struct{}{}
}

// CounterpartTenantIdCleared returns if the "counterpart_tenant_id" field was cleared in this mutation.
func (m *Mutation) CounterpartTenantIdCleared() bool {
	_, ok := m.clearedFields[FieldCounterpartTenantId]
	return ok
}

// ResetCounterpartTenantId resets all changes to the "counterpart_tenant_id" field.
func (m *Mutation) ResetCounterpartTenantId() {
	m.counterpart_tenant_id = nil
	delete(m.clearedFields, FieldCounterpartTenantId)
}

// SetDomain sets the "domain" field.
func (m *Mutation) SetDomain(u uint32) {
	m.domain = &u
	m.adddomain = nil
}

// Domain returns the value of the "domain" field in the mutation.
func (m *Mutation) Domain() (r uint32, exists bool) {
	v := m.domain
	if v == nil {
		return
	}
	return *v, true
}

// AddDomain adds u to the "domain" field.
func (m *Mutation) AddDomain(u int32) {
	if m.adddomain != nil {
		*m.adddomain += u
	} else {
		m.adddomain = &u
	}
}

// AddedDomain returns the value that was added to the "domain" field in this mutation.
func (m *Mutation) AddedDomain() (r int32, exists bool) {
	v := m.adddomain
	if v == nil {
		return
	}
	return *v, true
}

// ClearDomain clears the value of the "domain" field.
func (m *Mutation) ClearDomain() {
	m.domain = nil
	m.adddomain = nil
	m.clearedFields[FieldDomain] = struct{}{}
}

// DomainCleared returns if the "domain" field was cleared in this mutation.
func (m *Mutation) DomainCleared() bool {
	_, ok := m.clearedFields[FieldDomain]
	return ok
}

// ResetDomain resets all changes to the "domain" field.
func (m *Mutation) ResetDomain() {
	m.domain = nil
	m.adddomain = nil
	delete(m.clearedFields, FieldDomain)
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.Audit) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Audit, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (Audit).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.tenant_id != nil {
		fields = append(fields, FieldTenantId)
	}
	if m.actor_id != nil {
		fields = append(fields, FieldActorId)
	}
	if m.trace_id != nil {
		fields = append(fields, FieldTraceId)
	}
	if m.action != nil {
		fields = append(fields, FieldAction)
	}
	if m.object_id != nil {
		fields = append(fields, FieldObjectId)
	}
	if m.patch != nil {
		fields = append(fields, FieldPatch)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.actor_tenant_id != nil {
		fields = append(fields, FieldActorTenantId)
	}
	if m.value != nil {
		fields = append(fields, FieldValue)
	}
	if m.counterpart_tenant_id != nil {
		fields = append(fields, FieldCounterpartTenantId)
	}
	if m.domain != nil {
		fields = append(fields, FieldDomain)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldTenantId:
		return m.TenantId()
	case FieldActorId:
		return m.ActorId()
	case FieldTraceId:
		return m.TraceId()
	case FieldAction:
		return m.Action()
	case FieldObjectId:
		return m.ObjectId()
	case FieldPatch:
		return m.Patch()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldActorTenantId:
		return m.ActorTenantId()
	case FieldValue:
		return m.Value()
	case FieldCounterpartTenantId:
		return m.CounterpartTenantId()
	case FieldDomain:
		return m.Domain()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Audit field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantId(v)
		return nil
	case FieldActorId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorId(v)
		return nil
	case FieldTraceId:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTraceId(v)
		return nil
	case FieldAction:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAction(v)
		return nil
	case FieldObjectId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetObjectId(v)
		return nil
	case FieldPatch:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPatch(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldActorTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetActorTenantId(v)
		return nil
	case FieldValue:
		v, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	case FieldCounterpartTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCounterpartTenantId(v)
		return nil
	case FieldDomain:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDomain(v)
		return nil
	}
	return fmt.Errorf("unknown Audit field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	var fields []string
	if m.adddomain != nil {
		fields = append(fields, FieldDomain)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case FieldDomain:
		return m.AddedDomain()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	case FieldDomain:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDomain(v)
		return nil
	}
	return fmt.Errorf("unknown Audit numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	if m.FieldCleared(FieldCounterpartTenantId) {
		fields = append(fields, FieldCounterpartTenantId)
	}
	if m.FieldCleared(FieldDomain) {
		fields = append(fields, FieldDomain)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	case FieldCounterpartTenantId:
		m.ClearCounterpartTenantId()
		return nil
	case FieldDomain:
		m.ClearDomain()
		return nil
	}
	return fmt.Errorf("unknown Audit nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldTenantId:
		m.ResetTenantId()
		return nil
	case FieldActorId:
		m.ResetActorId()
		return nil
	case FieldTraceId:
		m.ResetTraceId()
		return nil
	case FieldAction:
		m.ResetAction()
		return nil
	case FieldObjectId:
		m.ResetObjectId()
		return nil
	case FieldPatch:
		m.ResetPatch()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldActorTenantId:
		m.ResetActorTenantId()
		return nil
	case FieldValue:
		m.ResetValue()
		return nil
	case FieldCounterpartTenantId:
		m.ResetCounterpartTenantId()
		return nil
	case FieldDomain:
		m.ResetDomain()
		return nil
	}
	return fmt.Errorf("unknown Audit field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Audit unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Audit edge %s", name)
}
