// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shale/host.proto

package bare

import (
	context "context"
	errors "errors"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	api "github.com/lesomnus/shale/api"
	ent "github.com/lesomnus/shale/internal/ent"
	node "github.com/lesomnus/shale/internal/ent/node"
	predicate "github.com/lesomnus/shale/internal/ent/predicate"
	producer "github.com/lesomnus/shale/internal/ent/producer"
	reader "github.com/lesomnus/shale/internal/ent/reader"
	relay "github.com/lesomnus/shale/internal/ent/relay"
	set "github.com/lesomnus/shale/internal/ent/set"
	site "github.com/lesomnus/shale/internal/ent/site"
	ent1 "github.com/protobuf-orm/ent"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	graph "github.com/protobuf-orm/protobuf-orm/graph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	uuid "uuid"
)

type NodeServiceServer struct {
	Store

	api.UnimplementedNodeServiceServer
}

// NewNodeServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewNodeServiceServer(db *ent.Client, opts ...Option) api.NodeServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return NodeServiceServer{Store: s.Store}
}

// NodeNarrow answers with `p` and everything else that narrows a
// read of a Node: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func NodeNarrow(ctx context.Context, scope Scope, p predicate.Node) (predicate.Node, error) {
	ps := make([]predicate.Node, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, node.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.NodeScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return node.And(ps...), nil
	}
}

// narrow is [NodeNarrow] with this server's own scope.
func (s NodeServiceServer) narrow(ctx context.Context, p predicate.Node) (predicate.Node, error) {
	return NodeNarrow(ctx, s.Scope, p)
}

func (s NodeServiceServer) Add(ctx context.Context, req *api.NodeAddRequest) (*api.Node, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Node.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "shale.Node", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	q.SetHardwareId(req.GetHardwareId())
	q.SetHostname(req.GetHostname())
	q.SetState(int32(req.GetState()))
	q.SetCertSerial(req.GetCertSerial())
	if req.HasJoin() {
		q.SetJoin(req.GetJoin())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasDateAdopted() {
		q.SetDateAdopted(req.GetDateAdopted().AsTime())
	}
	if req.HasDateSeen() {
		q.SetDateSeen(req.GetDateSeen().AsTime())
	}
	if req.HasDateCertExpires() {
		q.SetDateCertExpires(req.GetDateCertExpires().AsTime())
	}
	if u := req.GetInterfaces(); len(u) > 0 {
		q.SetInterfaces(u)
	}
	if u := req.GetKeyIds(); len(u) > 0 {
		q.SetKeyIds(u)
	}
	q.SetCaHash(req.GetCaHash())
	q.SetVersion(req.GetVersion())
	q.SetControlAddress(req.GetControlAddress())
	q.SetDataAddress(req.GetDataAddress())
	if req.HasStatus() {
		q.SetStatus(req.GetStatus())
	}
	q.SetFailureScore(req.GetFailureScore())
	if req.HasDateScored() {
		q.SetDateScored(req.GetDateScored().AsTime())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Node already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Node: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.NodeService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s NodeServiceServer) Get(ctx context.Context, req *api.NodeGetRequest) (*api.Node, error) {
	p, err := NodePick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Node.Query().Where(p)
	NodeSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Node not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectNodeKey(q *ent.NodeQuery) {
	q.Select(node.FieldId)
}

func NodeSelectedFields(m *api.NodeSelect) []string {
	if m.GetAll() {
		return node.Columns
	}

	vs := make([]string, 0, len(node.Columns))
	{
		vs = append(vs, node.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, node.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, node.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, node.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, node.FieldLabels)
	}
	if m.GetHardwareId() {
		vs = append(vs, node.FieldHardwareId)
	}
	if m.GetHostname() {
		vs = append(vs, node.FieldHostname)
	}
	if m.GetState() {
		vs = append(vs, node.FieldState)
	}
	if m.GetCertSerial() {
		vs = append(vs, node.FieldCertSerial)
	}
	if m.GetJoin() {
		vs = append(vs, node.FieldJoin)
	}
	if m.GetDateUpdated() {
		vs = append(vs, node.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, node.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, node.FieldDateCreated)
	}
	if m.GetDateAdopted() {
		vs = append(vs, node.FieldDateAdopted)
	}
	if m.GetDateSeen() {
		vs = append(vs, node.FieldDateSeen)
	}
	if m.GetDateCertExpires() {
		vs = append(vs, node.FieldDateCertExpires)
	}
	if m.GetInterfaces() {
		vs = append(vs, node.FieldInterfaces)
	}
	if m.GetKeyIds() {
		vs = append(vs, node.FieldKeyIds)
	}
	if m.GetCaHash() {
		vs = append(vs, node.FieldCaHash)
	}
	if m.GetVersion() {
		vs = append(vs, node.FieldVersion)
	}
	if m.GetControlAddress() {
		vs = append(vs, node.FieldControlAddress)
	}
	if m.GetDataAddress() {
		vs = append(vs, node.FieldDataAddress)
	}
	if m.GetStatus() {
		vs = append(vs, node.FieldStatus)
	}
	if m.GetFailureScore() {
		vs = append(vs, node.FieldFailureScore)
	}
	if m.GetDateScored() {
		vs = append(vs, node.FieldDateScored)
	}

	return vs
}

func NodeSelect(q *ent.NodeQuery, m *api.NodeSelect) {
	if !m.GetAll() {
		fields := NodeSelectedFields(m)
		q.Select(fields...)
	}
}

func NodeSelectInit(q *ent.NodeQuery, m *api.NodeSelect) {
	if m != nil {
		NodeSelect(q, m)
	} else {
	}
}

func (s NodeServiceServer) Patch(ctx context.Context, req *api.NodePatchRequest) (*api.Node, error) {
	doc, err := ormpatch.FromPatchRequest(nodeOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.NodeService_Patch_FullMethodName)
}

func NodeGetKey(ctx context.Context, db *ent.Client, ref *api.NodeRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := NodePick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Node.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Node not found")
		}
		return z, err
	}

	return v, nil
}

var nodeOrmEntity = ormpatch.MustEntityOf(api.File_shale_host_proto, "Node")

var nodePatchColumns = entpatch.Columns{
	1: node.FieldId, 4: node.FieldAlias, 5: node.FieldName, 6: node.FieldDesc, 7: node.FieldLabels, 8: node.FieldHardwareId, 9: node.FieldHostname, 10: node.FieldState, 11: node.FieldCertSerial, 12: node.FieldJoin, 13: node.FieldDateUpdated, 14: node.FieldDateErased, 15: node.FieldDateCreated, 16: node.FieldDateAdopted, 17: node.FieldDateSeen, 18: node.FieldDateCertExpires, 19: node.FieldInterfaces, 20: node.FieldKeyIds, 21: node.FieldCaHash, 22: node.FieldVersion, 23: node.FieldControlAddress, 24: node.FieldDataAddress, 25: node.FieldStatus, 26: node.FieldFailureScore, 27: node.FieldDateScored}

func (s NodeServiceServer) Apply(ctx context.Context, req *api.NodeApplyRequest) (*api.Node, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.NodeService_Apply_FullMethodName)
}

func (s NodeServiceServer) apply(ctx context.Context, ref *api.NodeRef, doc *patchpb.Patch, by string) (*api.Node, error) {
	plan := &ormpatch.Plan{Entity: nodeOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(nodeOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, nodePatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := NodeGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.NodeRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, node.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Node.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Node(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Node.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Node not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Node.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Node(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Node already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Node: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Node.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Node not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s NodeServiceServer) Erase(ctx context.Context, req *api.NodeRef) (*api.NodeEraseResponse, error) {
	p, err := NodePick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Node.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.NodeEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = node.And(p, node.IdEQ(v))
	}

	u := st.Db.Node.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.NodeService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.NodeEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// NodePick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Node is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasNodeWith`, where no narrowing of a Node
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func NodePick(req *api.NodeRef) (predicate.Node, error) {
	p, err := pickNode(req)
	if err != nil {
		return nil, err
	}

	return node.And(node.DateErasedIsNil(), p), nil
}

func pickNode(req *api.NodeRef) (predicate.Node, error) {
	switch req.WhichKey() {
	case api.NodeRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return node.IdEQ(v), nil
		}
	case api.NodeRef_Alias_case:
		return node.AliasEQ(req.GetAlias()), nil
	case api.NodeRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Node")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type RelayServiceServer struct {
	Store

	api.UnimplementedRelayServiceServer
}

// NewRelayServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewRelayServiceServer(db *ent.Client, opts ...Option) api.RelayServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return RelayServiceServer{Store: s.Store}
}

// RelayNarrow answers with `p` and everything else that narrows a
// read of a Relay: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func RelayNarrow(ctx context.Context, scope Scope, p predicate.Relay) (predicate.Relay, error) {
	ps := make([]predicate.Relay, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, relay.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.RelayScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return relay.And(ps...), nil
	}
}

// narrow is [RelayNarrow] with this server's own scope.
func (s RelayServiceServer) narrow(ctx context.Context, p predicate.Relay) (predicate.Relay, error) {
	return RelayNarrow(ctx, s.Scope, p)
}

func (s RelayServiceServer) Add(ctx context.Context, req *api.RelayAddRequest) (*api.Relay, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	q := st.Db.Relay.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "shale.Relay", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	q.SetHardwareId(req.GetHardwareId())
	q.SetHostname(req.GetHostname())
	q.SetState(int32(req.GetState()))
	q.SetCertSerial(req.GetCertSerial())
	if req.HasJoin() {
		q.SetJoin(req.GetJoin())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasDateAdopted() {
		q.SetDateAdopted(req.GetDateAdopted().AsTime())
	}
	if req.HasDateSeen() {
		q.SetDateSeen(req.GetDateSeen().AsTime())
	}
	if req.HasDateCertExpires() {
		q.SetDateCertExpires(req.GetDateCertExpires().AsTime())
	}
	if u := req.GetInterfaces(); len(u) > 0 {
		q.SetInterfaces(u)
	}
	if u := req.GetKeyIds(); len(u) > 0 {
		q.SetKeyIds(u)
	}
	q.SetCaHash(req.GetCaHash())
	q.SetVersion(req.GetVersion())
	q.SetIngestAddress(req.GetIngestAddress())
	q.SetWhepAddress(req.GetWhepAddress())
	if req.HasStatus() {
		q.SetStatus(req.GetStatus())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Relay already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Relay: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.RelayService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	return u.Proto(), nil
}

func (s RelayServiceServer) Get(ctx context.Context, req *api.RelayGetRequest) (*api.Relay, error) {
	p, err := RelayPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Relay.Query().Where(p)
	RelaySelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Relay not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectRelayKey(q *ent.RelayQuery) {
	q.Select(relay.FieldId)
}

func RelaySelectedFields(m *api.RelaySelect) []string {
	if m.GetAll() {
		return relay.Columns
	}

	vs := make([]string, 0, len(relay.Columns))
	{
		vs = append(vs, relay.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, relay.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, relay.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, relay.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, relay.FieldLabels)
	}
	if m.GetHardwareId() {
		vs = append(vs, relay.FieldHardwareId)
	}
	if m.GetHostname() {
		vs = append(vs, relay.FieldHostname)
	}
	if m.GetState() {
		vs = append(vs, relay.FieldState)
	}
	if m.GetCertSerial() {
		vs = append(vs, relay.FieldCertSerial)
	}
	if m.GetJoin() {
		vs = append(vs, relay.FieldJoin)
	}
	if m.GetDateUpdated() {
		vs = append(vs, relay.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, relay.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, relay.FieldDateCreated)
	}
	if m.GetDateAdopted() {
		vs = append(vs, relay.FieldDateAdopted)
	}
	if m.GetDateSeen() {
		vs = append(vs, relay.FieldDateSeen)
	}
	if m.GetDateCertExpires() {
		vs = append(vs, relay.FieldDateCertExpires)
	}
	if m.GetInterfaces() {
		vs = append(vs, relay.FieldInterfaces)
	}
	if m.GetKeyIds() {
		vs = append(vs, relay.FieldKeyIds)
	}
	if m.GetCaHash() {
		vs = append(vs, relay.FieldCaHash)
	}
	if m.GetVersion() {
		vs = append(vs, relay.FieldVersion)
	}
	if m.GetIngestAddress() {
		vs = append(vs, relay.FieldIngestAddress)
	}
	if m.GetWhepAddress() {
		vs = append(vs, relay.FieldWhepAddress)
	}
	if m.GetStatus() {
		vs = append(vs, relay.FieldStatus)
	}

	return vs
}

func RelaySelect(q *ent.RelayQuery, m *api.RelaySelect) {
	if !m.GetAll() {
		fields := RelaySelectedFields(m)
		q.Select(fields...)
	}
}

func RelaySelectInit(q *ent.RelayQuery, m *api.RelaySelect) {
	if m != nil {
		RelaySelect(q, m)
	} else {
	}
}

func (s RelayServiceServer) Patch(ctx context.Context, req *api.RelayPatchRequest) (*api.Relay, error) {
	doc, err := ormpatch.FromPatchRequest(relayOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.RelayService_Patch_FullMethodName)
}

func RelayGetKey(ctx context.Context, db *ent.Client, ref *api.RelayRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := RelayPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Relay.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Relay not found")
		}
		return z, err
	}

	return v, nil
}

var relayOrmEntity = ormpatch.MustEntityOf(api.File_shale_host_proto, "Relay")

var relayPatchColumns = entpatch.Columns{
	1: relay.FieldId, 4: relay.FieldAlias, 5: relay.FieldName, 6: relay.FieldDesc, 7: relay.FieldLabels, 8: relay.FieldHardwareId, 9: relay.FieldHostname, 10: relay.FieldState, 11: relay.FieldCertSerial, 12: relay.FieldJoin, 13: relay.FieldDateUpdated, 14: relay.FieldDateErased, 15: relay.FieldDateCreated, 16: relay.FieldDateAdopted, 17: relay.FieldDateSeen, 18: relay.FieldDateCertExpires, 19: relay.FieldInterfaces, 20: relay.FieldKeyIds, 21: relay.FieldCaHash, 22: relay.FieldVersion, 23: relay.FieldIngestAddress, 24: relay.FieldWhepAddress, 25: relay.FieldStatus}

func (s RelayServiceServer) Apply(ctx context.Context, req *api.RelayApplyRequest) (*api.Relay, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.RelayService_Apply_FullMethodName)
}

func (s RelayServiceServer) apply(ctx context.Context, ref *api.RelayRef, doc *patchpb.Patch, by string) (*api.Relay, error) {
	plan := &ormpatch.Plan{Entity: relayOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(relayOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, relayPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := RelayGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.RelayRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, relay.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Relay.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Relay(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Relay.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Relay not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Relay.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Relay(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Relay already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Relay: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Relay.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Relay not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s RelayServiceServer) Erase(ctx context.Context, req *api.RelayRef) (*api.RelayEraseResponse, error) {
	p, err := RelayPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Relay.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.RelayEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = relay.And(p, relay.IdEQ(v))
	}

	u := st.Db.Relay.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.RelayService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.RelayEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// RelayPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Relay is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasRelayWith`, where no narrowing of a Relay
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func RelayPick(req *api.RelayRef) (predicate.Relay, error) {
	p, err := pickRelay(req)
	if err != nil {
		return nil, err
	}

	return relay.And(relay.DateErasedIsNil(), p), nil
}

func pickRelay(req *api.RelayRef) (predicate.Relay, error) {
	switch req.WhichKey() {
	case api.RelayRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return relay.IdEQ(v), nil
		}
	case api.RelayRef_Alias_case:
		return relay.AliasEQ(req.GetAlias()), nil
	case api.RelayRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Relay")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type ProducerServiceServer struct {
	Store

	api.UnimplementedProducerServiceServer
}

// NewProducerServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewProducerServiceServer(db *ent.Client, opts ...Option) api.ProducerServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return ProducerServiceServer{Store: s.Store}
}

// ProducerNarrow answers with `p` and everything else that narrows a
// read of a Producer: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func ProducerNarrow(ctx context.Context, scope Scope, p predicate.Producer) (predicate.Producer, error) {
	ps := make([]predicate.Producer, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, producer.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.ProducerScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return producer.And(ps...), nil
	}
}

// narrow is [ProducerNarrow] with this server's own scope.
func (s ProducerServiceServer) narrow(ctx context.Context, p predicate.Producer) (predicate.Producer, error) {
	return ProducerNarrow(ctx, s.Scope, p)
}

func (s ProducerServiceServer) Add(ctx context.Context, req *api.ProducerAddRequest) (*api.Producer, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *api.Producer), 0, 4)
	q := st.Db.Producer.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "shale.Producer", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *api.Producer) {
			v.SetTenant(api.Tenant_builder{Id: k[:]}.Build())
		})
	}
	if req.HasSite() {
		if k, err := SiteGetKey(ctx, st.Db, req.GetSite()); err != nil {
			return nil, err
		} else {
			q.SetSiteId(k)
			ds = append(ds, func(v *api.Producer) {
				v.SetSite(api.Site_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	if req.HasSet() {
		if k, err := SetGetKey(ctx, st.Db, req.GetSet()); err != nil {
			return nil, err
		} else {
			q.SetSetId(k)
			ds = append(ds, func(v *api.Producer) {
				v.SetSet(api.Set_builder{Id: k[:]}.Build())
			})
		}
	}
	q.SetHardwareId(req.GetHardwareId())
	q.SetHostname(req.GetHostname())
	q.SetState(int32(req.GetState()))
	q.SetCertSerial(req.GetCertSerial())
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasJoin() {
		q.SetJoin(req.GetJoin())
	}
	if req.HasDateAdopted() {
		q.SetDateAdopted(req.GetDateAdopted().AsTime())
	}
	if req.HasDateSeen() {
		q.SetDateSeen(req.GetDateSeen().AsTime())
	}
	if req.HasDateCertExpires() {
		q.SetDateCertExpires(req.GetDateCertExpires().AsTime())
	}
	if req.HasRelay() {
		if k, err := RelayGetKey(ctx, st.Db, req.GetRelay()); err != nil {
			return nil, err
		} else {
			q.SetRelayId(k)
			ds = append(ds, func(v *api.Producer) {
				v.SetRelay(api.Relay_builder{Id: k[:]}.Build())
			})
		}
	}
	if req.HasStatus() {
		q.SetStatus(req.GetStatus())
	}
	q.SetVersion(req.GetVersion())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Producer already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Producer: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.ProducerService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s ProducerServiceServer) Get(ctx context.Context, req *api.ProducerGetRequest) (*api.Producer, error) {
	p, err := ProducerPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Producer.Query().Where(p)
	ProducerSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Producer not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectProducerKey(q *ent.ProducerQuery) {
	q.Select(producer.FieldId)
}

func ProducerSelectedFields(m *api.ProducerSelect) []string {
	if m.GetAll() {
		return producer.Columns
	}

	vs := make([]string, 0, len(producer.Columns))
	{
		vs = append(vs, producer.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, producer.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, producer.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, producer.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, producer.FieldLabels)
	}
	if m.GetHardwareId() {
		vs = append(vs, producer.FieldHardwareId)
	}
	if m.GetHostname() {
		vs = append(vs, producer.FieldHostname)
	}
	if m.GetState() {
		vs = append(vs, producer.FieldState)
	}
	if m.GetCertSerial() {
		vs = append(vs, producer.FieldCertSerial)
	}
	if m.GetDateUpdated() {
		vs = append(vs, producer.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, producer.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, producer.FieldDateCreated)
	}
	if m.GetJoin() {
		vs = append(vs, producer.FieldJoin)
	}
	if m.GetDateAdopted() {
		vs = append(vs, producer.FieldDateAdopted)
	}
	if m.GetDateSeen() {
		vs = append(vs, producer.FieldDateSeen)
	}
	if m.GetDateCertExpires() {
		vs = append(vs, producer.FieldDateCertExpires)
	}
	if m.GetStatus() {
		vs = append(vs, producer.FieldStatus)
	}
	if m.GetVersion() {
		vs = append(vs, producer.FieldVersion)
	}

	return vs
}

func ProducerSelect(q *ent.ProducerQuery, m *api.ProducerSelect) {
	if !m.GetAll() {
		fields := ProducerSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
	if m.HasSite() {
		q.WithSite(func(q *ent.SiteQuery) {
			q.Where(site.DateErasedIsNil())
			SiteSelect(q, m.GetSite())
		})
	}
	if m.HasSet() {
		q.WithSet(func(q *ent.SetQuery) {
			q.Where(set.DateErasedIsNil())
			SetSelect(q, m.GetSet())
		})
	}
	if m.HasRelay() {
		q.WithRelay(func(q *ent.RelayQuery) {
			q.Where(relay.DateErasedIsNil())
			RelaySelect(q, m.GetRelay())
		})
	}
}

func ProducerSelectInit(q *ent.ProducerQuery, m *api.ProducerSelect) {
	if m != nil {
		ProducerSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
		q.WithSite(selectSiteKey)
		q.WithSet(selectSetKey)
		q.WithRelay(selectRelayKey)
	}
}

func (s ProducerServiceServer) Patch(ctx context.Context, req *api.ProducerPatchRequest) (*api.Producer, error) {
	doc, err := ormpatch.FromPatchRequest(producerOrmEntity, req.ProtoReflect(), func(ed graph.Edge, ref protoreflect.Message) (protoreflect.Value, error) {
		switch ed.Number() {
		case 3:
			k, err := SiteGetKey(ctx, s.Db, ref.Interface().(*api.SiteRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 8:
			k, err := SetGetKey(ctx, s.Db, ref.Interface().(*api.SetRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		case 20:
			k, err := RelayGetKey(ctx, s.Db, ref.Interface().(*api.RelayRef))
			if err != nil {
				return protoreflect.Value{}, err
			}
			return protoreflect.ValueOfBytes(k[:]), nil
		}
		return protoreflect.Value{}, status.Errorf(codes.Internal, "no key resolver for edge: %s", ed.Name())
	})
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.ProducerService_Patch_FullMethodName)
}

func ProducerGetKey(ctx context.Context, db *ent.Client, ref *api.ProducerRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := ProducerPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Producer.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Producer not found")
		}
		return z, err
	}

	return v, nil
}

var producerOrmEntity = ormpatch.MustEntityOf(api.File_shale_host_proto, "Producer")

var producerPatchColumns = entpatch.Columns{
	1: producer.FieldId, 2: producer.TenantColumn, 3: producer.SiteColumn, 4: producer.FieldAlias, 5: producer.FieldName, 6: producer.FieldDesc, 7: producer.FieldLabels, 8: producer.SetColumn, 9: producer.FieldHardwareId, 10: producer.FieldHostname, 11: producer.FieldState, 12: producer.FieldCertSerial, 13: producer.FieldDateUpdated, 14: producer.FieldDateErased, 15: producer.FieldDateCreated, 16: producer.FieldJoin, 17: producer.FieldDateAdopted, 18: producer.FieldDateSeen, 19: producer.FieldDateCertExpires, 20: producer.RelayColumn, 21: producer.FieldStatus, 22: producer.FieldVersion}

func (s ProducerServiceServer) Apply(ctx context.Context, req *api.ProducerApplyRequest) (*api.Producer, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.ProducerService_Apply_FullMethodName)
}

func (s ProducerServiceServer) apply(ctx context.Context, ref *api.ProducerRef, doc *patchpb.Patch, by string) (*api.Producer, error) {
	plan := &ormpatch.Plan{Entity: producerOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(producerOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, producerPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := ProducerGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.ProducerRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, producer.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Producer.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Producer(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Producer.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Producer not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Producer.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Producer(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Producer already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Producer: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Producer.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Producer not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s ProducerServiceServer) Erase(ctx context.Context, req *api.ProducerRef) (*api.ProducerEraseResponse, error) {
	p, err := ProducerPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Producer.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.ProducerEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = producer.And(p, producer.IdEQ(v))
	}

	u := st.Db.Producer.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.ProducerService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.ProducerEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// ProducerPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Producer is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasProducerWith`, where no narrowing of a Producer
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func ProducerPick(req *api.ProducerRef) (predicate.Producer, error) {
	p, err := pickProducer(req)
	if err != nil {
		return nil, err
	}

	return producer.And(producer.DateErasedIsNil(), p), nil
}

func pickProducer(req *api.ProducerRef) (predicate.Producer, error) {
	switch req.WhichKey() {
	case api.ProducerRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return producer.IdEQ(v), nil
		}
	case api.ProducerRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Producer, 0, 2)
		ps = append(ps, producer.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, producer.HasTenantWith(p))
		}
		return producer.And(ps...), nil
	case api.ProducerRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Producer")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}

type ReaderServiceServer struct {
	Store

	api.UnimplementedReaderServiceServer
}

// NewReaderServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewReaderServiceServer(db *ent.Client, opts ...Option) api.ReaderServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return ReaderServiceServer{Store: s.Store}
}

// ReaderNarrow answers with `p` and everything else that narrows a
// read of a Reader: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func ReaderNarrow(ctx context.Context, scope Scope, p predicate.Reader) (predicate.Reader, error) {
	ps := make([]predicate.Reader, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, reader.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.ReaderScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return reader.And(ps...), nil
	}
}

// narrow is [ReaderNarrow] with this server's own scope.
func (s ReaderServiceServer) narrow(ctx context.Context, p predicate.Reader) (predicate.Reader, error) {
	return ReaderNarrow(ctx, s.Scope, p)
}

func (s ReaderServiceServer) Add(ctx context.Context, req *api.ReaderAddRequest) (*api.Reader, error) {
	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *api.Reader), 0, 1)
	q := st.Db.Reader.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "shale.Reader", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := TenantGetKey(ctx, st.Db, req.GetTenant()); err != nil {
		return nil, err
	} else {
		q.SetTenantId(k)
		ds = append(ds, func(v *api.Reader) {
			v.SetTenant(api.Tenant_builder{Id: k[:]}.Build())
		})
	}
	q.SetAlias(req.GetAlias())
	q.SetName(req.GetName())
	q.SetDesc(req.GetDesc())
	if u := req.GetLabels(); len(u) > 0 {
		q.SetLabels(u)
	}
	q.SetHardwareId(req.GetHardwareId())
	q.SetHostname(req.GetHostname())
	q.SetState(int32(req.GetState()))
	q.SetCertSerial(req.GetCertSerial())
	if req.HasJoin() {
		q.SetJoin(req.GetJoin())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}
	if req.HasDateAdopted() {
		q.SetDateAdopted(req.GetDateAdopted().AsTime())
	}
	if req.HasDateSeen() {
		q.SetDateSeen(req.GetDateSeen().AsTime())
	}
	if req.HasDateCertExpires() {
		q.SetDateCertExpires(req.GetDateCertExpires().AsTime())
	}
	q.SetVersion(req.GetVersion())
	q.SetAllSites(req.GetAllSites())

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Reader already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Reader: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  api.ReaderService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s ReaderServiceServer) Get(ctx context.Context, req *api.ReaderGetRequest) (*api.Reader, error) {
	p, err := ReaderPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Reader.Query().Where(p)
	ReaderSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Reader not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectReaderKey(q *ent.ReaderQuery) {
	q.Select(reader.FieldId)
}

func ReaderSelectedFields(m *api.ReaderSelect) []string {
	if m.GetAll() {
		return reader.Columns
	}

	vs := make([]string, 0, len(reader.Columns))
	{
		vs = append(vs, reader.FieldId)
	}
	if m.GetAlias() {
		vs = append(vs, reader.FieldAlias)
	}
	if m.GetName() {
		vs = append(vs, reader.FieldName)
	}
	if m.GetDesc() {
		vs = append(vs, reader.FieldDesc)
	}
	if m.GetLabels() {
		vs = append(vs, reader.FieldLabels)
	}
	if m.GetHardwareId() {
		vs = append(vs, reader.FieldHardwareId)
	}
	if m.GetHostname() {
		vs = append(vs, reader.FieldHostname)
	}
	if m.GetState() {
		vs = append(vs, reader.FieldState)
	}
	if m.GetCertSerial() {
		vs = append(vs, reader.FieldCertSerial)
	}
	if m.GetJoin() {
		vs = append(vs, reader.FieldJoin)
	}
	if m.GetDateUpdated() {
		vs = append(vs, reader.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, reader.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, reader.FieldDateCreated)
	}
	if m.GetDateAdopted() {
		vs = append(vs, reader.FieldDateAdopted)
	}
	if m.GetDateSeen() {
		vs = append(vs, reader.FieldDateSeen)
	}
	if m.GetDateCertExpires() {
		vs = append(vs, reader.FieldDateCertExpires)
	}
	if m.GetVersion() {
		vs = append(vs, reader.FieldVersion)
	}
	if m.GetAllSites() {
		vs = append(vs, reader.FieldAllSites)
	}

	return vs
}

func ReaderSelect(q *ent.ReaderQuery, m *api.ReaderSelect) {
	if !m.GetAll() {
		fields := ReaderSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasTenant() {
		q.WithTenant(func(q *ent.TenantQuery) {
			TenantSelect(q, m.GetTenant())
		})
	}
}

func ReaderSelectInit(q *ent.ReaderQuery, m *api.ReaderSelect) {
	if m != nil {
		ReaderSelect(q, m)
	} else {
		q.WithTenant(selectTenantKey)
	}
}

func (s ReaderServiceServer) Patch(ctx context.Context, req *api.ReaderPatchRequest) (*api.Reader, error) {
	doc, err := ormpatch.FromPatchRequest(readerOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, api.ReaderService_Patch_FullMethodName)
}

func ReaderGetKey(ctx context.Context, db *ent.Client, ref *api.ReaderRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := ReaderPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Reader.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Reader not found")
		}
		return z, err
	}

	return v, nil
}

var readerOrmEntity = ormpatch.MustEntityOf(api.File_shale_host_proto, "Reader")

var readerPatchColumns = entpatch.Columns{
	1: reader.FieldId, 2: reader.TenantColumn, 4: reader.FieldAlias, 5: reader.FieldName, 6: reader.FieldDesc, 7: reader.FieldLabels, 8: reader.FieldHardwareId, 9: reader.FieldHostname, 10: reader.FieldState, 11: reader.FieldCertSerial, 12: reader.FieldJoin, 13: reader.FieldDateUpdated, 14: reader.FieldDateErased, 15: reader.FieldDateCreated, 16: reader.FieldDateAdopted, 17: reader.FieldDateSeen, 18: reader.FieldDateCertExpires, 19: reader.FieldVersion, 20: reader.FieldAllSites}

func (s ReaderServiceServer) Apply(ctx context.Context, req *api.ReaderApplyRequest) (*api.Reader, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), api.ReaderService_Apply_FullMethodName)
}

func (s ReaderServiceServer) apply(ctx context.Context, ref *api.ReaderRef, doc *patchpb.Patch, by string) (*api.Reader, error) {
	plan := &ormpatch.Plan{Entity: readerOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(readerOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, readerPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := ReaderGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &api.ReaderRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, reader.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Reader.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Reader(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Reader.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Reader not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Reader.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Reader(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Reader already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Reader: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Reader.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Reader not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s ReaderServiceServer) Erase(ctx context.Context, req *api.ReaderRef) (*api.ReaderEraseResponse, error) {
	p, err := ReaderPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := ent1.JoinTx[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Reader.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &api.ReaderEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = reader.And(p, reader.IdEQ(v))
	}

	u := st.Db.Reader.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  api.ReaderService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &api.ReaderEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// ReaderPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Reader is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasReaderWith`, where no narrowing of a Reader
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func ReaderPick(req *api.ReaderRef) (predicate.Reader, error) {
	p, err := pickReader(req)
	if err != nil {
		return nil, err
	}

	return reader.And(reader.DateErasedIsNil(), p), nil
}

func pickReader(req *api.ReaderRef) (predicate.Reader, error) {
	switch req.WhichKey() {
	case api.ReaderRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return reader.IdEQ(v), nil
		}
	case api.ReaderRef_Slug_case:
		k := req.GetSlug()
		ps := make([]predicate.Reader, 0, 2)
		ps = append(ps, reader.AliasEQ(k.GetAlias()))
		if p, err := TenantPick(k.GetTenant()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "slug.tenant: %s", err)
		} else {
			ps = append(ps, reader.HasTenantWith(p))
		}
		return reader.And(ps...), nil
	case api.ReaderRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Reader")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
