// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: shale/payday/outbox.proto

package bare

import (
	context "context"
	api "github.com/lesomnus/shale/api"
	ent "github.com/lesomnus/shale/internal/ent"
	outbox "github.com/lesomnus/shale/internal/ent/outbox"
	predicate "github.com/lesomnus/shale/internal/ent/predicate"
)

type OutboxServiceServer struct {
	Store

	api.UnimplementedOutboxServiceServer
}

// NewOutboxServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewOutboxServiceServer(db *ent.Client, opts ...Option) api.OutboxServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return OutboxServiceServer{Store: s.Store}
}

// OutboxNarrow answers with `p` and everything else that narrows a
// read of a Outbox, which is whatever `scope` says.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func OutboxNarrow(ctx context.Context, scope Scope, p predicate.Outbox) (predicate.Outbox, error) {
	ps := make([]predicate.Outbox, 0, 2)
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.OutboxScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return outbox.And(ps...), nil
	}
}

// narrow is [OutboxNarrow] with this server's own scope.
func (s OutboxServiceServer) narrow(ctx context.Context, p predicate.Outbox) (predicate.Outbox, error) {
	return OutboxNarrow(ctx, s.Scope, p)
}
