// Code generated by ent, DO NOT EDIT.

package sink

import (
	"github.com/lesomnus/shale/api"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

const (
	// Label holds the string label denoting the sink type in the database.
	Label = "sink"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldCapacity holds the string denoting the capacity field in the database.
	FieldCapacity = "capacity"
	// FieldFree holds the string denoting the free field in the database.
	FieldFree = "free"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldPressure holds the string denoting the pressure field in the database.
	FieldPressure = "pressure"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldAttachment holds the string denoting the attachment field in the database.
	FieldAttachment = "attachment"
	// FieldAcceptWrites holds the string denoting the accept_writes field in the database.
	FieldAcceptWrites = "accept_writes"
	// FieldDateSeen holds the string denoting the date_seen field in the database.
	FieldDateSeen = "date_seen"
	// FieldUploadsInFlight holds the string denoting the uploads_in_flight field in the database.
	FieldUploadsInFlight = "uploads_in_flight"
	// FieldDateReconciled holds the string denoting the date_reconciled field in the database.
	FieldDateReconciled = "date_reconciled"
	// FieldReportedBy holds the string denoting the reported_by field in the database.
	FieldReportedBy = "reported_by"
	// FieldWarnings holds the string denoting the warnings field in the database.
	FieldWarnings = "warnings"
	// FieldCapacityClamped holds the string denoting the capacity_clamped field in the database.
	FieldCapacityClamped = "capacity_clamped"
	// FieldObjects holds the string denoting the objects field in the database.
	FieldObjects = "objects"
	// FieldNodeId holds the string denoting the node_id field in the database.
	FieldNodeId = "node_id"
	// FieldDeviceId holds the string denoting the device_id field in the database.
	FieldDeviceId = "device_id"
	// EdgeNode holds the string denoting the node edge name in mutations.
	EdgeNode = "node"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the sink in the database.
	Table = "sink"
	// NodeTable is the table that holds the node relation/edge.
	NodeTable = "sink"
	// NodeInverseTable is the table name for the Node entity.
	// It exists in this package in order to avoid circular dependency with the "node" package.
	NodeInverseTable = "node"
	// NodeColumn is the table column denoting the node relation/edge.
	NodeColumn = "node_id"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "sink"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "device"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
)

// Columns holds all SQL columns for sink fields.
var Columns = []string{
	FieldId,
	FieldAlias,
	FieldName,
	FieldDesc,
	FieldLabels,
	FieldPath,
	FieldCapacity,
	FieldFree,
	FieldDateUpdated,
	FieldDateErased,
	FieldDateCreated,
	FieldPressure,
	FieldCapabilities,
	FieldAttachment,
	FieldAcceptWrites,
	FieldDateSeen,
	FieldUploadsInFlight,
	FieldDateReconciled,
	FieldReportedBy,
	FieldWarnings,
	FieldCapacityClamped,
	FieldObjects,
	FieldNodeId,
	FieldDeviceId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ValueScanner of all Sink fields.
	ValueScanner struct {
		Capabilities field.TypeValueScanner[*api.SinkCapabilities]
	}
)

// OrderOption defines the ordering options for the Sink queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDesc orders the results by the desc field.
func ByDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDesc, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByCapacity orders the results by the capacity field.
func ByCapacity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacity, opts...).ToFunc()
}

// ByFree orders the results by the free field.
func ByFree(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFree, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByPressure orders the results by the pressure field.
func ByPressure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPressure, opts...).ToFunc()
}

// ByAttachment orders the results by the attachment field.
func ByAttachment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttachment, opts...).ToFunc()
}

// ByAcceptWrites orders the results by the accept_writes field.
func ByAcceptWrites(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcceptWrites, opts...).ToFunc()
}

// ByDateSeen orders the results by the date_seen field.
func ByDateSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateSeen, opts...).ToFunc()
}

// ByUploadsInFlight orders the results by the uploads_in_flight field.
func ByUploadsInFlight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadsInFlight, opts...).ToFunc()
}

// ByDateReconciled orders the results by the date_reconciled field.
func ByDateReconciled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateReconciled, opts...).ToFunc()
}

// ByReportedBy orders the results by the reported_by field.
func ByReportedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedBy, opts...).ToFunc()
}

// ByCapacityClamped orders the results by the capacity_clamped field.
func ByCapacityClamped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapacityClamped, opts...).ToFunc()
}

// ByObjects orders the results by the objects field.
func ByObjects(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjects, opts...).ToFunc()
}

// ByNodeId orders the results by the node_id field.
func ByNodeId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeId, opts...).ToFunc()
}

// ByDeviceId orders the results by the device_id field.
func ByDeviceId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceId, opts...).ToFunc()
}

// ByNodeField orders the results by node field.
func ByNodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newNodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(NodeInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, NodeTable, NodeColumn),
	)
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(DeviceInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, DeviceTable, DeviceColumn),
	)
}
