// Code generated by ent, DO NOT EDIT.

package sitemember

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sitemember type in the database.
	Label = "site_member"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldTenantId holds the string denoting the tenant_id field in the database.
	FieldTenantId = "tenant_id"
	// FieldSiteId holds the string denoting the site_id field in the database.
	FieldSiteId = "site_id"
	// FieldHolderId holds the string denoting the holder_id field in the database.
	FieldHolderId = "holder_id"
	// FieldReaderId holds the string denoting the reader_id field in the database.
	FieldReaderId = "reader_id"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// EdgeHolder holds the string denoting the holder edge name in mutations.
	EdgeHolder = "holder"
	// EdgeReader holds the string denoting the reader edge name in mutations.
	EdgeReader = "reader"
	// Table holds the table name of the sitemember in the database.
	Table = "sitemember"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "sitemember"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenant"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "sitemember"
	// SiteInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	SiteInverseTable = "site"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
	// HolderTable is the table that holds the holder relation/edge.
	HolderTable = "sitemember"
	// HolderInverseTable is the table name for the Holder entity.
	// It exists in this package in order to avoid circular dependency with the "holder" package.
	HolderInverseTable = "holder"
	// HolderColumn is the table column denoting the holder relation/edge.
	HolderColumn = "holder_id"
	// ReaderTable is the table that holds the reader relation/edge.
	ReaderTable = "sitemember"
	// ReaderInverseTable is the table name for the Reader entity.
	// It exists in this package in order to avoid circular dependency with the "reader" package.
	ReaderInverseTable = "reader"
	// ReaderColumn is the table column denoting the reader relation/edge.
	ReaderColumn = "reader_id"
)

// Columns holds all SQL columns for sitemember fields.
var Columns = []string{
	FieldId,
	FieldDateUpdated,
	FieldDateCreated,
	FieldTenantId,
	FieldSiteId,
	FieldHolderId,
	FieldReaderId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SiteMember queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByTenantId orders the results by the tenant_id field.
func ByTenantId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantId, opts...).ToFunc()
}

// BySiteId orders the results by the site_id field.
func BySiteId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteId, opts...).ToFunc()
}

// ByHolderId orders the results by the holder_id field.
func ByHolderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHolderId, opts...).ToFunc()
}

// ByReaderId orders the results by the reader_id field.
func ByReaderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReaderId, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}

// ByHolderField orders the results by holder field.
func ByHolderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHolderStep(), sql.OrderByField(field, opts...))
	}
}

// ByReaderField orders the results by reader field.
func ByReaderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReaderStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(TenantInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
	)
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(SiteInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, SiteTable, SiteColumn),
	)
}
func newHolderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(HolderInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
	)
}
func newReaderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(ReaderInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, ReaderTable, ReaderColumn),
	)
}
