// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shale/payday/holder_svc.g.proto

package api

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HolderAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_IdpSubject  *string                `protobuf:"bytes,8,opt,name=idp_subject,json=idpSubject"`
	xxx_hidden_Password    []byte                 `protobuf:"bytes,9,opt,name=password"`
	xxx_hidden_AllSites    bool                   `protobuf:"varint,10,opt,name=all_sites,json=allSites"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderAddRequest) Reset() {
	*x = HolderAddRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderAddRequest) ProtoMessage() {}

func (x *HolderAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *HolderAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *HolderAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *HolderAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *HolderAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *HolderAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *HolderAddRequest) GetIdpSubject() string {
	if x != nil {
		if x.xxx_hidden_IdpSubject != nil {
			return *x.xxx_hidden_IdpSubject
		}
		return ""
	}
	return ""
}

func (x *HolderAddRequest) GetPassword() []byte {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *HolderAddRequest) GetAllSites() bool {
	if x != nil {
		return x.xxx_hidden_AllSites
	}
	return false
}

func (x *HolderAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *HolderAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *HolderAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *HolderAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *HolderAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *HolderAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *HolderAddRequest) SetIdpSubject(v string) {
	x.xxx_hidden_IdpSubject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *HolderAddRequest) SetPassword(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Password = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *HolderAddRequest) SetAllSites(v bool) {
	x.xxx_hidden_AllSites = v
}

func (x *HolderAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *HolderAddRequest) HasIdpSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HolderAddRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *HolderAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *HolderAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *HolderAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *HolderAddRequest) ClearIdpSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_IdpSubject = nil
}

func (x *HolderAddRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Password = nil
}

type HolderAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
	IdpSubject  *string
	Password    []byte
	AllSites    bool
}

func (b0 HolderAddRequest_builder) Build() *HolderAddRequest {
	m0 := &HolderAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	if b.IdpSubject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_IdpSubject = b.IdpSubject
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_Password = b.Password
	}
	x.xxx_hidden_AllSites = b.AllSites
	return m0
}

type HolderGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *HolderSelect          `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HolderGetRequest) Reset() {
	*x = HolderGetRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderGetRequest) ProtoMessage() {}

func (x *HolderGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderGetRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderGetRequest) GetSelect() *HolderSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *HolderGetRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderGetRequest) SetSelect(v *HolderSelect) {
	x.xxx_hidden_Select = v
}

func (x *HolderGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *HolderGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type HolderGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *HolderRef
	Select *HolderSelect
}

func (b0 HolderGetRequest_builder) Build() *HolderGetRequest {
	m0 := &HolderGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type HolderRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isHolderRef_Key        `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HolderRef) Reset() {
	*x = HolderRef{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRef) ProtoMessage() {}

func (x *HolderRef) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*holderRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *HolderRef) GetSlug() *HolderRefBySlug {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*holderRef_Slug); ok {
			return x.Slug
		}
	}
	return nil
}

func (x *HolderRef) GetIdpSubject() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*holderRef_IdpSubject); ok {
			return x.IdpSubject
		}
	}
	return ""
}

func (x *HolderRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &holderRef_Id{v}
}

func (x *HolderRef) SetSlug(v *HolderRefBySlug) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &holderRef_Slug{v}
}

func (x *HolderRef) SetIdpSubject(v string) {
	x.xxx_hidden_Key = &holderRef_IdpSubject{v}
}

func (x *HolderRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *HolderRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*holderRef_Id)
	return ok
}

func (x *HolderRef) HasSlug() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*holderRef_Slug)
	return ok
}

func (x *HolderRef) HasIdpSubject() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*holderRef_IdpSubject)
	return ok
}

func (x *HolderRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *HolderRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*holderRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *HolderRef) ClearSlug() {
	if _, ok := x.xxx_hidden_Key.(*holderRef_Slug); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *HolderRef) ClearIdpSubject() {
	if _, ok := x.xxx_hidden_Key.(*holderRef_IdpSubject); ok {
		x.xxx_hidden_Key = nil
	}
}

const HolderRef_Key_not_set_case case_HolderRef_Key = 0
const HolderRef_Id_case case_HolderRef_Key = 1
const HolderRef_Slug_case case_HolderRef_Key = 4
const HolderRef_IdpSubject_case case_HolderRef_Key = 8

func (x *HolderRef) WhichKey() case_HolderRef_Key {
	if x == nil {
		return HolderRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *holderRef_Id:
		return HolderRef_Id_case
	case *holderRef_Slug:
		return HolderRef_Slug_case
	case *holderRef_IdpSubject:
		return HolderRef_IdpSubject_case
	default:
		return HolderRef_Key_not_set_case
	}
}

type HolderRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id         []byte
	Slug       *HolderRefBySlug
	IdpSubject *string
	// -- end of xxx_hidden_Key
}

func (b0 HolderRef_builder) Build() *HolderRef {
	m0 := &HolderRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &holderRef_Id{b.Id}
	}
	if b.Slug != nil {
		x.xxx_hidden_Key = &holderRef_Slug{b.Slug}
	}
	if b.IdpSubject != nil {
		x.xxx_hidden_Key = &holderRef_IdpSubject{*b.IdpSubject}
	}
	return m0
}

type case_HolderRef_Key protoreflect.FieldNumber

func (x case_HolderRef_Key) String() string {
	md := file_shale_payday_holder_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isHolderRef_Key interface {
	isHolderRef_Key()
}

type holderRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type holderRef_Slug struct {
	Slug *HolderRefBySlug `protobuf:"bytes,4,opt,name=slug,oneof"`
}

type holderRef_IdpSubject struct {
	IdpSubject string `protobuf:"bytes,8,opt,name=idp_subject,json=idpSubject,oneof"`
}

func (*holderRef_Id) isHolderRef_Key() {}

func (*holderRef_Slug) isHolderRef_Key() {}

func (*holderRef_IdpSubject) isHolderRef_Key() {}

type HolderRefBySlug struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderRefBySlug) Reset() {
	*x = HolderRefBySlug{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRefBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRefBySlug) ProtoMessage() {}

func (x *HolderRefBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderRefBySlug) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *HolderRefBySlug) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderRefBySlug) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *HolderRefBySlug) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderRefBySlug) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderRefBySlug) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderRefBySlug) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *HolderRefBySlug) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type HolderRefBySlug_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 HolderRefBySlug_builder) Build() *HolderRefBySlug {
	m0 := &HolderRefBySlug{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type HolderSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_DateUpdated bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  bool                   `protobuf:"varint,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_IdpSubject  bool                   `protobuf:"varint,8,opt,name=idp_subject,json=idpSubject"`
	xxx_hidden_Password    bool                   `protobuf:"varint,9,opt,name=password"`
	xxx_hidden_AllSites    bool                   `protobuf:"varint,10,opt,name=all_sites,json=allSites"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderSelect) Reset() {
	*x = HolderSelect{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderSelect) ProtoMessage() {}

func (x *HolderSelect) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *HolderSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *HolderSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *HolderSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *HolderSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *HolderSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *HolderSelect) GetDateErased() bool {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return false
}

func (x *HolderSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *HolderSelect) GetIdpSubject() bool {
	if x != nil {
		return x.xxx_hidden_IdpSubject
	}
	return false
}

func (x *HolderSelect) GetPassword() bool {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return false
}

func (x *HolderSelect) GetAllSites() bool {
	if x != nil {
		return x.xxx_hidden_AllSites
	}
	return false
}

func (x *HolderSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *HolderSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *HolderSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *HolderSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *HolderSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *HolderSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *HolderSelect) SetDateErased(v bool) {
	x.xxx_hidden_DateErased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *HolderSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *HolderSelect) SetIdpSubject(v bool) {
	x.xxx_hidden_IdpSubject = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *HolderSelect) SetPassword(v bool) {
	x.xxx_hidden_Password = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *HolderSelect) SetAllSites(v bool) {
	x.xxx_hidden_AllSites = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *HolderSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HolderSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HolderSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *HolderSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *HolderSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *HolderSelect) HasDateErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HolderSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *HolderSelect) HasIdpSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *HolderSelect) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *HolderSelect) HasAllSites() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *HolderSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *HolderSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *HolderSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *HolderSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *HolderSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Desc = false
}

func (x *HolderSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Labels = false
}

func (x *HolderSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateUpdated = false
}

func (x *HolderSelect) ClearDateErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_DateErased = false
}

func (x *HolderSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_DateCreated = false
}

func (x *HolderSelect) ClearIdpSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_IdpSubject = false
}

func (x *HolderSelect) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_Password = false
}

func (x *HolderSelect) ClearAllSites() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_AllSites = false
}

type HolderSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateUpdated *bool
	DateErased  *bool
	DateCreated *bool
	IdpSubject  *bool
	Password    *bool
	AllSites    *bool
}

func (b0 HolderSelect_builder) Build() *HolderSelect {
	m0 := &HolderSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateErased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_DateErased = *b.DateErased
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	if b.IdpSubject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_IdpSubject = *b.IdpSubject
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_Password = *b.Password
	}
	if b.AllSites != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_AllSites = *b.AllSites
	}
	return m0
}

type HolderPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias            *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name             *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Desc             *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	xxx_hidden_IdpSubject       *string                `protobuf:"bytes,16,opt,name=idp_subject,json=idpSubject"`
	xxx_hidden_IdpSubjectNull   bool                   `protobuf:"varint,17,opt,name=idp_subject_null,json=idpSubjectNull"`
	xxx_hidden_Password         []byte                 `protobuf:"bytes,18,opt,name=password"`
	xxx_hidden_AllSites         bool                   `protobuf:"varint,20,opt,name=all_sites,json=allSites"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *HolderPatchRequest) Reset() {
	*x = HolderPatchRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderPatchRequest) ProtoMessage() {}

func (x *HolderPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderPatchRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *HolderPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *HolderPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *HolderPatchRequest) GetIdpSubject() string {
	if x != nil {
		if x.xxx_hidden_IdpSubject != nil {
			return *x.xxx_hidden_IdpSubject
		}
		return ""
	}
	return ""
}

func (x *HolderPatchRequest) GetIdpSubjectNull() bool {
	if x != nil {
		return x.xxx_hidden_IdpSubjectNull
	}
	return false
}

func (x *HolderPatchRequest) GetPassword() []byte {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *HolderPatchRequest) GetAllSites() bool {
	if x != nil {
		return x.xxx_hidden_AllSites
	}
	return false
}

func (x *HolderPatchRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *HolderPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *HolderPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *HolderPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *HolderPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *HolderPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
}

func (x *HolderPatchRequest) SetIdpSubject(v string) {
	x.xxx_hidden_IdpSubject = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 11)
}

func (x *HolderPatchRequest) SetIdpSubjectNull(v bool) {
	x.xxx_hidden_IdpSubjectNull = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *HolderPatchRequest) SetPassword(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Password = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
}

func (x *HolderPatchRequest) SetAllSites(v bool) {
	x.xxx_hidden_AllSites = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *HolderPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HolderPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HolderPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HolderPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *HolderPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *HolderPatchRequest) HasIdpSubject() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HolderPatchRequest) HasIdpSubjectNull() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *HolderPatchRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *HolderPatchRequest) HasAllSites() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *HolderPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *HolderPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *HolderPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

func (x *HolderPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *HolderPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateUpdatedForce = false
}

func (x *HolderPatchRequest) ClearIdpSubject() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_IdpSubject = nil
}

func (x *HolderPatchRequest) ClearIdpSubjectNull() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_IdpSubjectNull = false
}

func (x *HolderPatchRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Password = nil
}

func (x *HolderPatchRequest) ClearAllSites() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_AllSites = false
}

type HolderPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *HolderRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
	IdpSubject       *string
	// Clear idp_subject instead of writing it.
	// It takes a field of its own because an unset value already means
	// "leave it alone", so no value could have meant NULL. It wins
	// outright: setting both this and idp_subject clears.
	IdpSubjectNull *bool
	Password       []byte
	AllSites       *bool
}

func (b0 HolderPatchRequest_builder) Build() *HolderPatchRequest {
	m0 := &HolderPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	if b.IdpSubject != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 11)
		x.xxx_hidden_IdpSubject = b.IdpSubject
	}
	if b.IdpSubjectNull != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_IdpSubjectNull = *b.IdpSubjectNull
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_Password = b.Password
	}
	if b.AllSites != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_AllSites = *b.AllSites
	}
	return m0
}

type HolderApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HolderApplyRequest) Reset() {
	*x = HolderApplyRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderApplyRequest) ProtoMessage() {}

func (x *HolderApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderApplyRequest) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *HolderApplyRequest) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *HolderApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *HolderApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type HolderApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *HolderRef
	Patch *patchpb.Patch
}

func (b0 HolderApplyRequest_builder) Build() *HolderApplyRequest {
	m0 := &HolderApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type HolderEraseResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Erased      bool                   `protobuf:"varint,1,opt,name=erased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderEraseResponse) Reset() {
	*x = HolderEraseResponse{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderEraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderEraseResponse) ProtoMessage() {}

func (x *HolderEraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderEraseResponse) GetErased() bool {
	if x != nil {
		return x.xxx_hidden_Erased
	}
	return false
}

func (x *HolderEraseResponse) SetErased(v bool) {
	x.xxx_hidden_Erased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *HolderEraseResponse) HasErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderEraseResponse) ClearErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Erased = false
}

type HolderEraseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Erased is whether this call is the one that erased the row.
	//
	// False for a row that was already gone, was never there, or is out
	// of this caller's reach -- which are one answer on purpose, and the
	// reason the RPC does not fail instead.
	Erased *bool
}

func (b0 HolderEraseResponse_builder) Build() *HolderEraseResponse {
	m0 := &HolderEraseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Erased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Erased = *b.Erased
	}
	return m0
}

type HolderListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*HolderFilter       `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                 `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HolderListRequest) Reset() {
	*x = HolderListRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderListRequest) ProtoMessage() {}

func (x *HolderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderListRequest) GetFilters() []*HolderFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *HolderListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *HolderListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *HolderListRequest) SetFilters(v []*HolderFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *HolderListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *HolderListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type HolderListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*HolderFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 HolderListRequest_builder) Build() *HolderListRequest {
	m0 := &HolderListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type HolderListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Holder             `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HolderListResponse) Reset() {
	*x = HolderListResponse{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderListResponse) ProtoMessage() {}

func (x *HolderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderListResponse) GetItems() []*Holder {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *HolderListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *HolderListResponse) SetItems(v []*Holder) {
	x.xxx_hidden_Items = &v
}

func (x *HolderListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type HolderListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Holder
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 HolderListResponse_builder) Build() *HolderListResponse {
	m0 := &HolderListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type HolderFilter struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *HolderRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Tenant *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Labels map[string]string      `protobuf:"bytes,3,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HolderFilter) Reset() {
	*x = HolderFilter{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderFilter) ProtoMessage() {}

func (x *HolderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderFilter) GetRef() *HolderRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *HolderFilter) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *HolderFilter) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *HolderFilter) SetRef(v *HolderRef) {
	x.xxx_hidden_Ref = v
}

func (x *HolderFilter) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *HolderFilter) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *HolderFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *HolderFilter) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *HolderFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *HolderFilter) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type HolderFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *HolderRef
	Tenant *TenantRef
	Labels map[string]string
}

func (b0 HolderFilter_builder) Build() *HolderFilter {
	m0 := &HolderFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type HolderWatchRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters      *[]*HolderFilter       `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_SkipSnapshot bool                   `protobuf:"varint,2,opt,name=skip_snapshot,json=skipSnapshot"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HolderWatchRequest) Reset() {
	*x = HolderWatchRequest{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderWatchRequest) ProtoMessage() {}

func (x *HolderWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderWatchRequest) GetFilters() []*HolderFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *HolderWatchRequest) GetSkipSnapshot() bool {
	if x != nil {
		return x.xxx_hidden_SkipSnapshot
	}
	return false
}

func (x *HolderWatchRequest) SetFilters(v []*HolderFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *HolderWatchRequest) SetSkipSnapshot(v bool) {
	x.xxx_hidden_SkipSnapshot = v
}

type HolderWatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which rows to watch, in the same words List takes them: what is watched is
	// what that list would answer with, now and afterwards.
	//
	// Required, and bounded the way a List is -- for a heavier reason. A list
	// runs its filters once; a watch runs them again for every write that touches
	// the entity, for as long as the stream is open. A watch with no filters is
	// the whole table, forever, which is the one shape that has no cap at all.
	Filters []*HolderFilter
	// Skip what is there now and send only what changes from here.
	//
	// Off by default, and the default is the safe one: a client that does not
	// know the current state and did not ask for it holds something wrong until
	// the next write happens to correct it.
	SkipSnapshot bool
}

func (b0 HolderWatchRequest_builder) Build() *HolderWatchRequest {
	m0 := &HolderWatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_SkipSnapshot = b.SkipSnapshot
	return m0
}

type HolderWatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*HolderWatchItem    `protobuf:"bytes,1,rep,name=items"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HolderWatchResponse) Reset() {
	*x = HolderWatchResponse{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderWatchResponse) ProtoMessage() {}

func (x *HolderWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderWatchResponse) GetItems() []*HolderWatchItem {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *HolderWatchResponse) SetItems(v []*HolderWatchItem) {
	x.xxx_hidden_Items = &v
}

type HolderWatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// What changed, or -- in the first message -- everything that matches.
	Items []*HolderWatchItem
}

func (b0 HolderWatchResponse_builder) Build() *HolderWatchResponse {
	m0 := &HolderWatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	return m0
}

type HolderWatchItem struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       *Holder                `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Action      string                 `protobuf:"bytes,3,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HolderWatchItem) Reset() {
	*x = HolderWatchItem{}
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderWatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderWatchItem) ProtoMessage() {}

func (x *HolderWatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_holder_svc_g_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HolderWatchItem) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *HolderWatchItem) GetValue() *Holder {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *HolderWatchItem) GetAction() string {
	if x != nil {
		return x.xxx_hidden_Action
	}
	return ""
}

func (x *HolderWatchItem) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *HolderWatchItem) SetValue(v *Holder) {
	x.xxx_hidden_Value = v
}

func (x *HolderWatchItem) SetAction(v string) {
	x.xxx_hidden_Action = v
}

func (x *HolderWatchItem) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HolderWatchItem) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *HolderWatchItem) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *HolderWatchItem) ClearValue() {
	x.xxx_hidden_Value = nil
}

type HolderWatchItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Which row. Always said, since one that is gone still has to be named.
	Id []byte
	// The row as it is now, and **absent when it is no longer one this caller may
	// see**: erased, or moved out of the filters this stream named.
	//
	// Absence is the whole of how a removal is said. There is no flag for it, and
	// there is deliberately no way to tell those two apart -- a stream that
	// distinguished "erased" from "no longer yours" would be telling a caller
	// about rows that stopped being theirs, which is the thing the wall is for.
	//
	// It is only ever said about a row this stream has already carried. One that
	// never matched is not news.
	Value *Holder
	// The RPC that changed it, by the name gRPC knows it by. It is what the
	// caller of *that* RPC asked for and not the write it became, so an RPC
	// written by hand is here under its own name.
	//
	// Empty in the first message, which is not something anybody asked for -- it
	// is what is already there.
	Action string
}

func (b0 HolderWatchItem_builder) Build() *HolderWatchItem {
	m0 := &HolderWatchItem{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Action = b.Action
	return m0
}

var File_shale_payday_holder_svc_g_proto protoreflect.FileDescriptor

const file_shale_payday_holder_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1fshale/payday/holder_svc.g.proto\x12\x05shale\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\x1a\x19shale/payday/holder.proto\x1a\x1fshale/payday/tenant_svc.g.proto\"\xb7\x03\n" +
	"\x10HolderAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x06tenant\x18\x02 \x01(\v2\x10.shale.TenantRefR\x06tenant\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.shale.HolderAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12\x1f\n" +
	"\vidp_subject\x18\b \x01(\tR\n" +
	"idpSubject\x12\x1a\n" +
	"\bpassword\x18\t \x01(\fR\bpassword\x12\"\n" +
	"\tall_sites\x18\n" +
	" \x01(\bB\x05\xaa\x01\x02\b\x02R\ballSites\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10HolderGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.HolderRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.shale.HolderSelectR\x06select\"u\n" +
	"\tHolderRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12,\n" +
	"\x04slug\x18\x04 \x01(\v2\x16.shale.HolderRefBySlugH\x00R\x04slug\x12!\n" +
	"\vidp_subject\x18\b \x01(\tH\x00R\n" +
	"idpSubjectB\x05\n" +
	"\x03key\"Q\n" +
	"\x0fHolderRefBySlug\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12(\n" +
	"\x06tenant\x18\x02 \x01(\v2\x10.shale.TenantRefR\x06tenant\"\xe4\x02\n" +
	"\fHolderSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12+\n" +
	"\x06tenant\x18\x02 \x01(\v2\x13.shale.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12\x1f\n" +
	"\vdate_erased\x18\x0e \x01(\bR\n" +
	"dateErased\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\x12\x1f\n" +
	"\vidp_subject\x18\b \x01(\bR\n" +
	"idpSubject\x12\x1a\n" +
	"\bpassword\x18\t \x01(\bR\bpassword\x12\x1b\n" +
	"\tall_sites\x18\n" +
	" \x01(\bR\ballSites\"\xe1\x03\n" +
	"\x12HolderPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.HolderRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12=\n" +
	"\x06labels\x18\x0e \x03(\v2%.shale.HolderPatchRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\x12\x1f\n" +
	"\vidp_subject\x18\x10 \x01(\tR\n" +
	"idpSubject\x12(\n" +
	"\x10idp_subject_null\x18\x11 \x01(\bR\x0eidpSubjectNull\x12\x1a\n" +
	"\bpassword\x18\x12 \x01(\fR\bpassword\x12\x1b\n" +
	"\tall_sites\x18\x14 \x01(\bR\ballSites\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x12HolderApplyRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.HolderRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"-\n" +
	"\x13HolderEraseResponse\x12\x16\n" +
	"\x06erased\x18\x01 \x01(\bR\x06erased\"z\n" +
	"\x11HolderListRequest\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.shale.HolderFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"T\n" +
	"\x12HolderListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.shale.HolderR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"\xd0\x01\n" +
	"\fHolderFilter\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.HolderRefR\x03ref\x12(\n" +
	"\x06tenant\x18\x02 \x01(\v2\x10.shale.TenantRefR\x06tenant\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.shale.HolderFilter.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x12HolderWatchRequest\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.shale.HolderFilterR\afilters\x12*\n" +
	"\rskip_snapshot\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x02R\fskipSnapshot\"C\n" +
	"\x13HolderWatchResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.shale.HolderWatchItemR\x05items\"e\n" +
	"\x0fHolderWatchItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.shale.HolderR\x05value\x12\x1d\n" +
	"\x06action\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x06action2\x89\x03\n" +
	"\rHolderService\x12-\n" +
	"\x03Add\x12\x17.shale.HolderAddRequest\x1a\r.shale.Holder\x12-\n" +
	"\x03Get\x12\x17.shale.HolderGetRequest\x1a\r.shale.Holder\x121\n" +
	"\x05Patch\x12\x19.shale.HolderPatchRequest\x1a\r.shale.Holder\x121\n" +
	"\x05Apply\x12\x19.shale.HolderApplyRequest\x1a\r.shale.Holder\x125\n" +
	"\x05Erase\x12\x10.shale.HolderRef\x1a\x1a.shale.HolderEraseResponse\x12;\n" +
	"\x04List\x12\x18.shale.HolderListRequest\x1a\x19.shale.HolderListResponse\x12@\n" +
	"\x05Watch\x12\x19.shale.HolderWatchRequest\x1a\x1a.shale.HolderWatchResponse0\x01B\x1fZ\x1dgithub.com/lesomnus/shale/apib\beditionsp\xe8\a"

var file_shale_payday_holder_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_shale_payday_holder_svc_g_proto_goTypes = []any{
	(*HolderAddRequest)(nil),      // 0: shale.HolderAddRequest
	(*HolderGetRequest)(nil),      // 1: shale.HolderGetRequest
	(*HolderRef)(nil),             // 2: shale.HolderRef
	(*HolderRefBySlug)(nil),       // 3: shale.HolderRefBySlug
	(*HolderSelect)(nil),          // 4: shale.HolderSelect
	(*HolderPatchRequest)(nil),    // 5: shale.HolderPatchRequest
	(*HolderApplyRequest)(nil),    // 6: shale.HolderApplyRequest
	(*HolderEraseResponse)(nil),   // 7: shale.HolderEraseResponse
	(*HolderListRequest)(nil),     // 8: shale.HolderListRequest
	(*HolderListResponse)(nil),    // 9: shale.HolderListResponse
	(*HolderFilter)(nil),          // 10: shale.HolderFilter
	(*HolderWatchRequest)(nil),    // 11: shale.HolderWatchRequest
	(*HolderWatchResponse)(nil),   // 12: shale.HolderWatchResponse
	(*HolderWatchItem)(nil),       // 13: shale.HolderWatchItem
	nil,                           // 14: shale.HolderAddRequest.LabelsEntry
	nil,                           // 15: shale.HolderPatchRequest.LabelsEntry
	nil,                           // 16: shale.HolderFilter.LabelsEntry
	(*TenantRef)(nil),             // 17: shale.TenantRef
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 19: shale.TenantSelect
	(*patchpb.Patch)(nil),         // 20: patch.Patch
	(*Holder)(nil),                // 21: shale.Holder
}
var file_shale_payday_holder_svc_g_proto_depIdxs = []int32{
	17, // 0: shale.HolderAddRequest.tenant:type_name -> shale.TenantRef
	14, // 1: shale.HolderAddRequest.labels:type_name -> shale.HolderAddRequest.LabelsEntry
	18, // 2: shale.HolderAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 3: shale.HolderGetRequest.ref:type_name -> shale.HolderRef
	4,  // 4: shale.HolderGetRequest.select:type_name -> shale.HolderSelect
	3,  // 5: shale.HolderRef.slug:type_name -> shale.HolderRefBySlug
	17, // 6: shale.HolderRefBySlug.tenant:type_name -> shale.TenantRef
	19, // 7: shale.HolderSelect.tenant:type_name -> shale.TenantSelect
	2,  // 8: shale.HolderPatchRequest.ref:type_name -> shale.HolderRef
	15, // 9: shale.HolderPatchRequest.labels:type_name -> shale.HolderPatchRequest.LabelsEntry
	18, // 10: shale.HolderPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	2,  // 11: shale.HolderApplyRequest.ref:type_name -> shale.HolderRef
	20, // 12: shale.HolderApplyRequest.patch:type_name -> patch.Patch
	10, // 13: shale.HolderListRequest.filters:type_name -> shale.HolderFilter
	21, // 14: shale.HolderListResponse.items:type_name -> shale.Holder
	2,  // 15: shale.HolderFilter.ref:type_name -> shale.HolderRef
	17, // 16: shale.HolderFilter.tenant:type_name -> shale.TenantRef
	16, // 17: shale.HolderFilter.labels:type_name -> shale.HolderFilter.LabelsEntry
	10, // 18: shale.HolderWatchRequest.filters:type_name -> shale.HolderFilter
	13, // 19: shale.HolderWatchResponse.items:type_name -> shale.HolderWatchItem
	21, // 20: shale.HolderWatchItem.value:type_name -> shale.Holder
	0,  // 21: shale.HolderService.Add:input_type -> shale.HolderAddRequest
	1,  // 22: shale.HolderService.Get:input_type -> shale.HolderGetRequest
	5,  // 23: shale.HolderService.Patch:input_type -> shale.HolderPatchRequest
	6,  // 24: shale.HolderService.Apply:input_type -> shale.HolderApplyRequest
	2,  // 25: shale.HolderService.Erase:input_type -> shale.HolderRef
	8,  // 26: shale.HolderService.List:input_type -> shale.HolderListRequest
	11, // 27: shale.HolderService.Watch:input_type -> shale.HolderWatchRequest
	21, // 28: shale.HolderService.Add:output_type -> shale.Holder
	21, // 29: shale.HolderService.Get:output_type -> shale.Holder
	21, // 30: shale.HolderService.Patch:output_type -> shale.Holder
	21, // 31: shale.HolderService.Apply:output_type -> shale.Holder
	7,  // 32: shale.HolderService.Erase:output_type -> shale.HolderEraseResponse
	9,  // 33: shale.HolderService.List:output_type -> shale.HolderListResponse
	12, // 34: shale.HolderService.Watch:output_type -> shale.HolderWatchResponse
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_shale_payday_holder_svc_g_proto_init() }
func file_shale_payday_holder_svc_g_proto_init() {
	if File_shale_payday_holder_svc_g_proto != nil {
		return
	}
	file_shale_payday_holder_proto_init()
	file_shale_payday_tenant_svc_g_proto_init()
	file_shale_payday_holder_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*holderRef_Id)(nil),
		(*holderRef_Slug)(nil),
		(*holderRef_IdpSubject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_payday_holder_svc_g_proto_rawDesc), len(file_shale_payday_holder_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shale_payday_holder_svc_g_proto_goTypes,
		DependencyIndexes: file_shale_payday_holder_svc_g_proto_depIdxs,
		MessageInfos:      file_shale_payday_holder_svc_g_proto_msgTypes,
	}.Build()
	File_shale_payday_holder_svc_g_proto = out.File
	file_shale_payday_holder_svc_g_proto_goTypes = nil
	file_shale_payday_holder_svc_g_proto_depIdxs = nil
}
