// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shale/ingest.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachRequest struct {
	state              protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Message isAttachRequest_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_shale_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachRequest) GetHello() *AttachRequest_Hello {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*attachRequest_Hello_); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AttachRequest) GetData() *AttachRequest_Data {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*attachRequest_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *AttachRequest) SetHello(v *AttachRequest_Hello) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &attachRequest_Hello_{v}
}

func (x *AttachRequest) SetData(v *AttachRequest_Data) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &attachRequest_Data_{v}
}

func (x *AttachRequest) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *AttachRequest) HasHello() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*attachRequest_Hello_)
	return ok
}

func (x *AttachRequest) HasData() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*attachRequest_Data_)
	return ok
}

func (x *AttachRequest) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *AttachRequest) ClearHello() {
	if _, ok := x.xxx_hidden_Message.(*attachRequest_Hello_); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *AttachRequest) ClearData() {
	if _, ok := x.xxx_hidden_Message.(*attachRequest_Data_); ok {
		x.xxx_hidden_Message = nil
	}
}

const AttachRequest_Message_not_set_case case_AttachRequest_Message = 0
const AttachRequest_Hello_case case_AttachRequest_Message = 1
const AttachRequest_Data_case case_AttachRequest_Message = 2

func (x *AttachRequest) WhichMessage() case_AttachRequest_Message {
	if x == nil {
		return AttachRequest_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *attachRequest_Hello_:
		return AttachRequest_Hello_case
	case *attachRequest_Data_:
		return AttachRequest_Data_case
	default:
		return AttachRequest_Message_not_set_case
	}
}

type AttachRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	Hello *AttachRequest_Hello
	Data  *AttachRequest_Data
	// -- end of xxx_hidden_Message
}

func (b0 AttachRequest_builder) Build() *AttachRequest {
	m0 := &AttachRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Hello != nil {
		x.xxx_hidden_Message = &attachRequest_Hello_{b.Hello}
	}
	if b.Data != nil {
		x.xxx_hidden_Message = &attachRequest_Data_{b.Data}
	}
	return m0
}

type case_AttachRequest_Message protoreflect.FieldNumber

func (x case_AttachRequest_Message) String() string {
	md := file_shale_ingest_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAttachRequest_Message interface {
	isAttachRequest_Message()
}

type attachRequest_Hello_ struct {
	Hello *AttachRequest_Hello `protobuf:"bytes,1,opt,name=hello,oneof"`
}

type attachRequest_Data_ struct {
	Data *AttachRequest_Data `protobuf:"bytes,2,opt,name=data,oneof"`
}

func (*attachRequest_Hello_) isAttachRequest_Message() {}

func (*attachRequest_Data_) isAttachRequest_Message() {}

type AttachResponse struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Message isAttachResponse_Message `protobuf_oneof:"message"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_shale_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachResponse) GetStart() *AttachResponse_Start {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*attachResponse_Start_); ok {
			return x.Start
		}
	}
	return nil
}

func (x *AttachResponse) GetStop() *AttachResponse_Stop {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*attachResponse_Stop_); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *AttachResponse) GetWelcome() *AttachResponse_Welcome {
	if x != nil {
		if x, ok := x.xxx_hidden_Message.(*attachResponse_Welcome_); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *AttachResponse) SetStart(v *AttachResponse_Start) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &attachResponse_Start_{v}
}

func (x *AttachResponse) SetStop(v *AttachResponse_Stop) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &attachResponse_Stop_{v}
}

func (x *AttachResponse) SetWelcome(v *AttachResponse_Welcome) {
	if v == nil {
		x.xxx_hidden_Message = nil
		return
	}
	x.xxx_hidden_Message = &attachResponse_Welcome_{v}
}

func (x *AttachResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Message != nil
}

func (x *AttachResponse) HasStart() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*attachResponse_Start_)
	return ok
}

func (x *AttachResponse) HasStop() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*attachResponse_Stop_)
	return ok
}

func (x *AttachResponse) HasWelcome() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Message.(*attachResponse_Welcome_)
	return ok
}

func (x *AttachResponse) ClearMessage() {
	x.xxx_hidden_Message = nil
}

func (x *AttachResponse) ClearStart() {
	if _, ok := x.xxx_hidden_Message.(*attachResponse_Start_); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *AttachResponse) ClearStop() {
	if _, ok := x.xxx_hidden_Message.(*attachResponse_Stop_); ok {
		x.xxx_hidden_Message = nil
	}
}

func (x *AttachResponse) ClearWelcome() {
	if _, ok := x.xxx_hidden_Message.(*attachResponse_Welcome_); ok {
		x.xxx_hidden_Message = nil
	}
}

const AttachResponse_Message_not_set_case case_AttachResponse_Message = 0
const AttachResponse_Start_case case_AttachResponse_Message = 1
const AttachResponse_Stop_case case_AttachResponse_Message = 2
const AttachResponse_Welcome_case case_AttachResponse_Message = 3

func (x *AttachResponse) WhichMessage() case_AttachResponse_Message {
	if x == nil {
		return AttachResponse_Message_not_set_case
	}
	switch x.xxx_hidden_Message.(type) {
	case *attachResponse_Start_:
		return AttachResponse_Start_case
	case *attachResponse_Stop_:
		return AttachResponse_Stop_case
	case *attachResponse_Welcome_:
		return AttachResponse_Welcome_case
	default:
		return AttachResponse_Message_not_set_case
	}
}

type AttachResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Message:
	Start   *AttachResponse_Start
	Stop    *AttachResponse_Stop
	Welcome *AttachResponse_Welcome
	// -- end of xxx_hidden_Message
}

func (b0 AttachResponse_builder) Build() *AttachResponse {
	m0 := &AttachResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Start != nil {
		x.xxx_hidden_Message = &attachResponse_Start_{b.Start}
	}
	if b.Stop != nil {
		x.xxx_hidden_Message = &attachResponse_Stop_{b.Stop}
	}
	if b.Welcome != nil {
		x.xxx_hidden_Message = &attachResponse_Welcome_{b.Welcome}
	}
	return m0
}

type case_AttachResponse_Message protoreflect.FieldNumber

func (x case_AttachResponse_Message) String() string {
	md := file_shale_ingest_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAttachResponse_Message interface {
	isAttachResponse_Message()
}

type attachResponse_Start_ struct {
	Start *AttachResponse_Start `protobuf:"bytes,1,opt,name=start,oneof"`
}

type attachResponse_Stop_ struct {
	Stop *AttachResponse_Stop `protobuf:"bytes,2,opt,name=stop,oneof"`
}

type attachResponse_Welcome_ struct {
	Welcome *AttachResponse_Welcome `protobuf:"bytes,3,opt,name=welcome,oneof"`
}

func (*attachResponse_Start_) isAttachResponse_Message() {}

func (*attachResponse_Stop_) isAttachResponse_Message() {}

func (*attachResponse_Welcome_) isAttachResponse_Message() {}

// Hello once, then Data for every source the relay has started.
type AttachRequest_Hello struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublishToken string                 `protobuf:"bytes,1,opt,name=publish_token,json=publishToken"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AttachRequest_Hello) Reset() {
	*x = AttachRequest_Hello{}
	mi := &file_shale_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest_Hello) ProtoMessage() {}

func (x *AttachRequest_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachRequest_Hello) GetPublishToken() string {
	if x != nil {
		return x.xxx_hidden_PublishToken
	}
	return ""
}

func (x *AttachRequest_Hello) SetPublishToken(v string) {
	x.xxx_hidden_PublishToken = v
}

type AttachRequest_Hello_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublishToken string
}

func (b0 AttachRequest_Hello_builder) Build() *AttachRequest_Hello {
	m0 := &AttachRequest_Hello{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PublishToken = b.PublishToken
	return m0
}

type AttachRequest_Data struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SourceId []byte                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId"`
	xxx_hidden_Payload  []byte                 `protobuf:"bytes,2,opt,name=payload"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttachRequest_Data) Reset() {
	*x = AttachRequest_Data{}
	mi := &file_shale_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest_Data) ProtoMessage() {}

func (x *AttachRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachRequest_Data) GetSourceId() []byte {
	if x != nil {
		return x.xxx_hidden_SourceId
	}
	return nil
}

func (x *AttachRequest_Data) GetPayload() []byte {
	if x != nil {
		return x.xxx_hidden_Payload
	}
	return nil
}

func (x *AttachRequest_Data) SetSourceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SourceId = v
}

func (x *AttachRequest_Data) SetPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Payload = v
}

type AttachRequest_Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SourceId []byte
	// MPEG-TS packets, a whole number of them, the same bytes the producer
	// stores; the first bytes after a Start begin at a keyframe with the
	// tables prepended.
	Payload []byte
}

func (b0 AttachRequest_Data_builder) Build() *AttachRequest_Data {
	m0 := &AttachRequest_Data{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SourceId = b.SourceId
	x.xxx_hidden_Payload = b.Payload
	return m0
}

type AttachResponse_Start struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SourceId []byte                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttachResponse_Start) Reset() {
	*x = AttachResponse_Start{}
	mi := &file_shale_ingest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse_Start) ProtoMessage() {}

func (x *AttachResponse_Start) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachResponse_Start) GetSourceId() []byte {
	if x != nil {
		return x.xxx_hidden_SourceId
	}
	return nil
}

func (x *AttachResponse_Start) SetSourceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SourceId = v
}

type AttachResponse_Start_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SourceId []byte
}

func (b0 AttachResponse_Start_builder) Build() *AttachResponse_Start {
	m0 := &AttachResponse_Start{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SourceId = b.SourceId
	return m0
}

type AttachResponse_Stop struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SourceId []byte                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AttachResponse_Stop) Reset() {
	*x = AttachResponse_Stop{}
	mi := &file_shale_ingest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse_Stop) ProtoMessage() {}

func (x *AttachResponse_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachResponse_Stop) GetSourceId() []byte {
	if x != nil {
		return x.xxx_hidden_SourceId
	}
	return nil
}

func (x *AttachResponse_Stop) SetSourceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SourceId = v
}

type AttachResponse_Stop_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SourceId []byte
}

func (b0 AttachResponse_Stop_builder) Build() *AttachResponse_Stop {
	m0 := &AttachResponse_Stop{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SourceId = b.SourceId
	return m0
}

// Answered to Hello: which of the token's sources the relay accepted.
type AttachResponse_Welcome struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sources [][]byte               `protobuf:"bytes,1,rep,name=sources"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttachResponse_Welcome) Reset() {
	*x = AttachResponse_Welcome{}
	mi := &file_shale_ingest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse_Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse_Welcome) ProtoMessage() {}

func (x *AttachResponse_Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_shale_ingest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttachResponse_Welcome) GetSources() [][]byte {
	if x != nil {
		return x.xxx_hidden_Sources
	}
	return nil
}

func (x *AttachResponse_Welcome) SetSources(v [][]byte) {
	x.xxx_hidden_Sources = v
}

type AttachResponse_Welcome_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sources [][]byte
}

func (b0 AttachResponse_Welcome_builder) Build() *AttachResponse_Welcome {
	m0 := &AttachResponse_Welcome{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sources = b.Sources
	return m0
}

var File_shale_ingest_proto protoreflect.FileDescriptor

const file_shale_ingest_proto_rawDesc = "" +
	"\n" +
	"\x12shale/ingest.proto\x12\x05shale\"\xec\x01\n" +
	"\rAttachRequest\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.shale.AttachRequest.HelloH\x00R\x05hello\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x19.shale.AttachRequest.DataH\x00R\x04data\x1a,\n" +
	"\x05Hello\x12#\n" +
	"\rpublish_token\x18\x01 \x01(\tR\fpublishToken\x1a=\n" +
	"\x04Data\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\fR\bsourceId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\t\n" +
	"\amessage\"\xad\x02\n" +
	"\x0eAttachResponse\x123\n" +
	"\x05start\x18\x01 \x01(\v2\x1b.shale.AttachResponse.StartH\x00R\x05start\x120\n" +
	"\x04stop\x18\x02 \x01(\v2\x1a.shale.AttachResponse.StopH\x00R\x04stop\x129\n" +
	"\awelcome\x18\x03 \x01(\v2\x1d.shale.AttachResponse.WelcomeH\x00R\awelcome\x1a$\n" +
	"\x05Start\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\fR\bsourceId\x1a#\n" +
	"\x04Stop\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\fR\bsourceId\x1a#\n" +
	"\aWelcome\x12\x18\n" +
	"\asources\x18\x01 \x03(\fR\asourcesB\t\n" +
	"\amessage2H\n" +
	"\vRelayIngest\x129\n" +
	"\x06Attach\x12\x14.shale.AttachRequest\x1a\x15.shale.AttachResponse(\x010\x01B$Z\x1dgithub.com/lesomnus/shale/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_shale_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_shale_ingest_proto_goTypes = []any{
	(*AttachRequest)(nil),          // 0: shale.AttachRequest
	(*AttachResponse)(nil),         // 1: shale.AttachResponse
	(*AttachRequest_Hello)(nil),    // 2: shale.AttachRequest.Hello
	(*AttachRequest_Data)(nil),     // 3: shale.AttachRequest.Data
	(*AttachResponse_Start)(nil),   // 4: shale.AttachResponse.Start
	(*AttachResponse_Stop)(nil),    // 5: shale.AttachResponse.Stop
	(*AttachResponse_Welcome)(nil), // 6: shale.AttachResponse.Welcome
}
var file_shale_ingest_proto_depIdxs = []int32{
	2, // 0: shale.AttachRequest.hello:type_name -> shale.AttachRequest.Hello
	3, // 1: shale.AttachRequest.data:type_name -> shale.AttachRequest.Data
	4, // 2: shale.AttachResponse.start:type_name -> shale.AttachResponse.Start
	5, // 3: shale.AttachResponse.stop:type_name -> shale.AttachResponse.Stop
	6, // 4: shale.AttachResponse.welcome:type_name -> shale.AttachResponse.Welcome
	0, // 5: shale.RelayIngest.Attach:input_type -> shale.AttachRequest
	1, // 6: shale.RelayIngest.Attach:output_type -> shale.AttachResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shale_ingest_proto_init() }
func file_shale_ingest_proto_init() {
	if File_shale_ingest_proto != nil {
		return
	}
	file_shale_ingest_proto_msgTypes[0].OneofWrappers = []any{
		(*attachRequest_Hello_)(nil),
		(*attachRequest_Data_)(nil),
	}
	file_shale_ingest_proto_msgTypes[1].OneofWrappers = []any{
		(*attachResponse_Start_)(nil),
		(*attachResponse_Stop_)(nil),
		(*attachResponse_Welcome_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_ingest_proto_rawDesc), len(file_shale_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shale_ingest_proto_goTypes,
		DependencyIndexes: file_shale_ingest_proto_depIdxs,
		MessageInfos:      file_shale_ingest_proto_msgTypes,
	}.Build()
	File_shale_ingest_proto = out.File
	file_shale_ingest_proto_goTypes = nil
	file_shale_ingest_proto_depIdxs = nil
}
