// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package api

import (
	bytes "bytes"
)

func (x *SiteMemberRef) Pick() *SiteMemberGetRequest {
	return SiteMemberGetRequest_builder{Ref: x}.Build()
}

func (x *SiteMember) Ref() *SiteMemberRef {
	if v := x.GetId(); len(v) > 0 {
		return SiteMemberById(v)
	}

	return nil
}

func (x *SiteMember) Pick() *SiteMemberGetRequest {
	return x.Ref().Pick()
}

func (x *SiteMemberRef) Picks(v *SiteMember) bool {
	switch x.WhichKey() {
	case SiteMemberRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *SiteMemberGetRequest) WithSelect(f func(s *SiteMemberSelect)) *SiteMemberGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&SiteMemberSelect{})
	}
	f(x.GetSelect())
	return x
}

func SiteMemberById(v []byte) *SiteMemberRef {
	x := &SiteMemberRef{}
	x.SetId(v)
	return x
}

func SiteMemberGetById(v []byte) *SiteMemberGetRequest {
	return SiteMemberGetRequest_builder{Ref: SiteMemberById(v)}.Build()
}
