// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shale/object.proto

package api

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObjectState is the object machine of §8.
type ObjectState int32

const (
	ObjectState_OBJECT_STATE_UNSPECIFIED ObjectState = 0
	ObjectState_OBJECT_STATE_PENDING     ObjectState = 1
	ObjectState_OBJECT_STATE_COMMITTED   ObjectState = 2
	ObjectState_OBJECT_STATE_DELETING    ObjectState = 3
	ObjectState_OBJECT_STATE_DELETED     ObjectState = 4
	ObjectState_OBJECT_STATE_LOST        ObjectState = 5
)

// Enum value maps for ObjectState.
var (
	ObjectState_name = map[int32]string{
		0: "OBJECT_STATE_UNSPECIFIED",
		1: "OBJECT_STATE_PENDING",
		2: "OBJECT_STATE_COMMITTED",
		3: "OBJECT_STATE_DELETING",
		4: "OBJECT_STATE_DELETED",
		5: "OBJECT_STATE_LOST",
	}
	ObjectState_value = map[string]int32{
		"OBJECT_STATE_UNSPECIFIED": 0,
		"OBJECT_STATE_PENDING":     1,
		"OBJECT_STATE_COMMITTED":   2,
		"OBJECT_STATE_DELETING":    3,
		"OBJECT_STATE_DELETED":     4,
		"OBJECT_STATE_LOST":        5,
	}
)

func (x ObjectState) Enum() *ObjectState {
	p := new(ObjectState)
	*p = x
	return p
}

func (x ObjectState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectState) Descriptor() protoreflect.EnumDescriptor {
	return file_shale_object_proto_enumTypes[0].Descriptor()
}

func (ObjectState) Type() protoreflect.EnumType {
	return &file_shale_object_proto_enumTypes[0]
}

func (x ObjectState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// AttemptState is the write-attempt machine of §8.
type AttemptState int32

const (
	AttemptState_ATTEMPT_STATE_UNSPECIFIED AttemptState = 0
	AttemptState_ATTEMPT_STATE_ALLOCATED   AttemptState = 1
	AttemptState_ATTEMPT_STATE_STORED      AttemptState = 2
	AttemptState_ATTEMPT_STATE_FAILED      AttemptState = 3
	AttemptState_ATTEMPT_STATE_ABANDONED   AttemptState = 4
	AttemptState_ATTEMPT_STATE_DUPLICATE   AttemptState = 5
)

// Enum value maps for AttemptState.
var (
	AttemptState_name = map[int32]string{
		0: "ATTEMPT_STATE_UNSPECIFIED",
		1: "ATTEMPT_STATE_ALLOCATED",
		2: "ATTEMPT_STATE_STORED",
		3: "ATTEMPT_STATE_FAILED",
		4: "ATTEMPT_STATE_ABANDONED",
		5: "ATTEMPT_STATE_DUPLICATE",
	}
	AttemptState_value = map[string]int32{
		"ATTEMPT_STATE_UNSPECIFIED": 0,
		"ATTEMPT_STATE_ALLOCATED":   1,
		"ATTEMPT_STATE_STORED":      2,
		"ATTEMPT_STATE_FAILED":      3,
		"ATTEMPT_STATE_ABANDONED":   4,
		"ATTEMPT_STATE_DUPLICATE":   5,
	}
)

func (x AttemptState) Enum() *AttemptState {
	p := new(AttemptState)
	*p = x
	return p
}

func (x AttemptState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttemptState) Descriptor() protoreflect.EnumDescriptor {
	return file_shale_object_proto_enumTypes[1].Descriptor()
}

func (AttemptState) Type() protoreflect.EnumType {
	return &file_shale_object_proto_enumTypes[1]
}

func (x AttemptState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Object is the immutable unit of storage, a video segment (§23). Its row is
// the index (§23.3); the truth lives in the sink's xattrs.
//
// Never erased through the API: GC moves it to DELETED and the row is pruned
// later by row retention (§20.4), which is a hard erase the CP performs.
type Object struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant           *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Site             *Site                  `protobuf:"bytes,3,opt,name=site"`
	xxx_hidden_Set              *Set                   `protobuf:"bytes,8,opt,name=set"`
	xxx_hidden_Source           *Source                `protobuf:"bytes,9,opt,name=source"`
	xxx_hidden_Sink             *Sink                  `protobuf:"bytes,10,opt,name=sink"`
	xxx_hidden_ObjectKey        string                 `protobuf:"bytes,11,opt,name=object_key,json=objectKey"`
	xxx_hidden_State            ObjectState            `protobuf:"varint,12,opt,name=state,enum=shale.ObjectState"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_DateStarted      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=date_started,json=dateStarted"`
	xxx_hidden_DateEnded        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=date_ended,json=dateEnded"`
	xxx_hidden_EndedEstimated   bool                   `protobuf:"varint,18,opt,name=ended_estimated,json=endedEstimated"`
	xxx_hidden_Size             int64                  `protobuf:"varint,19,opt,name=size"`
	xxx_hidden_Incomplete       bool                   `protobuf:"varint,20,opt,name=incomplete"`
	xxx_hidden_DateExpired      *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=date_expired,json=dateExpired"`
	xxx_hidden_DateDeleted      *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=date_deleted,json=dateDeleted"`
	xxx_hidden_DatesSynced      bool                   `protobuf:"varint,23,opt,name=dates_synced,json=datesSynced"`
	xxx_hidden_PlacementVersion int64                  `protobuf:"varint,24,opt,name=placement_version,json=placementVersion"`
	xxx_hidden_DateCommitted    *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=date_committed,json=dateCommitted"`
	xxx_hidden_DateFinished     *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_finished,json=dateFinished"`
	xxx_hidden_Checksum         []byte                 `protobuf:"bytes,27,opt,name=checksum"`
	xxx_hidden_Epoch            int64                  `protobuf:"varint,28,opt,name=epoch"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_shale_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_shale_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Object) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Object) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Object) GetSite() *Site {
	if x != nil {
		return x.xxx_hidden_Site
	}
	return nil
}

func (x *Object) GetSet() *Set {
	if x != nil {
		return x.xxx_hidden_Set
	}
	return nil
}

func (x *Object) GetSource() *Source {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Object) GetSink() *Sink {
	if x != nil {
		return x.xxx_hidden_Sink
	}
	return nil
}

func (x *Object) GetObjectKey() string {
	if x != nil {
		return x.xxx_hidden_ObjectKey
	}
	return ""
}

func (x *Object) GetState() ObjectState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ObjectState_OBJECT_STATE_UNSPECIFIED
}

func (x *Object) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Object) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Object) GetDateStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateStarted
	}
	return nil
}

func (x *Object) GetDateEnded() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateEnded
	}
	return nil
}

func (x *Object) GetEndedEstimated() bool {
	if x != nil {
		return x.xxx_hidden_EndedEstimated
	}
	return false
}

func (x *Object) GetSize() int64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *Object) GetIncomplete() bool {
	if x != nil {
		return x.xxx_hidden_Incomplete
	}
	return false
}

func (x *Object) GetDateExpired() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateExpired
	}
	return nil
}

func (x *Object) GetDateDeleted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateDeleted
	}
	return nil
}

func (x *Object) GetDatesSynced() bool {
	if x != nil {
		return x.xxx_hidden_DatesSynced
	}
	return false
}

func (x *Object) GetPlacementVersion() int64 {
	if x != nil {
		return x.xxx_hidden_PlacementVersion
	}
	return 0
}

func (x *Object) GetDateCommitted() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCommitted
	}
	return nil
}

func (x *Object) GetDateFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateFinished
	}
	return nil
}

func (x *Object) GetChecksum() []byte {
	if x != nil {
		return x.xxx_hidden_Checksum
	}
	return nil
}

func (x *Object) GetEpoch() int64 {
	if x != nil {
		return x.xxx_hidden_Epoch
	}
	return 0
}

func (x *Object) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Object) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Object) SetSite(v *Site) {
	x.xxx_hidden_Site = v
}

func (x *Object) SetSet(v *Set) {
	x.xxx_hidden_Set = v
}

func (x *Object) SetSource(v *Source) {
	x.xxx_hidden_Source = v
}

func (x *Object) SetSink(v *Sink) {
	x.xxx_hidden_Sink = v
}

func (x *Object) SetObjectKey(v string) {
	x.xxx_hidden_ObjectKey = v
}

func (x *Object) SetState(v ObjectState) {
	x.xxx_hidden_State = v
}

func (x *Object) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Object) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Object) SetDateStarted(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateStarted = v
}

func (x *Object) SetDateEnded(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateEnded = v
}

func (x *Object) SetEndedEstimated(v bool) {
	x.xxx_hidden_EndedEstimated = v
}

func (x *Object) SetSize(v int64) {
	x.xxx_hidden_Size = v
}

func (x *Object) SetIncomplete(v bool) {
	x.xxx_hidden_Incomplete = v
}

func (x *Object) SetDateExpired(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateExpired = v
}

func (x *Object) SetDateDeleted(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateDeleted = v
}

func (x *Object) SetDatesSynced(v bool) {
	x.xxx_hidden_DatesSynced = v
}

func (x *Object) SetPlacementVersion(v int64) {
	x.xxx_hidden_PlacementVersion = v
}

func (x *Object) SetDateCommitted(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCommitted = v
}

func (x *Object) SetDateFinished(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateFinished = v
}

func (x *Object) SetChecksum(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Checksum = v
}

func (x *Object) SetEpoch(v int64) {
	x.xxx_hidden_Epoch = v
}

func (x *Object) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Object) HasSite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Site != nil
}

func (x *Object) HasSet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Set != nil
}

func (x *Object) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Object) HasSink() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sink != nil
}

func (x *Object) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Object) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Object) HasDateStarted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateStarted != nil
}

func (x *Object) HasDateEnded() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateEnded != nil
}

func (x *Object) HasDateExpired() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateExpired != nil
}

func (x *Object) HasDateDeleted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateDeleted != nil
}

func (x *Object) HasDateCommitted() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCommitted != nil
}

func (x *Object) HasDateFinished() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFinished != nil
}

func (x *Object) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Object) ClearSite() {
	x.xxx_hidden_Site = nil
}

func (x *Object) ClearSet() {
	x.xxx_hidden_Set = nil
}

func (x *Object) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *Object) ClearSink() {
	x.xxx_hidden_Sink = nil
}

func (x *Object) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Object) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *Object) ClearDateStarted() {
	x.xxx_hidden_DateStarted = nil
}

func (x *Object) ClearDateEnded() {
	x.xxx_hidden_DateEnded = nil
}

func (x *Object) ClearDateExpired() {
	x.xxx_hidden_DateExpired = nil
}

func (x *Object) ClearDateDeleted() {
	x.xxx_hidden_DateDeleted = nil
}

func (x *Object) ClearDateCommitted() {
	x.xxx_hidden_DateCommitted = nil
}

func (x *Object) ClearDateFinished() {
	x.xxx_hidden_DateFinished = nil
}

type Object_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	Site   *Site
	Set    *Set
	Source *Source
	// The sink the object was committed to; null until then.
	Sink *Sink
	// Path within the sink; with the sink, the object's location.
	ObjectKey   string
	State       ObjectState
	DateUpdated *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
	// Data time (§10): declared by the producer.
	DateStarted *timestamppb.Timestamp
	DateEnded   *timestamppb.Timestamp
	// date_ended is an estimate for an incomplete object (§19).
	EndedEstimated bool
	Size           int64
	Incomplete     bool
	DateExpired    *timestamppb.Timestamp
	DateDeleted    *timestamppb.Timestamp
	// False until the node has rewritten the xattr after a reschedule (§20.3).
	DatesSynced      bool
	PlacementVersion int64
	DateCommitted    *timestamppb.Timestamp
	// When the object became DELETED or LOST, for row retention (§20.4).
	DateFinished *timestamppb.Timestamp
	Checksum     []byte
	// The epoch bucket date_started falls in, in seconds since the epoch, so
	// one index answers "the objects of this source in this epoch".
	Epoch int64
}

func (b0 Object_builder) Build() *Object {
	m0 := &Object{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Site = b.Site
	x.xxx_hidden_Set = b.Set
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Sink = b.Sink
	x.xxx_hidden_ObjectKey = b.ObjectKey
	x.xxx_hidden_State = b.State
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_DateStarted = b.DateStarted
	x.xxx_hidden_DateEnded = b.DateEnded
	x.xxx_hidden_EndedEstimated = b.EndedEstimated
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Incomplete = b.Incomplete
	x.xxx_hidden_DateExpired = b.DateExpired
	x.xxx_hidden_DateDeleted = b.DateDeleted
	x.xxx_hidden_DatesSynced = b.DatesSynced
	x.xxx_hidden_PlacementVersion = b.PlacementVersion
	x.xxx_hidden_DateCommitted = b.DateCommitted
	x.xxx_hidden_DateFinished = b.DateFinished
	x.xxx_hidden_Checksum = b.Checksum
	x.xxx_hidden_Epoch = b.Epoch
	return m0
}

// Attempt is one write attempt of an object: one candidate of one allocation
// (§8). FAILED and ABANDONED are the CP's guesses; a late ObjectStored still
// moves it to STORED or DUPLICATE (§14).
type Attempt struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant        *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Site          *Site                  `protobuf:"bytes,3,opt,name=site"`
	xxx_hidden_Object        *Object                `protobuf:"bytes,8,opt,name=object"`
	xxx_hidden_Sink          *Sink                  `protobuf:"bytes,9,opt,name=sink"`
	xxx_hidden_Node          *Node                  `protobuf:"bytes,10,opt,name=node"`
	xxx_hidden_State         AttemptState           `protobuf:"varint,11,opt,name=state,enum=shale.AttemptState"`
	xxx_hidden_FailureReason string                 `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason"`
	xxx_hidden_DateUpdated   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_DateExpires   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=date_expires,json=dateExpires"`
	xxx_hidden_DateFinished  *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=date_finished,json=dateFinished"`
	xxx_hidden_Rank          int32                  `protobuf:"varint,18,opt,name=rank"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Attempt) Reset() {
	*x = Attempt{}
	mi := &file_shale_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attempt) ProtoMessage() {}

func (x *Attempt) ProtoReflect() protoreflect.Message {
	mi := &file_shale_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Attempt) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Attempt) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Attempt) GetSite() *Site {
	if x != nil {
		return x.xxx_hidden_Site
	}
	return nil
}

func (x *Attempt) GetObject() *Object {
	if x != nil {
		return x.xxx_hidden_Object
	}
	return nil
}

func (x *Attempt) GetSink() *Sink {
	if x != nil {
		return x.xxx_hidden_Sink
	}
	return nil
}

func (x *Attempt) GetNode() *Node {
	if x != nil {
		return x.xxx_hidden_Node
	}
	return nil
}

func (x *Attempt) GetState() AttemptState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return AttemptState_ATTEMPT_STATE_UNSPECIFIED
}

func (x *Attempt) GetFailureReason() string {
	if x != nil {
		return x.xxx_hidden_FailureReason
	}
	return ""
}

func (x *Attempt) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Attempt) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Attempt) GetDateExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateExpires
	}
	return nil
}

func (x *Attempt) GetDateFinished() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateFinished
	}
	return nil
}

func (x *Attempt) GetRank() int32 {
	if x != nil {
		return x.xxx_hidden_Rank
	}
	return 0
}

func (x *Attempt) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Attempt) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Attempt) SetSite(v *Site) {
	x.xxx_hidden_Site = v
}

func (x *Attempt) SetObject(v *Object) {
	x.xxx_hidden_Object = v
}

func (x *Attempt) SetSink(v *Sink) {
	x.xxx_hidden_Sink = v
}

func (x *Attempt) SetNode(v *Node) {
	x.xxx_hidden_Node = v
}

func (x *Attempt) SetState(v AttemptState) {
	x.xxx_hidden_State = v
}

func (x *Attempt) SetFailureReason(v string) {
	x.xxx_hidden_FailureReason = v
}

func (x *Attempt) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Attempt) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Attempt) SetDateExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateExpires = v
}

func (x *Attempt) SetDateFinished(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateFinished = v
}

func (x *Attempt) SetRank(v int32) {
	x.xxx_hidden_Rank = v
}

func (x *Attempt) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Attempt) HasSite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Site != nil
}

func (x *Attempt) HasObject() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Object != nil
}

func (x *Attempt) HasSink() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Sink != nil
}

func (x *Attempt) HasNode() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Node != nil
}

func (x *Attempt) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Attempt) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Attempt) HasDateExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateExpires != nil
}

func (x *Attempt) HasDateFinished() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateFinished != nil
}

func (x *Attempt) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Attempt) ClearSite() {
	x.xxx_hidden_Site = nil
}

func (x *Attempt) ClearObject() {
	x.xxx_hidden_Object = nil
}

func (x *Attempt) ClearSink() {
	x.xxx_hidden_Sink = nil
}

func (x *Attempt) ClearNode() {
	x.xxx_hidden_Node = nil
}

func (x *Attempt) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Attempt) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

func (x *Attempt) ClearDateExpires() {
	x.xxx_hidden_DateExpires = nil
}

func (x *Attempt) ClearDateFinished() {
	x.xxx_hidden_DateFinished = nil
}

type Attempt_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	Site   *Site
	Object *Object
	Sink   *Sink
	// The node the sink was on when the attempt was allocated.
	Node          *Node
	State         AttemptState
	FailureReason string
	DateUpdated   *timestamppb.Timestamp
	DateCreated   *timestamppb.Timestamp
	// The end of the allocation's TTL; the token expires with it.
	DateExpires  *timestamppb.Timestamp
	DateFinished *timestamppb.Timestamp
	// Position in the allocation's ranking, 0 first.
	Rank int32
}

func (b0 Attempt_builder) Build() *Attempt {
	m0 := &Attempt{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Site = b.Site
	x.xxx_hidden_Object = b.Object
	x.xxx_hidden_Sink = b.Sink
	x.xxx_hidden_Node = b.Node
	x.xxx_hidden_State = b.State
	x.xxx_hidden_FailureReason = b.FailureReason
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_DateExpires = b.DateExpires
	x.xxx_hidden_DateFinished = b.DateFinished
	x.xxx_hidden_Rank = b.Rank
	return m0
}

var File_shale_object_proto protoreflect.FileDescriptor

const file_shale_object_proto_rawDesc = "" +
	"\n" +
	"\x12shale/object.proto\x12\x05shale\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\x1a\x10shale/host.proto\x1a\x19shale/payday/tenant.proto\x1a\x0fshale/set.proto\x1a\x10shale/site.proto\x1a\x13shale/storage.proto\"\xb6\v\n" +
	"\x06Object\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12-\n" +
	"\x06tenant\x18\x02 \x01(\v2\r.shale.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12)\n" +
	"\x04site\x18\x03 \x01(\v2\v.shale.SiteB\b\xf2\x82\x16\x048\x01@\x01R\x04site\x12$\n" +
	"\x03set\x18\b \x01(\v2\n" +
	".shale.SetB\x06\xf2\x82\x16\x02@\x01R\x03set\x12-\n" +
	"\x06source\x18\t \x01(\v2\r.shale.SourceB\x06\xf2\x82\x16\x02@\x01R\x06source\x12'\n" +
	"\x04sink\x18\n" +
	" \x01(\v2\v.shale.SinkB\x06\xf2\x82\x16\x028\x01R\x04sink\x12\x1d\n" +
	"\n" +
	"object_key\x18\v \x01(\tR\tobjectKey\x12(\n" +
	"\x05state\x18\f \x01(\x0e2\x12.shale.ObjectStateR\x05state\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12F\n" +
	"\fdate_started\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x82\x01\x00R\vdateStarted\x12A\n" +
	"\n" +
	"date_ended\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\tdateEnded\x12'\n" +
	"\x0fended_estimated\x18\x12 \x01(\bR\x0eendedEstimated\x12\x12\n" +
	"\x04size\x18\x13 \x01(\x03R\x04size\x12\x1e\n" +
	"\n" +
	"incomplete\x18\x14 \x01(\bR\n" +
	"incomplete\x12F\n" +
	"\fdate_expired\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x82\x01\x00R\vdateExpired\x12E\n" +
	"\fdate_deleted\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\vdateDeleted\x12!\n" +
	"\fdates_synced\x18\x17 \x01(\bR\vdatesSynced\x12+\n" +
	"\x11placement_version\x18\x18 \x01(\x03R\x10placementVersion\x12I\n" +
	"\x0edate_committed\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\rdateCommitted\x12G\n" +
	"\rdate_finished\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\fdateFinished\x12#\n" +
	"\bchecksum\x18\x1b \x01(\fB\a\xea\x82\x16\x03\x82\x01\x00R\bchecksum\x12\x14\n" +
	"\x05epoch\x18\x1c \x01(\x03R\x05epoch:\xc5\x02\xca\xfc\x15\xe9\x01\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a+\x12\vsource_time\x1a\n" +
	"\n" +
	"\x06source\x10\t\x1a\x10\n" +
	"\fdate_started\x10\x10\x1a%\x12\bset_time\x1a\a\n" +
	"\x03set\x10\b\x1a\x10\n" +
	"\fdate_started\x10\x10\x1a$\x12\blocation\x1a\b\n" +
	"\x04sink\x10\n" +
	"\x1a\x0e\n" +
	"\n" +
	"object_key\x10\v\x1a \x12\x02gc\x1a\b\n" +
	"\x04sink\x10\n" +
	"\x1a\x10\n" +
	"\fdate_expired\x10\x15\x1a%\x12\x05state\x1a\t\n" +
	"\x05state\x10\f\x1a\x11\n" +
	"\rdate_finished\x10\x1a\x8a\xbb\x16S\b\t2I\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\b\n" +
	"\x06tenant\x1a\x05\n" +
	"\x03set\x1a\b\n" +
	"\x06source\x1a\x06\n" +
	"\x04sink d(\xe8\a:\x00B\x02\n" +
	"\x00\"\xd2\x06\n" +
	"\aAttempt\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12-\n" +
	"\x06tenant\x18\x02 \x01(\v2\r.shale.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12)\n" +
	"\x04site\x18\x03 \x01(\v2\v.shale.SiteB\b\xf2\x82\x16\x048\x01@\x01R\x04site\x12-\n" +
	"\x06object\x18\b \x01(\v2\r.shale.ObjectB\x06\xf2\x82\x16\x02@\x01R\x06object\x12'\n" +
	"\x04sink\x18\t \x01(\v2\v.shale.SinkB\x06\xf2\x82\x16\x02@\x01R\x04sink\x12'\n" +
	"\x04node\x18\n" +
	" \x01(\v2\v.shale.NodeB\x06\xf2\x82\x16\x02@\x01R\x04node\x12)\n" +
	"\x05state\x18\v \x01(\x0e2\x13.shale.AttemptStateR\x05state\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x12F\n" +
	"\fdate_expires\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x82\x01\x00R\vdateExpires\x12G\n" +
	"\rdate_finished\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xea\x82\x16\x028\x01R\fdateFinished\x12\x12\n" +
	"\x04rank\x18\x12 \x01(\x05R\x04rank:\xc5\x01\xca\xfc\x15s\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a&\x12\x06object\x1a\n" +
	"\n" +
	"\x06object\x10\b\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a#\x12\x04open\x1a\t\n" +
	"\x05state\x10\v\x1a\x10\n" +
	"\fdate_expires\x10\x10\x8a\xbb\x16J\b\n" +
	"2B\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\b\n" +
	"\x06tenant\x1a\b\n" +
	"\x06object\x1a\x06\n" +
	"\x04sink 2(\xf4\x03B\x02\n" +
	"\x00*\xad\x01\n" +
	"\vObjectState\x12\x1c\n" +
	"\x18OBJECT_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OBJECT_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16OBJECT_STATE_COMMITTED\x10\x02\x12\x19\n" +
	"\x15OBJECT_STATE_DELETING\x10\x03\x12\x18\n" +
	"\x14OBJECT_STATE_DELETED\x10\x04\x12\x15\n" +
	"\x11OBJECT_STATE_LOST\x10\x05*\xb8\x01\n" +
	"\fAttemptState\x12\x1d\n" +
	"\x19ATTEMPT_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ATTEMPT_STATE_ALLOCATED\x10\x01\x12\x18\n" +
	"\x14ATTEMPT_STATE_STORED\x10\x02\x12\x18\n" +
	"\x14ATTEMPT_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17ATTEMPT_STATE_ABANDONED\x10\x04\x12\x1b\n" +
	"\x17ATTEMPT_STATE_DUPLICATE\x10\x05B$Z\x1dgithub.com/lesomnus/shale/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_shale_object_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shale_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shale_object_proto_goTypes = []any{
	(ObjectState)(0),              // 0: shale.ObjectState
	(AttemptState)(0),             // 1: shale.AttemptState
	(*Object)(nil),                // 2: shale.Object
	(*Attempt)(nil),               // 3: shale.Attempt
	(*Tenant)(nil),                // 4: shale.Tenant
	(*Site)(nil),                  // 5: shale.Site
	(*Set)(nil),                   // 6: shale.Set
	(*Source)(nil),                // 7: shale.Source
	(*Sink)(nil),                  // 8: shale.Sink
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*Node)(nil),                  // 10: shale.Node
}
var file_shale_object_proto_depIdxs = []int32{
	4,  // 0: shale.Object.tenant:type_name -> shale.Tenant
	5,  // 1: shale.Object.site:type_name -> shale.Site
	6,  // 2: shale.Object.set:type_name -> shale.Set
	7,  // 3: shale.Object.source:type_name -> shale.Source
	8,  // 4: shale.Object.sink:type_name -> shale.Sink
	0,  // 5: shale.Object.state:type_name -> shale.ObjectState
	9,  // 6: shale.Object.date_updated:type_name -> google.protobuf.Timestamp
	9,  // 7: shale.Object.date_created:type_name -> google.protobuf.Timestamp
	9,  // 8: shale.Object.date_started:type_name -> google.protobuf.Timestamp
	9,  // 9: shale.Object.date_ended:type_name -> google.protobuf.Timestamp
	9,  // 10: shale.Object.date_expired:type_name -> google.protobuf.Timestamp
	9,  // 11: shale.Object.date_deleted:type_name -> google.protobuf.Timestamp
	9,  // 12: shale.Object.date_committed:type_name -> google.protobuf.Timestamp
	9,  // 13: shale.Object.date_finished:type_name -> google.protobuf.Timestamp
	4,  // 14: shale.Attempt.tenant:type_name -> shale.Tenant
	5,  // 15: shale.Attempt.site:type_name -> shale.Site
	2,  // 16: shale.Attempt.object:type_name -> shale.Object
	8,  // 17: shale.Attempt.sink:type_name -> shale.Sink
	10, // 18: shale.Attempt.node:type_name -> shale.Node
	1,  // 19: shale.Attempt.state:type_name -> shale.AttemptState
	9,  // 20: shale.Attempt.date_updated:type_name -> google.protobuf.Timestamp
	9,  // 21: shale.Attempt.date_created:type_name -> google.protobuf.Timestamp
	9,  // 22: shale.Attempt.date_expires:type_name -> google.protobuf.Timestamp
	9,  // 23: shale.Attempt.date_finished:type_name -> google.protobuf.Timestamp
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_shale_object_proto_init() }
func file_shale_object_proto_init() {
	if File_shale_object_proto != nil {
		return
	}
	file_shale_host_proto_init()
	file_shale_payday_tenant_proto_init()
	file_shale_set_proto_init()
	file_shale_site_proto_init()
	file_shale_storage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_object_proto_rawDesc), len(file_shale_object_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shale_object_proto_goTypes,
		DependencyIndexes: file_shale_object_proto_depIdxs,
		EnumInfos:         file_shale_object_proto_enumTypes,
		MessageInfos:      file_shale_object_proto_msgTypes,
	}.Build()
	File_shale_object_proto = out.File
	file_shale_object_proto_goTypes = nil
	file_shale_object_proto_depIdxs = nil
}
