// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shale/site.proto

package api

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Site groups sets within a tenant, e.g. a building or a branch (§7). It is
// payday's second permission axis: field 3 of Set, Source, Lamina, Attempt,
// Producer, and SiteMember names one, so a person or a reader limited to the
// sites it is a member of cannot read another site's cameras.
type Site struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant        *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias         string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name          string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc          string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RelaySelector map[string]string      `protobuf:"bytes,8,rep,name=relay_selector,json=relaySelector" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateUpdated   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_shale_site_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_shale_site_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Site) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Site) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Site) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Site) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Site) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Site) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *Site) GetRelaySelector() map[string]string {
	if x != nil {
		return x.xxx_hidden_RelaySelector
	}
	return nil
}

func (x *Site) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Site) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Site) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Site) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Site) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Site) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Site) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Site) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Site) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *Site) SetRelaySelector(v map[string]string) {
	x.xxx_hidden_RelaySelector = v
}

func (x *Site) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Site) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Site) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Site) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Site) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Site) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Site) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Site) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Site) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Site) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Site) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Site_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	Alias  string
	Name   string
	Desc   string
	Labels map[string]string
	// Labels a relay must carry to serve this site's producers (§39.2). Empty
	// means any relay.
	RelaySelector map[string]string
	DateUpdated   *timestamppb.Timestamp
	DateErased    *timestamppb.Timestamp
	DateCreated   *timestamppb.Timestamp
}

func (b0 Site_builder) Build() *Site {
	m0 := &Site{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_RelaySelector = b.RelaySelector
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_shale_site_proto protoreflect.FileDescriptor

const file_shale_site_proto_rawDesc = "" +
	"\n" +
	"\x10shale/site.proto\x12\x05shale\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\x1a\x19shale/payday/tenant.proto\"\xe4\x05\n" +
	"\x04Site\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12-\n" +
	"\x06tenant\x18\x02 \x01(\v2\r.shale.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12/\n" +
	"\x06labels\x18\a \x03(\v2\x17.shale.Site.LabelsEntryR\x06labels\x12E\n" +
	"\x0erelay_selector\x18\b \x03(\v2\x1e.shale.Site.RelaySelectorEntryR\rrelaySelector\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12RelaySelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x84\x01\xca\xfc\x15G\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x1f\x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x04\x1a\n" +
	"\n" +
	"\x06tenant\x10\x020\x01\x8a\xbb\x165\b\x132/\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref\x1a\b\n" +
	"\x06tenant \x14(d:\x00B$Z\x1dgithub.com/lesomnus/shale/api\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_shale_site_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shale_site_proto_goTypes = []any{
	(*Site)(nil),                  // 0: shale.Site
	nil,                           // 1: shale.Site.LabelsEntry
	nil,                           // 2: shale.Site.RelaySelectorEntry
	(*Tenant)(nil),                // 3: shale.Tenant
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_shale_site_proto_depIdxs = []int32{
	3, // 0: shale.Site.tenant:type_name -> shale.Tenant
	1, // 1: shale.Site.labels:type_name -> shale.Site.LabelsEntry
	2, // 2: shale.Site.relay_selector:type_name -> shale.Site.RelaySelectorEntry
	4, // 3: shale.Site.date_updated:type_name -> google.protobuf.Timestamp
	4, // 4: shale.Site.date_erased:type_name -> google.protobuf.Timestamp
	4, // 5: shale.Site.date_created:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_shale_site_proto_init() }
func file_shale_site_proto_init() {
	if File_shale_site_proto != nil {
		return
	}
	file_shale_payday_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_site_proto_rawDesc), len(file_shale_site_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shale_site_proto_goTypes,
		DependencyIndexes: file_shale_site_proto_depIdxs,
		MessageInfos:      file_shale_site_proto_msgTypes,
	}.Build()
	File_shale_site_proto = out.File
	file_shale_site_proto_goTypes = nil
	file_shale_site_proto_depIdxs = nil
}
