// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shale/payday/tenant_svc.g.proto

package api

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantAddRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id            []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias         string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name          string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc          string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated   *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_CapacityShare float64                `protobuf:"fixed64,8,opt,name=capacity_share,json=capacityShare"`
	xxx_hidden_StoredBytes   int64                  `protobuf:"varint,9,opt,name=stored_bytes,json=storedBytes"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TenantAddRequest) Reset() {
	*x = TenantAddRequest{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAddRequest) ProtoMessage() {}

func (x *TenantAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *TenantAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *TenantAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TenantAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *TenantAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *TenantAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *TenantAddRequest) GetCapacityShare() float64 {
	if x != nil {
		return x.xxx_hidden_CapacityShare
	}
	return 0
}

func (x *TenantAddRequest) GetStoredBytes() int64 {
	if x != nil {
		return x.xxx_hidden_StoredBytes
	}
	return 0
}

func (x *TenantAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *TenantAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *TenantAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TenantAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *TenantAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *TenantAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *TenantAddRequest) SetCapacityShare(v float64) {
	x.xxx_hidden_CapacityShare = v
}

func (x *TenantAddRequest) SetStoredBytes(v int64) {
	x.xxx_hidden_StoredBytes = v
}

func (x *TenantAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TenantAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *TenantAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *TenantAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type TenantAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id            []byte
	Alias         string
	Name          string
	Desc          string
	Labels        map[string]string
	DateCreated   *timestamppb.Timestamp
	CapacityShare float64
	StoredBytes   int64
}

func (b0 TenantAddRequest_builder) Build() *TenantAddRequest {
	m0 := &TenantAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	x.xxx_hidden_CapacityShare = b.CapacityShare
	x.xxx_hidden_StoredBytes = b.StoredBytes
	return m0
}

type TenantGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *TenantSelect          `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TenantGetRequest) Reset() {
	*x = TenantGetRequest{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantGetRequest) ProtoMessage() {}

func (x *TenantGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantGetRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantGetRequest) GetSelect() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *TenantGetRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantGetRequest) SetSelect(v *TenantSelect) {
	x.xxx_hidden_Select = v
}

func (x *TenantGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *TenantGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type TenantGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *TenantRef
	Select *TenantSelect
}

func (b0 TenantGetRequest_builder) Build() *TenantGetRequest {
	m0 := &TenantGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type TenantRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isTenantRef_Key        `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantRef) Reset() {
	*x = TenantRef{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRef) ProtoMessage() {}

func (x *TenantRef) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*tenantRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *TenantRef) GetAlias() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*tenantRef_Alias); ok {
			return x.Alias
		}
	}
	return ""
}

func (x *TenantRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &tenantRef_Id{v}
}

func (x *TenantRef) SetAlias(v string) {
	x.xxx_hidden_Key = &tenantRef_Alias{v}
}

func (x *TenantRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *TenantRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*tenantRef_Id)
	return ok
}

func (x *TenantRef) HasAlias() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*tenantRef_Alias)
	return ok
}

func (x *TenantRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *TenantRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*tenantRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *TenantRef) ClearAlias() {
	if _, ok := x.xxx_hidden_Key.(*tenantRef_Alias); ok {
		x.xxx_hidden_Key = nil
	}
}

const TenantRef_Key_not_set_case case_TenantRef_Key = 0
const TenantRef_Id_case case_TenantRef_Key = 1
const TenantRef_Alias_case case_TenantRef_Key = 4

func (x *TenantRef) WhichKey() case_TenantRef_Key {
	if x == nil {
		return TenantRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *tenantRef_Id:
		return TenantRef_Id_case
	case *tenantRef_Alias:
		return TenantRef_Alias_case
	default:
		return TenantRef_Key_not_set_case
	}
}

type TenantRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id    []byte
	Alias *string
	// -- end of xxx_hidden_Key
}

func (b0 TenantRef_builder) Build() *TenantRef {
	m0 := &TenantRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &tenantRef_Id{b.Id}
	}
	if b.Alias != nil {
		x.xxx_hidden_Key = &tenantRef_Alias{*b.Alias}
	}
	return m0
}

type case_TenantRef_Key protoreflect.FieldNumber

func (x case_TenantRef_Key) String() string {
	md := file_shale_payday_tenant_svc_g_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTenantRef_Key interface {
	isTenantRef_Key()
}

type tenantRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type tenantRef_Alias struct {
	Alias string `protobuf:"bytes,4,opt,name=alias,oneof"`
}

func (*tenantRef_Id) isTenantRef_Key() {}

func (*tenantRef_Alias) isTenantRef_Key() {}

type TenantSelect struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All           bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Alias         bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name          bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc          bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels        bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_DateUpdated   bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated   bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	xxx_hidden_CapacityShare bool                   `protobuf:"varint,8,opt,name=capacity_share,json=capacityShare"`
	xxx_hidden_StoredBytes   bool                   `protobuf:"varint,9,opt,name=stored_bytes,json=storedBytes"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TenantSelect) Reset() {
	*x = TenantSelect{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSelect) ProtoMessage() {}

func (x *TenantSelect) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *TenantSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *TenantSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *TenantSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *TenantSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *TenantSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *TenantSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *TenantSelect) GetCapacityShare() bool {
	if x != nil {
		return x.xxx_hidden_CapacityShare
	}
	return false
}

func (x *TenantSelect) GetStoredBytes() bool {
	if x != nil {
		return x.xxx_hidden_StoredBytes
	}
	return false
}

func (x *TenantSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *TenantSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *TenantSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *TenantSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *TenantSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *TenantSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *TenantSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *TenantSelect) SetCapacityShare(v bool) {
	x.xxx_hidden_CapacityShare = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *TenantSelect) SetStoredBytes(v bool) {
	x.xxx_hidden_StoredBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *TenantSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TenantSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TenantSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TenantSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TenantSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TenantSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TenantSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TenantSelect) HasCapacityShare() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *TenantSelect) HasStoredBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *TenantSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *TenantSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = false
}

func (x *TenantSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = false
}

func (x *TenantSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = false
}

func (x *TenantSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Labels = false
}

func (x *TenantSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DateUpdated = false
}

func (x *TenantSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateCreated = false
}

func (x *TenantSelect) ClearCapacityShare() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_CapacityShare = false
}

func (x *TenantSelect) ClearStoredBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_StoredBytes = false
}

type TenantSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All           *bool
	Alias         *bool
	Name          *bool
	Desc          *bool
	Labels        *bool
	DateUpdated   *bool
	DateCreated   *bool
	CapacityShare *bool
	StoredBytes   *bool
}

func (b0 TenantSelect_builder) Build() *TenantSelect {
	m0 := &TenantSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_All = *b.All
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	if b.CapacityShare != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_CapacityShare = *b.CapacityShare
	}
	if b.StoredBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_StoredBytes = *b.StoredBytes
	}
	return m0
}

type TenantPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias            *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name             *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Desc             *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	xxx_hidden_CapacityShare    float64                `protobuf:"fixed64,16,opt,name=capacity_share,json=capacityShare"`
	xxx_hidden_StoredBytes      int64                  `protobuf:"varint,18,opt,name=stored_bytes,json=storedBytes"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TenantPatchRequest) Reset() {
	*x = TenantPatchRequest{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPatchRequest) ProtoMessage() {}

func (x *TenantPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantPatchRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *TenantPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *TenantPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *TenantPatchRequest) GetCapacityShare() float64 {
	if x != nil {
		return x.xxx_hidden_CapacityShare
	}
	return 0
}

func (x *TenantPatchRequest) GetStoredBytes() int64 {
	if x != nil {
		return x.xxx_hidden_StoredBytes
	}
	return 0
}

func (x *TenantPatchRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *TenantPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *TenantPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 9)
}

func (x *TenantPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *TenantPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *TenantPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *TenantPatchRequest) SetCapacityShare(v float64) {
	x.xxx_hidden_CapacityShare = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *TenantPatchRequest) SetStoredBytes(v int64) {
	x.xxx_hidden_StoredBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *TenantPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TenantPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TenantPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TenantPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *TenantPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TenantPatchRequest) HasCapacityShare() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *TenantPatchRequest) HasStoredBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *TenantPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *TenantPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *TenantPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

func (x *TenantPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *TenantPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateUpdatedForce = false
}

func (x *TenantPatchRequest) ClearCapacityShare() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_CapacityShare = 0
}

func (x *TenantPatchRequest) ClearStoredBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_StoredBytes = 0
}

type TenantPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *TenantRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
	CapacityShare    *float64
	StoredBytes      *int64
}

func (b0 TenantPatchRequest_builder) Build() *TenantPatchRequest {
	m0 := &TenantPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 9)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	if b.CapacityShare != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_CapacityShare = *b.CapacityShare
	}
	if b.StoredBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_StoredBytes = *b.StoredBytes
	}
	return m0
}

type TenantApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantApplyRequest) Reset() {
	*x = TenantApplyRequest{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantApplyRequest) ProtoMessage() {}

func (x *TenantApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantApplyRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *TenantApplyRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *TenantApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *TenantApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type TenantApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *TenantRef
	Patch *patchpb.Patch
}

func (b0 TenantApplyRequest_builder) Build() *TenantApplyRequest {
	m0 := &TenantApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type TenantEraseResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Erased      bool                   `protobuf:"varint,1,opt,name=erased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TenantEraseResponse) Reset() {
	*x = TenantEraseResponse{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantEraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantEraseResponse) ProtoMessage() {}

func (x *TenantEraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantEraseResponse) GetErased() bool {
	if x != nil {
		return x.xxx_hidden_Erased
	}
	return false
}

func (x *TenantEraseResponse) SetErased(v bool) {
	x.xxx_hidden_Erased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TenantEraseResponse) HasErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TenantEraseResponse) ClearErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Erased = false
}

type TenantEraseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Erased is whether this call is the one that erased the row.
	//
	// False for a row that was already gone, was never there, or is out
	// of this caller's reach -- which are one answer on purpose, and the
	// reason the RPC does not fail instead.
	Erased *bool
}

func (b0 TenantEraseResponse_builder) Build() *TenantEraseResponse {
	m0 := &TenantEraseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Erased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Erased = *b.Erased
	}
	return m0
}

type TenantListRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Filters *[]*TenantFilter       `protobuf:"bytes,1,rep,name=filters"`
	xxx_hidden_Size    int32                  `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_After   string                 `protobuf:"bytes,3,opt,name=after"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TenantListRequest) Reset() {
	*x = TenantListRequest{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListRequest) ProtoMessage() {}

func (x *TenantListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantListRequest) GetFilters() []*TenantFilter {
	if x != nil {
		if x.xxx_hidden_Filters != nil {
			return *x.xxx_hidden_Filters
		}
	}
	return nil
}

func (x *TenantListRequest) GetSize() int32 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *TenantListRequest) GetAfter() string {
	if x != nil {
		return x.xxx_hidden_After
	}
	return ""
}

func (x *TenantListRequest) SetFilters(v []*TenantFilter) {
	x.xxx_hidden_Filters = &v
}

func (x *TenantListRequest) SetSize(v int32) {
	x.xxx_hidden_Size = v
}

func (x *TenantListRequest) SetAfter(v string) {
	x.xxx_hidden_After = v
}

type TenantListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Bounded because the work is: each filter is a predicate in the same query,
	// so this is what says how much of the database one request may read.
	Filters []*TenantFilter
	// How many to answer with. Nothing said is what the schema declared, and more
	// than the cap is the cap -- a caller asking for more than there is meant no
	// harm, so it is not an error and it is not the whole table either.
	Size int32
	// Where to carry on from: the "next" of the answer before. It names the last
	// row of that page rather than counting rows from the start, so a row added
	// ahead of the page does not shift it and a caller reading through never sees
	// one twice or misses one.
	After string
}

func (b0 TenantListRequest_builder) Build() *TenantListRequest {
	m0 := &TenantListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Filters = &b.Filters
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_After = b.After
	return m0
}

type TenantListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *[]*Tenant             `protobuf:"bytes,1,rep,name=items"`
	xxx_hidden_Next  string                 `protobuf:"bytes,2,opt,name=next"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantListResponse) Reset() {
	*x = TenantListResponse{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListResponse) ProtoMessage() {}

func (x *TenantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantListResponse) GetItems() []*Tenant {
	if x != nil {
		if x.xxx_hidden_Items != nil {
			return *x.xxx_hidden_Items
		}
	}
	return nil
}

func (x *TenantListResponse) GetNext() string {
	if x != nil {
		return x.xxx_hidden_Next
	}
	return ""
}

func (x *TenantListResponse) SetItems(v []*Tenant) {
	x.xxx_hidden_Items = &v
}

func (x *TenantListResponse) SetNext(v string) {
	x.xxx_hidden_Next = v
}

type TenantListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items []*Tenant
	// What to ask for next, and empty when this was the last of them.
	//
	// Empty means there is no more *for now*: a list is read as it is, and one
	// that has grown since answers a fresh call. It is not empty merely because
	// the page came back short -- a page is short when the last row of it was the
	// last row there was, which is a thing the server can only know by having
	// looked.
	Next string
}

func (b0 TenantListResponse_builder) Build() *TenantListResponse {
	m0 := &TenantListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = &b.Items
	x.xxx_hidden_Next = b.Next
	return m0
}

type TenantFilter struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantFilter) Reset() {
	*x = TenantFilter{}
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantFilter) ProtoMessage() {}

func (x *TenantFilter) ProtoReflect() protoreflect.Message {
	mi := &file_shale_payday_tenant_svc_g_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantFilter) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantFilter) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantFilter) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantFilter) ClearRef() {
	x.xxx_hidden_Ref = nil
}

type TenantFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref *TenantRef
}

func (b0 TenantFilter_builder) Build() *TenantFilter {
	m0 := &TenantFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	return m0
}

var File_shale_payday_tenant_svc_g_proto protoreflect.FileDescriptor

const file_shale_payday_tenant_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x1fshale/payday/tenant_svc.g.proto\x12\x05shale\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\x1a\x19shale/payday/tenant.proto\"\x84\x03\n" +
	"\x10TenantAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.shale.TenantAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x12,\n" +
	"\x0ecapacity_share\x18\b \x01(\x01B\x05\xaa\x01\x02\b\x02R\rcapacityShare\x12(\n" +
	"\fstored_bytes\x18\t \x01(\x03B\x05\xaa\x01\x02\b\x02R\vstoredBytes\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10TenantGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.TenantRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.shale.TenantSelectR\x06select\"<\n" +
	"\tTenantRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12\x16\n" +
	"\x05alias\x18\x04 \x01(\tH\x00R\x05aliasB\x05\n" +
	"\x03key\"\x86\x02\n" +
	"\fTenantSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\x12%\n" +
	"\x0ecapacity_share\x18\b \x01(\bR\rcapacityShare\x12!\n" +
	"\fstored_bytes\x18\t \x01(\bR\vstoredBytes\"\xa7\x03\n" +
	"\x12TenantPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.TenantRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12=\n" +
	"\x06labels\x18\x0e \x03(\v2%.shale.TenantPatchRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\x12%\n" +
	"\x0ecapacity_share\x18\x10 \x01(\x01R\rcapacityShare\x12!\n" +
	"\fstored_bytes\x18\x12 \x01(\x03R\vstoredBytes\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x12TenantApplyRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.TenantRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"-\n" +
	"\x13TenantEraseResponse\x12\x16\n" +
	"\x06erased\x18\x01 \x01(\bR\x06erased\"z\n" +
	"\x11TenantListRequest\x12-\n" +
	"\afilters\x18\x01 \x03(\v2\x13.shale.TenantFilterR\afilters\x12\x19\n" +
	"\x04size\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x04size\x12\x1b\n" +
	"\x05after\x18\x03 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05after\"T\n" +
	"\x12TenantListResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.shale.TenantR\x05items\x12\x19\n" +
	"\x04next\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04next\"2\n" +
	"\fTenantFilter\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.shale.TenantRefR\x03ref2\xc7\x02\n" +
	"\rTenantService\x12-\n" +
	"\x03Add\x12\x17.shale.TenantAddRequest\x1a\r.shale.Tenant\x12-\n" +
	"\x03Get\x12\x17.shale.TenantGetRequest\x1a\r.shale.Tenant\x121\n" +
	"\x05Patch\x12\x19.shale.TenantPatchRequest\x1a\r.shale.Tenant\x121\n" +
	"\x05Apply\x12\x19.shale.TenantApplyRequest\x1a\r.shale.Tenant\x125\n" +
	"\x05Erase\x12\x10.shale.TenantRef\x1a\x1a.shale.TenantEraseResponse\x12;\n" +
	"\x04List\x12\x18.shale.TenantListRequest\x1a\x19.shale.TenantListResponseB\x1fZ\x1dgithub.com/lesomnus/shale/apib\beditionsp\xe8\a"

var file_shale_payday_tenant_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shale_payday_tenant_svc_g_proto_goTypes = []any{
	(*TenantAddRequest)(nil),      // 0: shale.TenantAddRequest
	(*TenantGetRequest)(nil),      // 1: shale.TenantGetRequest
	(*TenantRef)(nil),             // 2: shale.TenantRef
	(*TenantSelect)(nil),          // 3: shale.TenantSelect
	(*TenantPatchRequest)(nil),    // 4: shale.TenantPatchRequest
	(*TenantApplyRequest)(nil),    // 5: shale.TenantApplyRequest
	(*TenantEraseResponse)(nil),   // 6: shale.TenantEraseResponse
	(*TenantListRequest)(nil),     // 7: shale.TenantListRequest
	(*TenantListResponse)(nil),    // 8: shale.TenantListResponse
	(*TenantFilter)(nil),          // 9: shale.TenantFilter
	nil,                           // 10: shale.TenantAddRequest.LabelsEntry
	nil,                           // 11: shale.TenantPatchRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*patchpb.Patch)(nil),         // 13: patch.Patch
	(*Tenant)(nil),                // 14: shale.Tenant
}
var file_shale_payday_tenant_svc_g_proto_depIdxs = []int32{
	10, // 0: shale.TenantAddRequest.labels:type_name -> shale.TenantAddRequest.LabelsEntry
	12, // 1: shale.TenantAddRequest.date_created:type_name -> google.protobuf.Timestamp
	2,  // 2: shale.TenantGetRequest.ref:type_name -> shale.TenantRef
	3,  // 3: shale.TenantGetRequest.select:type_name -> shale.TenantSelect
	2,  // 4: shale.TenantPatchRequest.ref:type_name -> shale.TenantRef
	11, // 5: shale.TenantPatchRequest.labels:type_name -> shale.TenantPatchRequest.LabelsEntry
	12, // 6: shale.TenantPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	2,  // 7: shale.TenantApplyRequest.ref:type_name -> shale.TenantRef
	13, // 8: shale.TenantApplyRequest.patch:type_name -> patch.Patch
	9,  // 9: shale.TenantListRequest.filters:type_name -> shale.TenantFilter
	14, // 10: shale.TenantListResponse.items:type_name -> shale.Tenant
	2,  // 11: shale.TenantFilter.ref:type_name -> shale.TenantRef
	0,  // 12: shale.TenantService.Add:input_type -> shale.TenantAddRequest
	1,  // 13: shale.TenantService.Get:input_type -> shale.TenantGetRequest
	4,  // 14: shale.TenantService.Patch:input_type -> shale.TenantPatchRequest
	5,  // 15: shale.TenantService.Apply:input_type -> shale.TenantApplyRequest
	2,  // 16: shale.TenantService.Erase:input_type -> shale.TenantRef
	7,  // 17: shale.TenantService.List:input_type -> shale.TenantListRequest
	14, // 18: shale.TenantService.Add:output_type -> shale.Tenant
	14, // 19: shale.TenantService.Get:output_type -> shale.Tenant
	14, // 20: shale.TenantService.Patch:output_type -> shale.Tenant
	14, // 21: shale.TenantService.Apply:output_type -> shale.Tenant
	6,  // 22: shale.TenantService.Erase:output_type -> shale.TenantEraseResponse
	8,  // 23: shale.TenantService.List:output_type -> shale.TenantListResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_shale_payday_tenant_svc_g_proto_init() }
func file_shale_payday_tenant_svc_g_proto_init() {
	if File_shale_payday_tenant_svc_g_proto != nil {
		return
	}
	file_shale_payday_tenant_proto_init()
	file_shale_payday_tenant_svc_g_proto_msgTypes[2].OneofWrappers = []any{
		(*tenantRef_Id)(nil),
		(*tenantRef_Alias)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shale_payday_tenant_svc_g_proto_rawDesc), len(file_shale_payday_tenant_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shale_payday_tenant_svc_g_proto_goTypes,
		DependencyIndexes: file_shale_payday_tenant_svc_g_proto_depIdxs,
		MessageInfos:      file_shale_payday_tenant_svc_g_proto_msgTypes,
	}.Build()
	File_shale_payday_tenant_svc_g_proto = out.File
	file_shale_payday_tenant_svc_g_proto_goTypes = nil
	file_shale_payday_tenant_svc_g_proto_depIdxs = nil
}
